#!/usr/bin/perl

sub doswftest($$)
{
local($test,$testprog)=@_;

$testswf = "./$test.swf";
$testref = "./$test.ref";

print "executing $testprog\n";
if( ! -r $testprog ) {
	printf  STDERR "$test failed. $testprog does not exist\n";
	return 0;
}
if( ! -x $testprog ) {
	printf  STDERR "$test failed. $testprog not executable\n";
	return 0;
}
if( -r $testswf ) {
	system("rm -f $testswf");
}

system($testprog);

if( ! -r $testswf ) {
	printf  STDERR "$test failed. $testswf not created\n";
	return 0;
}
if( ! -r $testref ) {
	printf  STDERR "$test failed. $testref does not exist\n";
	return 0;
}
if( system("listswf $testswf | diff - $testref >/dev/null 2>&1") ) {
	printf  STDERR "$test failed. problem comparing against $testref\n";
	return 0;
}
return 1;
}

sub dotestset($)
{
local($depth) = @_;

local %test;

local $TESTLIST;

print "dotestset depth $depth\n";

open($TESTLIST,"<TestList") || die "Can't find test list";
while(<$TESTLIST>) {
	@test = split(':');
	if( $test[1] eq "swf" ) {
		$test = $test[0];
		$testexe = "./".$test[0];
		$testphp = "./".$test[0].".php";
		$testpl = "./".$test[0].".pl";
		$testpy = "./".$test[0].".py";
		doswftest($test,$testexe);
		#doswftest($test,$testphp);
		doswftest($test,$testpl);
		doswftest($test,$testpy);
	} elsif ( $test[1] eq "dir" ) {
		print "doing tests in ".$test[0]."\n";
		chdir $test[0] || die "Can't cd to ".$test[0]."\n";
		dotestset($depth+1);
		chdir ".." || die "Can't cd ..";
		print "done in ".$test[0]."\n";
	} else {
		print STDERR "Don't know how to handle test type ".$test[1]."\n";
	}
}
print "End of loop for depth $depth\n";
close(TESTLIST);
}

dotestset(0);
