/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3u-20001212-1418 (Alpha 5)
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>

#if defined(_WIN32) || defined(__WIN32__)
#       if defined(_MSC_VER)
#               if defined(STATIC_LINKED)
#                       define SWIGEXPORT(a) a
#               else
#                       define SWIGEXPORT(a) __declspec(dllexport) a
#               endif
#       else
#               if defined(__BORLANDC__)
#                       define SWIGEXPORT(a) a _export
#               else
#                       define SWIGEXPORT(a) a
#       endif
#endif
#else
#       define SWIGEXPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#define SWIGRUNTIME(a) SWIGEXPORT(a)
#else
#define SWIGRUNTIME(a) static a
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef struct swig_type_info {
  char  *name;                 
  void *(*converter)(void *);
  char  *str;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
} swig_type_info;

#ifdef SWIG_NOINCLUDE
SWIGEXPORT(swig_type_info *) SWIG_TypeRegister(swig_type_info *);
SWIGEXPORT(swig_type_info *) SWIG_TypeCheck(char *c, swig_type_info *);
SWIGEXPORT(void *) SWIG_TypeCast(swig_type_info *, void *);
#else

static swig_type_info *swig_type_list = 0;

/* Register a type mapping with the type-checking */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeRegister(swig_type_info *ti)
{
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = swig_type_list;
  while (tc) {
    if (strcmp(tc->name, ti->name) == 0) {
      /* Already exists in the table.  Just add additional types to the list */
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = swig_type_list;
  swig_type_list = ti;

  /* Build linked lists */
 l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  head->next = next;
  return ret;
}

/* Check the typename */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeCheck(char *c, swig_type_info *ty)
{
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  while (s) {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
	s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      return s;
    }
    s = s->next;
  }
  return 0;
}

/* Cast a pointer (needed for C++ inheritance */
SWIGRUNTIME(void *) 
SWIG_TypeCast(swig_type_info *ty, void *ptr) 
{
  if ((!ty) || (!ty->converter)) return ptr;
  return (*ty->converter)(ptr);
}

/* Search for a swig_type_info structure */
SWIGRUNTIME(void *)
SWIG_TypeQuery(const char *name) {
  swig_type_info *ty = swig_type_list;
  while (ty) {
    if (ty->str && (strcmp(name,ty->str) == 0)) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

#endif

#ifdef __cplusplus
}
#endif



/*
 * $Header$
 * 
 * swigtcl8.swg
 */

#include <tcl.h>
#include <stdlib.h>
#include <stdarg.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef SWIG_NOINCLUDE
SWIGEXPORT(int) SWIG_ConvertPtrFromString(Tcl_Interp *, char *, void **, swig_type_info *);
SWIGEXPORT(int) SWIG_ConvertPtr(Tcl_Interp *, Tcl_Obj *, void **, swig_type_info *);
SWIGEXPORT(void) SWIG_MakePtr(char *, void *, swig_type_info *);
SWIGEXPORT(Tcl_Obj *) SWIG_NewPointerObj(void *, swig_type_info *);
SWIGEXPORT(int) SWIG_GetArgs(Tcl_Interp *, int, Tcl_Obj *CONST [], const char *, ...);
SWIGEXPORT(char *) SWIG_PointerTypeFromString(char *c);
#else

/* Convert a pointer value */
SWIGRUNTIME(int)
SWIG_ConvertPtrFromString(Tcl_Interp *interp, char *c, void **ptr, swig_type_info *ty)
{
  unsigned long p;
  register int d;
  swig_type_info *tc;
  p = 0;
  /* Pointer values must start with leading underscore */
  if (*c != '_') {
    *ptr = (void *) 0;
    if (strcmp(c,"NULL") == 0) return TCL_OK;
    Tcl_SetResult(interp,"Type error. Expected a pointer", TCL_STATIC);
    return TCL_ERROR;
  }
  c++;
  /* Extract hex value from pointer */
  while ((d = *c)) {
    if ((d >= '0') && (d <= '9'))
      p = (p << 4) + (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      p = (p << 4) + (d - ('a'-10));
    else
      break; 
    c++;
  }
  *ptr = (void *) p;
  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) {
      Tcl_SetResult(interp,"Type error. Expected ", TCL_STATIC);
      Tcl_AppendElement(interp, ty->name);
      return TCL_ERROR;
    }
    *ptr = SWIG_TypeCast(tc,(void *)p);
  }
  return TCL_OK;
}


/* Convert a pointer value */
SWIGRUNTIME(int)
SWIG_ConvertPtr(Tcl_Interp *interp, Tcl_Obj *oc, void **ptr, swig_type_info *ty)
{
  return SWIG_ConvertPtrFromString(interp, Tcl_GetStringFromObj(oc,NULL), ptr, ty);
}


/* Convert a pointer value */
SWIGRUNTIME(char *)
SWIG_PointerTypeFromString(char *c) {
  char d;
  /* Pointer values must start with leading underscore */
  if (*c != '_') {
    return 0;
  }
  c++;
  /* Extract hex value from pointer */
  while (d = *c) {
    if (!(((d >= '0') && (d <= '9')) || ((d >= 'a') && (d <= 'f')))) break;
    c++;
  }
  return c;
}

/* Take a pointer and convert it to a string */
SWIGRUNTIME(void) 
SWIG_MakePtr(char *c, void *ptr, swig_type_info *ty) {
  static char hex[17] = "0123456789abcdef";
  unsigned long p, s;
  char result[24], *r; 
  r = result;
  p = (unsigned long) ptr;
  if (p > 0) {
    while (p > 0) {
      s = p & 0xf;
      *(r++) = hex[s];
      p = p >> 4;
    }
    *r = '_';
    while (r >= result)
      *(c++) = *(r--);
    strcpy (c, ty->name);
  } else {
    strcpy (c, "NULL");
  }
}

/* Create a new pointer object */
SWIGRUNTIME(Tcl_Obj *)
SWIG_NewPointerObj(void *ptr, swig_type_info *type) {
  char result[256];
  Tcl_Obj *robj;
  SWIG_MakePtr(result,ptr,type);
  robj = Tcl_NewStringObj(result,-1);
  return robj;
}

/* Get arguments */
SWIGRUNTIME(int)
SWIG_GetArgs(Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[], const char *fmt, ...)
{
  int        argno = 0, opt = 0, tempi;
  int        us = 0;
  double     tempd;
  const char *c;
  va_list    ap;
  void      *vptr;
  swig_type_info *ty;

  va_start(ap,fmt);
  for (c = fmt; (*c && (*c != ':')); c++,argno++) {
    if (*c == '|') {
      opt = 1;
      c++;
    }
    if (argno >= (objc-1)) {
      if (!opt) {
	Tcl_SetResult(interp,"Wrong # args. ", TCL_STATIC);
	goto argerror;
      } else {
	va_end(ap);
	return TCL_OK;
      }
    }
    vptr = va_arg(ap,void *);
    if (vptr) {
      us = 0;
      if (*c == 'u') {
	us = 1;
	c++;
      }
      switch(*c) {
      case 'i':
      case 'l':
      case 'h':
      case 'b':
	if (Tcl_GetIntFromObj(interp,objv[argno+1],&tempi) != TCL_OK) goto argerror;
	if (*c == 'i') *((int *)vptr) = tempi;
	else if (*c == 'l') *((long *)vptr) = tempi;
	else if (*c == 'h') *((short*)vptr) = tempi;
	else if (*c == 'b') *((unsigned char *)vptr) = tempi;
	break;
      case 'f':
      case 'd':
	if (Tcl_GetDoubleFromObj(interp,objv[argno+1],&tempd) != TCL_OK) goto argerror;
	if (*c == 'f') *((float *) vptr) = tempd;
	else if (*c == 'd') *((double*) vptr) = tempd;
	break;
      case 's':
	if (*(c+1) == '#') {
	  int *vlptr = (int *) va_arg(ap, void *);
	  *((char **) vptr) = Tcl_GetStringFromObj(objv[argno+1], vlptr);
	  c++;
	} else {
	  *((char **)vptr) = Tcl_GetStringFromObj(objv[argno+1],NULL);
	}
	break;
      case 'c':
	*((char *)vptr) = *(Tcl_GetStringFromObj(objv[argno+1],NULL));
	break;
      case 'p':
	ty = (swig_type_info *) va_arg(ap, void *);
	if (SWIG_ConvertPtr(interp, objv[argno+1], (void **) vptr, ty) == TCL_ERROR) goto argerror;
	break;
      case 'o':
	*((Tcl_Obj **)vptr) = objv[argno+1];
	break;
      default:
	break;
      }
    }
  }
  if ((objc-1) > argno) {
    Tcl_SetResult(interp,"Wrong # args.", TCL_STATIC);
    goto argerror;
  }
  va_end(ap);
  return TCL_OK;
  
 argerror:
  {
    char temp[32];
    sprintf(temp,"%d", argno);
    Tcl_AppendResult(interp,strchr(fmt,':'), " argument ", temp, NULL);
    va_end(ap);
    return TCL_ERROR;
  }
}

#endif

/* Structure for command table */
typedef struct {
  const char *name;
  int       (*wrapper)(ClientData, Tcl_Interp *, int, Tcl_Obj *CONST []);
  ClientData  clientdata;
} swig_command_info;

/* Structure for variable linking table */
typedef struct {
  const char *name;
  void *addr;
  char * (*get)(ClientData, Tcl_Interp *, char *, char *, int);
  char * (*set)(ClientData, Tcl_Interp *, char *, char *, int);
} swig_var_info;


#ifdef __cplusplus
}
#endif


/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_SWFMovieClip swig_types[0] 
#define  SWIGTYPE_SWFMovie swig_types[1] 
#define  SWIGTYPE_SWFGradient swig_types[2] 
#define  SWIGTYPE_SWFDisplayItem swig_types[3] 
#define  SWIGTYPE_SWFShape swig_types[4] 
#define  SWIGTYPE_SWFBitmap swig_types[5] 
#define  SWIGTYPE_p_SWFByteOutputMethod swig_types[6] 
#define  SWIGTYPE_p_SWFCXform swig_types[7] 
#define  SWIGTYPE_SWFText swig_types[8] 
#define  SWIGTYPE_SWFFont swig_types[9] 
#define  SWIGTYPE_p_void swig_types[10] 
#define  SWIGTYPE_SWFMorph swig_types[11] 
#define  SWIGTYPE_SWFButton swig_types[12] 
#define  SWIGTYPE_SWFBlock swig_types[13] 
#define  SWIGTYPE_SWFTextField swig_types[14] 
#define  SWIGTYPE_p_FILE swig_types[15] 
#define  SWIGTYPE_p_SWFRect swig_types[16] 
#define  SWIGTYPE_SWFFill swig_types[17] 
#define  SWIGTYPE_SWFMatrix swig_types[18] 
#define  SWIGTYPE_SWFSound swig_types[19] 
#define  SWIGTYPE_SWFAction swig_types[20] 
#define  SWIGTYPE_SWFCharacter swig_types[21] 
#define  SWIGTYPE_p_int swig_types[22] 
#define  SWIGTYPE_SWFBrowserFont swig_types[23] 
static swig_type_info *swig_types[25];

/* -------- TYPES TABLE (END) -------- */

#define SWIG_init    Mingc_Init
#define SWIG_name    "mingc"
#define SWIG_prefix  ""
#define SWIG_namespace ""

#ifdef __cplusplus
extern "C" {
#endif
#ifdef MAC_TCL
#pragma export on
#endif
SWIGEXPORT(int) Mingc_Init(Tcl_Interp *);
#ifdef MAC_TCL
#pragma export off
#endif
#ifdef __cplusplus
}
#endif

  #include "ming.h"

void my_stdout_write(unsigned char c, void* data) {
  write(1, &c, 1);
}

int SWFMovie_simpleOutput(SWFMovie movie) {
   return SWFMovie_output(movie, my_stdout_write, 0);
}

static int  _wrap_const_SWFFILL_SOLID = 0x00;
static int  _wrap_const_SWFFILL_GRADIENT = 0x10;
static int  _wrap_const_SWFFILL_LINEAR_GRADIENT = 0x10;
static int  _wrap_const_SWFFILL_RADIAL_GRADIENT = 0x12;
static int  _wrap_const_SWFFILL_BITMAP = 0x40;
static int  _wrap_const_SWFFILL_TILED_BITMAP = 0x40;
static int  _wrap_const_SWFFILL_CLIPPED_BITMAP = 0x41;
static int  _wrap_const_SWFTEXTFIELD_ONMASK = 0x2085;
static int  _wrap_const_SWFTEXTFIELD_OFFMASK = 0x38FF;
static int  _wrap_const_SWFTEXTFIELD_HASLENGTH = (1<<1);
static int  _wrap_const_SWFTEXTFIELD_NOEDIT = (1<<3);
static int  _wrap_const_SWFTEXTFIELD_PASSWORD = (1<<4);
static int  _wrap_const_SWFTEXTFIELD_MULTILINE = (1<<5);
static int  _wrap_const_SWFTEXTFIELD_WORDWRAP = (1<<6);
static int  _wrap_const_SWFTEXTFIELD_DRAWBOX = (1<<11);
static int  _wrap_const_SWFTEXTFIELD_NOSELECT = (1<<12);
static int  _wrap_const_SWFTEXTFIELD_ALIGN_LEFT = SWFTEXTFIELD_ALIGN_LEFT;
static int  _wrap_const_SWFTEXTFIELD_ALIGN_RIGHT = SWFTEXTFIELD_ALIGN_RIGHT;
static int  _wrap_const_SWFTEXTFIELD_ALIGN_CENTER = SWFTEXTFIELD_ALIGN_CENTER;
static int  _wrap_const_SWFTEXTFIELD_ALIGN_JUSTIFY = SWFTEXTFIELD_ALIGN_JUSTIFY;
static int  _wrap_const_SWF_SOUND_COMPRESSION = 0xf0;
static int  _wrap_const_SWF_SOUND_NOT_COMPRESSED = (0<<4);
static int  _wrap_const_SWF_SOUND_ADPCM_COMPRESSED = (1<<4);
static int  _wrap_const_SWF_SOUND_RATE = 0x0c;
static int  _wrap_const_SWF_SOUND_5KHZ = (0<<2);
static int  _wrap_const_SWF_SOUND_11KHZ = (1<<2);
static int  _wrap_const_SWF_SOUND_22KHZ = (2<<2);
static int  _wrap_const_SWF_SOUND_44KHZ = (3<<2);
static int  _wrap_const_SWF_SOUND_BITS = 0x02;
static int  _wrap_const_SWF_SOUND_8BIT = (0<<1);
static int  _wrap_const_SWF_SOUND_16BIT = (1<<1);
static int  _wrap_const_SWF_SOUND_CHANNELS = 0x01;
static int  _wrap_const_SWF_SOUND_MONO = (0<<0);
static int  _wrap_const_SWF_SOUND_STEREO = (1<<0);
static int  _wrap_const_SWFBUTTON_HIT = (1<<3);
static int  _wrap_const_SWFBUTTON_DOWN = (1<<2);
static int  _wrap_const_SWFBUTTON_OVER = (1<<1);
static int  _wrap_const_SWFBUTTON_UP = (1<<0);

  int swfButton_keypress(char c)
  {
    return SWFBUTTON_KEYPRESS(c);
  }
static int  _wrap_const_SWFBUTTON_OVERDOWNTOIDLE = (1<<8);
static int  _wrap_const_SWFBUTTON_IDLETOOVERDOWN = (1<<7);
static int  _wrap_const_SWFBUTTON_OUTDOWNTOIDLE = (1<<6);
static int  _wrap_const_SWFBUTTON_OUTDOWNTOOVERDOWN = (1<<5);
static int  _wrap_const_SWFBUTTON_OVERDOWNTOOUTDOWN = (1<<4);
static int  _wrap_const_SWFBUTTON_OVERDOWNTOOVERUP = (1<<3);
static int  _wrap_const_SWFBUTTON_OVERUPTOOVERDOWN = (1<<2);
static int  _wrap_const_SWFBUTTON_OVERUPTOIDLE = (1<<1);
static int  _wrap_const_SWFBUTTON_IDLETOOVERUP = (1<<0);
static int  _wrap_const_SWFBUTTON_MOUSEUPOUTSIDE = (1<<6);
static int  _wrap_const_SWFBUTTON_DRAGOVER = ((1<<5)|(1<<7));
static int  _wrap_const_SWFBUTTON_DRAGOUT = ((1<<4)|(1<<8));
static int  _wrap_const_SWFBUTTON_MOUSEUP = (1<<3);
static int  _wrap_const_SWFBUTTON_MOUSEDOWN = (1<<2);
static int  _wrap_const_SWFBUTTON_MOUSEOUT = (1<<1);
static int  _wrap_const_SWFBUTTON_MOUSEOVER = (1<<0);
static int
_wrap_Ming_init(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    int result ;
    
    if (SWIG_GetArgs(interp, objc, objv,":Ming_init ") == TCL_ERROR) return TCL_ERROR;
    result = (int )Ming_init();
    Tcl_SetObjResult(interp,Tcl_NewIntObj((long) result));
    return TCL_OK;
}

static int
_wrap_destroySWFMovie(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFMovie arg0 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:destroySWFMovie movie ",&arg0, SWIGTYPE_SWFMovie) == TCL_ERROR) return TCL_ERROR;
    destroySWFMovie(arg0);
    return TCL_OK;
}

static int
_wrap_newSWFMovie(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFMovie result ;
    
    if (SWIG_GetArgs(interp, objc, objv,":newSWFMovie ") == TCL_ERROR) return TCL_ERROR;
    result = (SWFMovie )newSWFMovie();
    Tcl_SetObjResult(interp,SWIG_NewPointerObj((void *) result,SWIGTYPE_SWFMovie));
    return TCL_OK;
}

static int
_wrap_SWFMovie_setRate(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFMovie arg0 ;
    float arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pf:SWFMovie_setRate movie rate ",&arg0, SWIGTYPE_SWFMovie,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFMovie_setRate(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFMovie_setDimension(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFMovie arg0 ;
    int arg1 ;
    int arg2 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pii:SWFMovie_setDimension movie x y ",&arg0, SWIGTYPE_SWFMovie,&arg1,&arg2) == TCL_ERROR) return TCL_ERROR;
    SWFMovie_setDimension(arg0,arg1,arg2);
    return TCL_OK;
}

static int
_wrap_SWFMovie_setNumberOfFrames(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFMovie arg0 ;
    int arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pi:SWFMovie_setNumberOfFrames movie frames ",&arg0, SWIGTYPE_SWFMovie,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFMovie_setNumberOfFrames(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFMovie_setBackground(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFMovie arg0 ;
    int arg1 ;
    int arg2 ;
    int arg3 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"piii:SWFMovie_setBackground movie r g b ",&arg0, SWIGTYPE_SWFMovie,&arg1,&arg2,&arg3) == TCL_ERROR) return TCL_ERROR;
    SWFMovie_setBackground(arg0,arg1,arg2,arg3);
    return TCL_OK;
}

static int
_wrap_SWFMovie_setSoundStream(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFMovie arg0 ;
    SWFSound arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pp:SWFMovie_setSoundStream movie sound ",&arg0, SWIGTYPE_SWFMovie,&arg1, SWIGTYPE_SWFSound) == TCL_ERROR) return TCL_ERROR;
    SWFMovie_setSoundStream(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFMovie_add(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFMovie arg0 ;
    SWFBlock arg1 ;
    SWFDisplayItem result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pp:SWFMovie_add movie block ",&arg0, SWIGTYPE_SWFMovie,&arg1, SWIGTYPE_SWFBlock) == TCL_ERROR) return TCL_ERROR;
    result = (SWFDisplayItem )SWFMovie_add(arg0,arg1);
    Tcl_SetObjResult(interp,SWIG_NewPointerObj((void *) result,SWIGTYPE_SWFDisplayItem));
    return TCL_OK;
}

static int
_wrap_SWFMovie_remove(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFMovie arg0 ;
    SWFDisplayItem arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pp:SWFMovie_remove movie item ",&arg0, SWIGTYPE_SWFMovie,&arg1, SWIGTYPE_SWFDisplayItem) == TCL_ERROR) return TCL_ERROR;
    SWFMovie_remove(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFMovie_nextFrame(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFMovie arg0 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:SWFMovie_nextFrame movie ",&arg0, SWIGTYPE_SWFMovie) == TCL_ERROR) return TCL_ERROR;
    SWFMovie_nextFrame(arg0);
    return TCL_OK;
}

static int
_wrap_SWFMovie_labelFrame(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFMovie arg0 ;
    char *arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"ps:SWFMovie_labelFrame movie label ",&arg0, SWIGTYPE_SWFMovie,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFMovie_labelFrame(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFMovie_output(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFMovie arg0 ;
    SWFByteOutputMethod *arg1 ;
    void *arg2 ;
    int result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"ppp:SWFMovie_output movie method data ",&arg0, SWIGTYPE_SWFMovie,&arg1, SWIGTYPE_p_SWFByteOutputMethod,&arg2, 0) == TCL_ERROR) return TCL_ERROR;
    result = (int )SWFMovie_output(arg0,*arg1,arg2);
    Tcl_SetObjResult(interp,Tcl_NewIntObj((long) result));
    return TCL_OK;
}

static int
_wrap_SWFMovie_simpleOutput(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFMovie arg0 ;
    int result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:SWFMovie_simpleOutput movie ",&arg0, SWIGTYPE_SWFMovie) == TCL_ERROR) return TCL_ERROR;
    result = (int )SWFMovie_simpleOutput(arg0);
    Tcl_SetObjResult(interp,Tcl_NewIntObj((long) result));
    return TCL_OK;
}

static int
_wrap_SWFMovie_save(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFMovie arg0 ;
    char *arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"ps:SWFMovie_save movie filename ",&arg0, SWIGTYPE_SWFMovie,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFMovie_save(arg0,(char const *)arg1);
    return TCL_OK;
}

static int
_wrap_SWFDisplayItem_rotate(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFDisplayItem arg0 ;
    float arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pf:SWFDisplayItem_rotate item degrees ",&arg0, SWIGTYPE_SWFDisplayItem,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFDisplayItem_rotate(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFDisplayItem_rotateTo(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFDisplayItem arg0 ;
    float arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pf:SWFDisplayItem_rotateTo item degrees ",&arg0, SWIGTYPE_SWFDisplayItem,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFDisplayItem_rotateTo(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFDisplayItem_move(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFDisplayItem arg0 ;
    int arg1 ;
    int arg2 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pii:SWFDisplayItem_move item x y ",&arg0, SWIGTYPE_SWFDisplayItem,&arg1,&arg2) == TCL_ERROR) return TCL_ERROR;
    SWFDisplayItem_move(arg0,arg1,arg2);
    return TCL_OK;
}

static int
_wrap_SWFDisplayItem_moveTo(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFDisplayItem arg0 ;
    int arg1 ;
    int arg2 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pii:SWFDisplayItem_moveTo item x y ",&arg0, SWIGTYPE_SWFDisplayItem,&arg1,&arg2) == TCL_ERROR) return TCL_ERROR;
    SWFDisplayItem_moveTo(arg0,arg1,arg2);
    return TCL_OK;
}

static int
_wrap_SWFDisplayItem_scale(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFDisplayItem arg0 ;
    float arg1 ;
    float arg2 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pff:SWFDisplayItem_scale item xScale yScale ",&arg0, SWIGTYPE_SWFDisplayItem,&arg1,&arg2) == TCL_ERROR) return TCL_ERROR;
    SWFDisplayItem_scale(arg0,arg1,arg2);
    return TCL_OK;
}

static int
_wrap_SWFDisplayItem_scaleTo(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFDisplayItem arg0 ;
    float arg1 ;
    float arg2 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pff:SWFDisplayItem_scaleTo item xScale yScale ",&arg0, SWIGTYPE_SWFDisplayItem,&arg1,&arg2) == TCL_ERROR) return TCL_ERROR;
    SWFDisplayItem_scaleTo(arg0,arg1,arg2);
    return TCL_OK;
}

static int
_wrap_SWFDisplayItem_skewX(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFDisplayItem arg0 ;
    float arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pf:SWFDisplayItem_skewX item x ",&arg0, SWIGTYPE_SWFDisplayItem,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFDisplayItem_skewX(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFDisplayItem_skewXTo(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFDisplayItem arg0 ;
    float arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pf:SWFDisplayItem_skewXTo item x ",&arg0, SWIGTYPE_SWFDisplayItem,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFDisplayItem_skewXTo(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFDisplayItem_skewY(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFDisplayItem arg0 ;
    float arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pf:SWFDisplayItem_skewY item y ",&arg0, SWIGTYPE_SWFDisplayItem,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFDisplayItem_skewY(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFDisplayItem_skewYTo(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFDisplayItem arg0 ;
    float arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pf:SWFDisplayItem_skewYTo item y ",&arg0, SWIGTYPE_SWFDisplayItem,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFDisplayItem_skewYTo(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFDisplayItem_getDepth(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFDisplayItem arg0 ;
    int result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:SWFDisplayItem_getDepth item ",&arg0, SWIGTYPE_SWFDisplayItem) == TCL_ERROR) return TCL_ERROR;
    result = (int )SWFDisplayItem_getDepth(arg0);
    Tcl_SetObjResult(interp,Tcl_NewIntObj((long) result));
    return TCL_OK;
}

static int
_wrap_SWFDisplayItem_setDepth(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFDisplayItem arg0 ;
    int arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pi:SWFDisplayItem_setDepth item depth ",&arg0, SWIGTYPE_SWFDisplayItem,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFDisplayItem_setDepth(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFDisplayItem_remove(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFDisplayItem arg0 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:SWFDisplayItem_remove item ",&arg0, SWIGTYPE_SWFDisplayItem) == TCL_ERROR) return TCL_ERROR;
    SWFDisplayItem_remove(arg0);
    return TCL_OK;
}

static int
_wrap_SWFDisplayItem_setName(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFDisplayItem arg0 ;
    char *arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"ps:SWFDisplayItem_setName item name ",&arg0, SWIGTYPE_SWFDisplayItem,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFDisplayItem_setName(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFDisplayItem_setRatio(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFDisplayItem arg0 ;
    float arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pf:SWFDisplayItem_setRatio item ratio ",&arg0, SWIGTYPE_SWFDisplayItem,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFDisplayItem_setRatio(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFDisplayItem_setCXform(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFDisplayItem arg0 ;
    SWFCXform *arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pp:SWFDisplayItem_setCXform item cXform ",&arg0, SWIGTYPE_SWFDisplayItem,&arg1, SWIGTYPE_p_SWFCXform) == TCL_ERROR) return TCL_ERROR;
    SWFDisplayItem_setCXform(arg0,*arg1);
    return TCL_OK;
}

static int
_wrap_SWFDisplayItem_setColorAdd(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFDisplayItem arg0 ;
    int arg1 ;
    int arg2 ;
    int arg3 ;
    int arg4 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"piiii:SWFDisplayItem_setColorAdd item r g b a ",&arg0, SWIGTYPE_SWFDisplayItem,&arg1,&arg2,&arg3,&arg4) == TCL_ERROR) return TCL_ERROR;
    SWFDisplayItem_setColorAdd(arg0,arg1,arg2,arg3,arg4);
    return TCL_OK;
}

static int
_wrap_SWFDisplayItem_setColorMult(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFDisplayItem arg0 ;
    float arg1 ;
    float arg2 ;
    float arg3 ;
    float arg4 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pffff:SWFDisplayItem_setColorMult item r g b a ",&arg0, SWIGTYPE_SWFDisplayItem,&arg1,&arg2,&arg3,&arg4) == TCL_ERROR) return TCL_ERROR;
    SWFDisplayItem_setColorMult(arg0,arg1,arg2,arg3,arg4);
    return TCL_OK;
}

static int
_wrap_destroySWFFill(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFFill arg0 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:destroySWFFill fill ",&arg0, SWIGTYPE_SWFFill) == TCL_ERROR) return TCL_ERROR;
    destroySWFFill(arg0);
    return TCL_OK;
}

static int
_wrap_SWFFill_skewX(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFFill arg0 ;
    float arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pf:SWFFill_skewX fill x ",&arg0, SWIGTYPE_SWFFill,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFFill_skewX(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFFill_skewXTo(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFFill arg0 ;
    float arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pf:SWFFill_skewXTo fill x ",&arg0, SWIGTYPE_SWFFill,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFFill_skewXTo(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFFill_skewY(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFFill arg0 ;
    float arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pf:SWFFill_skewY fill y ",&arg0, SWIGTYPE_SWFFill,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFFill_skewY(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFFill_skewYTo(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFFill arg0 ;
    float arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pf:SWFFill_skewYTo fill y ",&arg0, SWIGTYPE_SWFFill,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFFill_skewYTo(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFFill_scaleX(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFFill arg0 ;
    float arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pf:SWFFill_scaleX fill x ",&arg0, SWIGTYPE_SWFFill,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFFill_scaleX(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFFill_scaleXTo(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFFill arg0 ;
    float arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pf:SWFFill_scaleXTo fill x ",&arg0, SWIGTYPE_SWFFill,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFFill_scaleXTo(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFFill_scaleY(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFFill arg0 ;
    float arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pf:SWFFill_scaleY fill y ",&arg0, SWIGTYPE_SWFFill,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFFill_scaleY(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFFill_scaleYTo(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFFill arg0 ;
    float arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pf:SWFFill_scaleYTo fill y ",&arg0, SWIGTYPE_SWFFill,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFFill_scaleYTo(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFFill_scaleXY(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFFill arg0 ;
    float arg1 ;
    float arg2 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pff:SWFFill_scaleXY fill x y ",&arg0, SWIGTYPE_SWFFill,&arg1,&arg2) == TCL_ERROR) return TCL_ERROR;
    SWFFill_scaleXY(arg0,arg1,arg2);
    return TCL_OK;
}

static int
_wrap_SWFFill_scaleXYTo(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFFill arg0 ;
    float arg1 ;
    float arg2 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pff:SWFFill_scaleXYTo fill x y ",&arg0, SWIGTYPE_SWFFill,&arg1,&arg2) == TCL_ERROR) return TCL_ERROR;
    SWFFill_scaleXYTo(arg0,arg1,arg2);
    return TCL_OK;
}

static int
_wrap_SWFFill_rotate(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFFill arg0 ;
    float arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pf:SWFFill_rotate fill degrees ",&arg0, SWIGTYPE_SWFFill,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFFill_rotate(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFFill_rotateTo(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFFill arg0 ;
    float arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pf:SWFFill_rotateTo fill degrees ",&arg0, SWIGTYPE_SWFFill,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFFill_rotateTo(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFFill_move(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFFill arg0 ;
    int arg1 ;
    int arg2 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pii:SWFFill_move fill x y ",&arg0, SWIGTYPE_SWFFill,&arg1,&arg2) == TCL_ERROR) return TCL_ERROR;
    SWFFill_move(arg0,arg1,arg2);
    return TCL_OK;
}

static int
_wrap_SWFFill_moveTo(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFFill arg0 ;
    int arg1 ;
    int arg2 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pii:SWFFill_moveTo fill x y ",&arg0, SWIGTYPE_SWFFill,&arg1,&arg2) == TCL_ERROR) return TCL_ERROR;
    SWFFill_moveTo(arg0,arg1,arg2);
    return TCL_OK;
}

static int
_wrap_SWFShape_addSolidFill(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFShape arg0 ;
    byte arg1 ;
    byte arg2 ;
    byte arg3 ;
    byte arg4 ;
    SWFFill result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pbbbb:SWFShape_addSolidFill shape r g b a ",&arg0, SWIGTYPE_SWFShape,&arg1,&arg2,&arg3,&arg4) == TCL_ERROR) return TCL_ERROR;
    result = (SWFFill )SWFShape_addSolidFill(arg0,arg1,arg2,arg3,arg4);
    Tcl_SetObjResult(interp,SWIG_NewPointerObj((void *) result,SWIGTYPE_SWFFill));
    return TCL_OK;
}

static int
_wrap_SWFShape_addGradientFill(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFShape arg0 ;
    SWFGradient arg1 ;
    byte arg2 ;
    SWFFill result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"ppb:SWFShape_addGradientFill shape gradient flags ",&arg0, SWIGTYPE_SWFShape,&arg1, SWIGTYPE_SWFGradient,&arg2) == TCL_ERROR) return TCL_ERROR;
    result = (SWFFill )SWFShape_addGradientFill(arg0,arg1,arg2);
    Tcl_SetObjResult(interp,SWIG_NewPointerObj((void *) result,SWIGTYPE_SWFFill));
    return TCL_OK;
}

static int
_wrap_SWFShape_addBitmapFill(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFShape arg0 ;
    SWFBitmap arg1 ;
    byte arg2 ;
    SWFFill result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"ppb:SWFShape_addBitmapFill shape bitmap flags ",&arg0, SWIGTYPE_SWFShape,&arg1, SWIGTYPE_SWFBitmap,&arg2) == TCL_ERROR) return TCL_ERROR;
    result = (SWFFill )SWFShape_addBitmapFill(arg0,arg1,arg2);
    Tcl_SetObjResult(interp,SWIG_NewPointerObj((void *) result,SWIGTYPE_SWFFill));
    return TCL_OK;
}

static int
_wrap_SWFShape_setLeftFill(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFShape arg0 ;
    SWFFill arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pp:SWFShape_setLeftFill shape fill ",&arg0, SWIGTYPE_SWFShape,&arg1, SWIGTYPE_SWFFill) == TCL_ERROR) return TCL_ERROR;
    SWFShape_setLeftFill(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFShape_setRightFill(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFShape arg0 ;
    SWFFill arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pp:SWFShape_setRightFill shape fill ",&arg0, SWIGTYPE_SWFShape,&arg1, SWIGTYPE_SWFFill) == TCL_ERROR) return TCL_ERROR;
    SWFShape_setRightFill(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFShape_setLine(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFShape arg0 ;
    unsigned short arg1 ;
    byte arg2 ;
    byte arg3 ;
    byte arg4 ;
    byte arg5 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"phbbbb:SWFShape_setLine shape width r g b a ",&arg0, SWIGTYPE_SWFShape,&arg1,&arg2,&arg3,&arg4,&arg5) == TCL_ERROR) return TCL_ERROR;
    SWFShape_setLine(arg0,arg1,arg2,arg3,arg4,arg5);
    return TCL_OK;
}

static int
_wrap_SWFShape_drawArc(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFShape arg0 ;
    int arg1 ;
    float arg2 ;
    float arg3 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"piff:SWFShape_drawArc shape r startAngle endAngle ",&arg0, SWIGTYPE_SWFShape,&arg1,&arg2,&arg3) == TCL_ERROR) return TCL_ERROR;
    SWFShape_drawArc(arg0,arg1,arg2,arg3);
    return TCL_OK;
}

static int
_wrap_SWFShape_drawCircle(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFShape arg0 ;
    int arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pi:SWFShape_drawCircle shape r ",&arg0, SWIGTYPE_SWFShape,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFShape_drawCircle(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFShape_drawFontGlyph(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFShape arg0 ;
    SWFFont arg1 ;
    int arg2 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"ppi:SWFShape_drawFontGlyph shape font c ",&arg0, SWIGTYPE_SWFShape,&arg1, SWIGTYPE_SWFFont,&arg2) == TCL_ERROR) return TCL_ERROR;
    SWFShape_drawFontGlyph(arg0,arg1,arg2);
    return TCL_OK;
}

static int
_wrap_newSWFMovieClip(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFMovieClip result ;
    
    if (SWIG_GetArgs(interp, objc, objv,":newSWFMovieClip ") == TCL_ERROR) return TCL_ERROR;
    result = (SWFMovieClip )newSWFMovieClip();
    Tcl_SetObjResult(interp,SWIG_NewPointerObj((void *) result,SWIGTYPE_SWFMovieClip));
    return TCL_OK;
}

static int
_wrap_destroySWFMovieClip(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFMovieClip arg0 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:destroySWFMovieClip clip ",&arg0, SWIGTYPE_SWFMovieClip) == TCL_ERROR) return TCL_ERROR;
    destroySWFMovieClip(arg0);
    return TCL_OK;
}

static int
_wrap_SWFMovieClip_setNumberOfFrames(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFMovieClip arg0 ;
    int arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pi:SWFMovieClip_setNumberOfFrames clip frames ",&arg0, SWIGTYPE_SWFMovieClip,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFMovieClip_setNumberOfFrames(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFMovieClip_add(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFMovieClip arg0 ;
    SWFBlock arg1 ;
    SWFDisplayItem result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pp:SWFMovieClip_add clip block ",&arg0, SWIGTYPE_SWFMovieClip,&arg1, SWIGTYPE_SWFBlock) == TCL_ERROR) return TCL_ERROR;
    result = (SWFDisplayItem )SWFMovieClip_add(arg0,arg1);
    Tcl_SetObjResult(interp,SWIG_NewPointerObj((void *) result,SWIGTYPE_SWFDisplayItem));
    return TCL_OK;
}

static int
_wrap_SWFMovieClip_remove(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFMovieClip arg0 ;
    SWFDisplayItem arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pp:SWFMovieClip_remove clip item ",&arg0, SWIGTYPE_SWFMovieClip,&arg1, SWIGTYPE_SWFDisplayItem) == TCL_ERROR) return TCL_ERROR;
    SWFMovieClip_remove(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFMovieClip_nextFrame(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFMovieClip arg0 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:SWFMovieClip_nextFrame clip ",&arg0, SWIGTYPE_SWFMovieClip) == TCL_ERROR) return TCL_ERROR;
    SWFMovieClip_nextFrame(arg0);
    return TCL_OK;
}

static int
_wrap_SWFMovieClip_labelFrame(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFMovieClip arg0 ;
    char *arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"ps:SWFMovieClip_labelFrame clip label ",&arg0, SWIGTYPE_SWFMovieClip,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFMovieClip_labelFrame(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_newSWFRect(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    int arg0 ;
    int arg1 ;
    int arg2 ;
    int arg3 ;
    SWFRect *result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"iiii:newSWFRect minX maxX minY maxY ",&arg0,&arg1,&arg2,&arg3) == TCL_ERROR) return TCL_ERROR;
    result = new SWFRect (newSWFRect(arg0,arg1,arg2,arg3));Tcl_SetObjResult(interp,SWIG_NewPointerObj((void *) result,SWIGTYPE_p_SWFRect));
    return TCL_OK;
}

static int
_wrap_destroySWFRect(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFRect *arg0 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:destroySWFRect rect ",&arg0, SWIGTYPE_p_SWFRect) == TCL_ERROR) return TCL_ERROR;
    destroySWFRect(*arg0);
    return TCL_OK;
}

static int
_wrap_SWFRect_getWidth(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFRect *arg0 ;
    int result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:SWFRect_getWidth r ",&arg0, SWIGTYPE_p_SWFRect) == TCL_ERROR) return TCL_ERROR;
    result = (int )SWFRect_getWidth(*arg0);
    Tcl_SetObjResult(interp,Tcl_NewIntObj((long) result));
    return TCL_OK;
}

static int
_wrap_SWFRect_getHeight(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFRect *arg0 ;
    int result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:SWFRect_getHeight r ",&arg0, SWIGTYPE_p_SWFRect) == TCL_ERROR) return TCL_ERROR;
    result = (int )SWFRect_getHeight(*arg0);
    Tcl_SetObjResult(interp,Tcl_NewIntObj((long) result));
    return TCL_OK;
}

static int
_wrap_SWFCharacter_getBounds(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFCharacter arg0 ;
    SWFRect *result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:SWFCharacter_getBounds character ",&arg0, SWIGTYPE_SWFCharacter) == TCL_ERROR) return TCL_ERROR;
    result = new SWFRect (SWFCharacter_getBounds(arg0));Tcl_SetObjResult(interp,SWIG_NewPointerObj((void *) result,SWIGTYPE_p_SWFRect));
    return TCL_OK;
}

static int
_wrap_SWFBlock_isCharacter(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFBlock arg0 ;
    byte result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:SWFBlock_isCharacter block ",&arg0, SWIGTYPE_SWFBlock) == TCL_ERROR) return TCL_ERROR;
    result = (byte )SWFBlock_isCharacter(arg0);
    Tcl_SetObjResult(interp,Tcl_NewIntObj((long) result));
    return TCL_OK;
}

static int
_wrap_destroySWFBitmap(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFBitmap arg0 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:destroySWFBitmap b ",&arg0, SWIGTYPE_SWFBitmap) == TCL_ERROR) return TCL_ERROR;
    destroySWFBitmap(arg0);
    return TCL_OK;
}

static int
_wrap_SWFBitmap_getWidth(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFBitmap arg0 ;
    int result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:SWFBitmap_getWidth b ",&arg0, SWIGTYPE_SWFBitmap) == TCL_ERROR) return TCL_ERROR;
    result = (int )SWFBitmap_getWidth(arg0);
    Tcl_SetObjResult(interp,Tcl_NewIntObj((long) result));
    return TCL_OK;
}

static int
_wrap_SWFBitmap_getHeight(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFBitmap arg0 ;
    int result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:SWFBitmap_getHeight b ",&arg0, SWIGTYPE_SWFBitmap) == TCL_ERROR) return TCL_ERROR;
    result = (int )SWFBitmap_getHeight(arg0);
    Tcl_SetObjResult(interp,Tcl_NewIntObj((long) result));
    return TCL_OK;
}

static int
_wrap_newSWFDBLBitmap(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    FILE *arg0 ;
    SWFBitmap result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:newSWFDBLBitmap f ",&arg0, SWIGTYPE_p_FILE) == TCL_ERROR) return TCL_ERROR;
    result = (SWFBitmap )newSWFDBLBitmap(arg0);
    Tcl_SetObjResult(interp,SWIG_NewPointerObj((void *) result,SWIGTYPE_SWFBitmap));
    return TCL_OK;
}

static int
_wrap_newSWFJpegBitmap(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    FILE *arg0 ;
    SWFBitmap result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:newSWFJpegBitmap f ",&arg0, SWIGTYPE_p_FILE) == TCL_ERROR) return TCL_ERROR;
    result = (SWFBitmap )newSWFJpegBitmap(arg0);
    Tcl_SetObjResult(interp,SWIG_NewPointerObj((void *) result,SWIGTYPE_SWFBitmap));
    return TCL_OK;
}

static int
_wrap_newSWFJpegWithAlpha(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    FILE *arg0 ;
    FILE *arg1 ;
    SWFBitmap result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pp:newSWFJpegWithAlpha f alpha ",&arg0, SWIGTYPE_p_FILE,&arg1, SWIGTYPE_p_FILE) == TCL_ERROR) return TCL_ERROR;
    result = (SWFBitmap )newSWFJpegWithAlpha(arg0,arg1);
    Tcl_SetObjResult(interp,SWIG_NewPointerObj((void *) result,SWIGTYPE_SWFBitmap));
    return TCL_OK;
}

static int
_wrap_newSWFGradient(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFGradient result ;
    
    if (SWIG_GetArgs(interp, objc, objv,":newSWFGradient ") == TCL_ERROR) return TCL_ERROR;
    result = (SWFGradient )newSWFGradient();
    Tcl_SetObjResult(interp,SWIG_NewPointerObj((void *) result,SWIGTYPE_SWFGradient));
    return TCL_OK;
}

static int
_wrap_destroySWFGradient(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFGradient arg0 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:destroySWFGradient gradient ",&arg0, SWIGTYPE_SWFGradient) == TCL_ERROR) return TCL_ERROR;
    destroySWFGradient(arg0);
    return TCL_OK;
}

static int
_wrap_SWFGradient_addEntry(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFGradient arg0 ;
    float arg1 ;
    byte arg2 ;
    byte arg3 ;
    byte arg4 ;
    byte arg5 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pfbbbb:SWFGradient_addEntry gradient ratio r g b a ",&arg0, SWIGTYPE_SWFGradient,&arg1,&arg2,&arg3,&arg4,&arg5) == TCL_ERROR) return TCL_ERROR;
    SWFGradient_addEntry(arg0,arg1,arg2,arg3,arg4,arg5);
    return TCL_OK;
}

static int
_wrap_newSWFMatrix(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    int arg0 ;
    int arg1 ;
    int arg2 ;
    int arg3 ;
    int arg4 ;
    int arg5 ;
    SWFMatrix result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"iiiiii:newSWFMatrix a b c d x y ",&arg0,&arg1,&arg2,&arg3,&arg4,&arg5) == TCL_ERROR) return TCL_ERROR;
    result = (SWFMatrix )newSWFMatrix(arg0,arg1,arg2,arg3,arg4,arg5);
    Tcl_SetObjResult(interp,SWIG_NewPointerObj((void *) result,SWIGTYPE_SWFMatrix));
    return TCL_OK;
}

static int
_wrap_destroySWFMatrix(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFMatrix arg0 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:destroySWFMatrix matrix ",&arg0, SWIGTYPE_SWFMatrix) == TCL_ERROR) return TCL_ERROR;
    destroySWFMatrix(arg0);
    return TCL_OK;
}

static int
_wrap_SWFMatrix_set(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFMatrix arg0 ;
    float arg1 ;
    float arg2 ;
    float arg3 ;
    float arg4 ;
    int arg5 ;
    int arg6 ;
    SWFMatrix result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pffffii:SWFMatrix_set m a b c d x y ",&arg0, SWIGTYPE_SWFMatrix,&arg1,&arg2,&arg3,&arg4,&arg5,&arg6) == TCL_ERROR) return TCL_ERROR;
    result = (SWFMatrix )SWFMatrix_set(arg0,arg1,arg2,arg3,arg4,arg5,arg6);
    Tcl_SetObjResult(interp,SWIG_NewPointerObj((void *) result,SWIGTYPE_SWFMatrix));
    return TCL_OK;
}

static char *swig_int_get(ClientData clientData, Tcl_Interp *interp, char *name1, char *name2, int flags) {
    int *addr ;
    Tcl_Obj *value;
    
    addr = (int *) clientData;
    value = Tcl_NewIntObj((int) *addr);
    Tcl_SetVar2(interp,name1,name2,Tcl_GetStringFromObj(value,NULL), flags);
    Tcl_DecrRefCount(value);
    return NULL;
}


static char *swig_int_set(ClientData clientData, Tcl_Interp *interp, char *name1, char *name2, int flags) {
    int *addr ;
    char *value;
    
    addr = (int *) clientData;
    value = Tcl_GetVar2(interp, name1, name2, flags);
    if (!value) return NULL;
    *(addr) = (int ) atol(value);
    return NULL;
}


static char *swig_readonly(ClientData clientData, Tcl_Interp *interp, char *name1, char *name2, int flags) {
    return "Variable is read-only";
}


static int
_wrap_newSWFShape(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFShape result ;
    
    if (SWIG_GetArgs(interp, objc, objv,":newSWFShape ") == TCL_ERROR) return TCL_ERROR;
    result = (SWFShape )newSWFShape();
    Tcl_SetObjResult(interp,SWIG_NewPointerObj((void *) result,SWIGTYPE_SWFShape));
    return TCL_OK;
}

static int
_wrap_destroySWFShape(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFShape arg0 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:destroySWFShape shape ",&arg0, SWIGTYPE_SWFShape) == TCL_ERROR) return TCL_ERROR;
    destroySWFShape(arg0);
    return TCL_OK;
}

static int
_wrap_SWFShape_moveTo(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFShape arg0 ;
    int arg1 ;
    int arg2 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pii:SWFShape_moveTo shape x y ",&arg0, SWIGTYPE_SWFShape,&arg1,&arg2) == TCL_ERROR) return TCL_ERROR;
    SWFShape_moveTo(arg0,arg1,arg2);
    return TCL_OK;
}

static int
_wrap_SWFShape_moveToRelative(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFShape arg0 ;
    int arg1 ;
    int arg2 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pii:SWFShape_moveToRelative shape x y ",&arg0, SWIGTYPE_SWFShape,&arg1,&arg2) == TCL_ERROR) return TCL_ERROR;
    SWFShape_moveToRelative(arg0,arg1,arg2);
    return TCL_OK;
}

static int
_wrap_SWFShape_lineTo(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFShape arg0 ;
    int arg1 ;
    int arg2 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pii:SWFShape_lineTo shape x y ",&arg0, SWIGTYPE_SWFShape,&arg1,&arg2) == TCL_ERROR) return TCL_ERROR;
    SWFShape_lineTo(arg0,arg1,arg2);
    return TCL_OK;
}

static int
_wrap_SWFShape_lineToRelative(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFShape arg0 ;
    int arg1 ;
    int arg2 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pii:SWFShape_lineToRelative shape dx dy ",&arg0, SWIGTYPE_SWFShape,&arg1,&arg2) == TCL_ERROR) return TCL_ERROR;
    SWFShape_lineToRelative(arg0,arg1,arg2);
    return TCL_OK;
}

static int
_wrap_SWFShape_curveTo(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFShape arg0 ;
    int arg1 ;
    int arg2 ;
    int arg3 ;
    int arg4 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"piiii:SWFShape_curveTo shape controlx controly anchorx anchory ",&arg0, SWIGTYPE_SWFShape,&arg1,&arg2,&arg3,&arg4) == TCL_ERROR) return TCL_ERROR;
    SWFShape_curveTo(arg0,arg1,arg2,arg3,arg4);
    return TCL_OK;
}

static int
_wrap_SWFShape_curveToRelative(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFShape arg0 ;
    int arg1 ;
    int arg2 ;
    int arg3 ;
    int arg4 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"piiii:SWFShape_curveToRelative shape controldx controldy anchordx anchordy ",&arg0, SWIGTYPE_SWFShape,&arg1,&arg2,&arg3,&arg4) == TCL_ERROR) return TCL_ERROR;
    SWFShape_curveToRelative(arg0,arg1,arg2,arg3,arg4);
    return TCL_OK;
}

static int
_wrap_SWFShape_end(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFShape arg0 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:SWFShape_end shape ",&arg0, SWIGTYPE_SWFShape) == TCL_ERROR) return TCL_ERROR;
    SWFShape_end(arg0);
    return TCL_OK;
}

static int
_wrap_newSWFMorphShape(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFMorph result ;
    
    if (SWIG_GetArgs(interp, objc, objv,":newSWFMorphShape ") == TCL_ERROR) return TCL_ERROR;
    result = (SWFMorph )newSWFMorphShape();
    Tcl_SetObjResult(interp,SWIG_NewPointerObj((void *) result,SWIGTYPE_SWFMorph));
    return TCL_OK;
}

static int
_wrap_destroySWFMorph(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFMorph arg0 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:destroySWFMorph morph ",&arg0, SWIGTYPE_SWFMorph) == TCL_ERROR) return TCL_ERROR;
    destroySWFMorph(arg0);
    return TCL_OK;
}

static int
_wrap_SWFMorph_getShape1(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFMorph arg0 ;
    SWFShape result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:SWFMorph_getShape1 morph ",&arg0, SWIGTYPE_SWFMorph) == TCL_ERROR) return TCL_ERROR;
    result = (SWFShape )SWFMorph_getShape1(arg0);
    Tcl_SetObjResult(interp,SWIG_NewPointerObj((void *) result,SWIGTYPE_SWFShape));
    return TCL_OK;
}

static int
_wrap_SWFMorph_getShape2(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFMorph arg0 ;
    SWFShape result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:SWFMorph_getShape2 morph ",&arg0, SWIGTYPE_SWFMorph) == TCL_ERROR) return TCL_ERROR;
    result = (SWFShape )SWFMorph_getShape2(arg0);
    Tcl_SetObjResult(interp,SWIG_NewPointerObj((void *) result,SWIGTYPE_SWFShape));
    return TCL_OK;
}

static int
_wrap_newSWFFont(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFFont result ;
    
    if (SWIG_GetArgs(interp, objc, objv,":newSWFFont ") == TCL_ERROR) return TCL_ERROR;
    result = (SWFFont )newSWFFont();
    Tcl_SetObjResult(interp,SWIG_NewPointerObj((void *) result,SWIGTYPE_SWFFont));
    return TCL_OK;
}

static int
_wrap_destroySWFFont(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFFont arg0 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:destroySWFFont font ",&arg0, SWIGTYPE_SWFFont) == TCL_ERROR) return TCL_ERROR;
    destroySWFFont(arg0);
    return TCL_OK;
}

static int
_wrap_loadSWFFontFromFile(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    FILE *arg0 ;
    SWFFont result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:loadSWFFontFromFile file ",&arg0, SWIGTYPE_p_FILE) == TCL_ERROR) return TCL_ERROR;
    result = (SWFFont )loadSWFFontFromFile(arg0);
    Tcl_SetObjResult(interp,SWIG_NewPointerObj((void *) result,SWIGTYPE_SWFFont));
    return TCL_OK;
}

static int
_wrap_SWFFont_getStringWidth(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFFont arg0 ;
    char *arg1 ;
    int result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"ps:SWFFont_getStringWidth font string ",&arg0, SWIGTYPE_SWFFont,&arg1) == TCL_ERROR) return TCL_ERROR;
    result = (int )SWFFont_getStringWidth(arg0,arg1);
    Tcl_SetObjResult(interp,Tcl_NewIntObj((long) result));
    return TCL_OK;
}

static int
_wrap_SWFFont_getAscent(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFFont arg0 ;
    short result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:SWFFont_getAscent font ",&arg0, SWIGTYPE_SWFFont) == TCL_ERROR) return TCL_ERROR;
    result = (short )SWFFont_getAscent(arg0);
    Tcl_SetObjResult(interp,Tcl_NewIntObj((long) result));
    return TCL_OK;
}

static int
_wrap_SWFFont_getDescent(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFFont arg0 ;
    short result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:SWFFont_getDescent font ",&arg0, SWIGTYPE_SWFFont) == TCL_ERROR) return TCL_ERROR;
    result = (short )SWFFont_getDescent(arg0);
    Tcl_SetObjResult(interp,Tcl_NewIntObj((long) result));
    return TCL_OK;
}

static int
_wrap_SWFFont_getLeading(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFFont arg0 ;
    short result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:SWFFont_getLeading font ",&arg0, SWIGTYPE_SWFFont) == TCL_ERROR) return TCL_ERROR;
    result = (short )SWFFont_getLeading(arg0);
    Tcl_SetObjResult(interp,Tcl_NewIntObj((long) result));
    return TCL_OK;
}

static int
_wrap_newSWFText(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFText result ;
    
    if (SWIG_GetArgs(interp, objc, objv,":newSWFText ") == TCL_ERROR) return TCL_ERROR;
    result = (SWFText )newSWFText();
    Tcl_SetObjResult(interp,SWIG_NewPointerObj((void *) result,SWIGTYPE_SWFText));
    return TCL_OK;
}

static int
_wrap_newSWFText2(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFText result ;
    
    if (SWIG_GetArgs(interp, objc, objv,":newSWFText2 ") == TCL_ERROR) return TCL_ERROR;
    result = (SWFText )newSWFText2();
    Tcl_SetObjResult(interp,SWIG_NewPointerObj((void *) result,SWIGTYPE_SWFText));
    return TCL_OK;
}

static int
_wrap_destroySWFText(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFText arg0 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:destroySWFText text ",&arg0, SWIGTYPE_SWFText) == TCL_ERROR) return TCL_ERROR;
    destroySWFText(arg0);
    return TCL_OK;
}

static int
_wrap_SWFText_setFont(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFText arg0 ;
    SWFFont arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pp:SWFText_setFont text font ",&arg0, SWIGTYPE_SWFText,&arg1, SWIGTYPE_SWFFont) == TCL_ERROR) return TCL_ERROR;
    SWFText_setFont(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFText_setHeight(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFText arg0 ;
    int arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pi:SWFText_setHeight text height ",&arg0, SWIGTYPE_SWFText,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFText_setHeight(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFText_moveTo(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFText arg0 ;
    int arg1 ;
    int arg2 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pii:SWFText_moveTo text x y ",&arg0, SWIGTYPE_SWFText,&arg1,&arg2) == TCL_ERROR) return TCL_ERROR;
    SWFText_moveTo(arg0,arg1,arg2);
    return TCL_OK;
}

static int
_wrap_SWFText_setColor(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFText arg0 ;
    byte arg1 ;
    byte arg2 ;
    byte arg3 ;
    byte arg4 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pbbbb:SWFText_setColor text r g b a ",&arg0, SWIGTYPE_SWFText,&arg1,&arg2,&arg3,&arg4) == TCL_ERROR) return TCL_ERROR;
    SWFText_setColor(arg0,arg1,arg2,arg3,arg4);
    return TCL_OK;
}

static int
_wrap_SWFText_addString(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFText arg0 ;
    char *arg1 ;
    int *arg2 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"psp:SWFText_addString text string advance ",&arg0, SWIGTYPE_SWFText,&arg1,&arg2, SWIGTYPE_p_int) == TCL_ERROR) return TCL_ERROR;
    SWFText_addString(arg0,arg1,arg2);
    return TCL_OK;
}

static int
_wrap_SWFText_setSpacing(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFText arg0 ;
    float arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pf:SWFText_setSpacing text spacing ",&arg0, SWIGTYPE_SWFText,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFText_setSpacing(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFText_getStringWidth(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFText arg0 ;
    char *arg1 ;
    int result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"ps:SWFText_getStringWidth text string ",&arg0, SWIGTYPE_SWFText,&arg1) == TCL_ERROR) return TCL_ERROR;
    result = (int )SWFText_getStringWidth(arg0,arg1);
    Tcl_SetObjResult(interp,Tcl_NewIntObj((long) result));
    return TCL_OK;
}

static int
_wrap_newSWFBrowserFont(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    char *arg0 ;
    SWFBrowserFont result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"s:newSWFBrowserFont name ",&arg0) == TCL_ERROR) return TCL_ERROR;
    result = (SWFBrowserFont )newSWFBrowserFont(arg0);
    Tcl_SetObjResult(interp,SWIG_NewPointerObj((void *) result,SWIGTYPE_SWFBrowserFont));
    return TCL_OK;
}

static int
_wrap_destroySWFBrowserFont(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFBrowserFont arg0 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:destroySWFBrowserFont b ",&arg0, SWIGTYPE_SWFBrowserFont) == TCL_ERROR) return TCL_ERROR;
    destroySWFBrowserFont(arg0);
    return TCL_OK;
}

static int
_wrap_newSWFTextField(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFTextField result ;
    
    if (SWIG_GetArgs(interp, objc, objv,":newSWFTextField ") == TCL_ERROR) return TCL_ERROR;
    result = (SWFTextField )newSWFTextField();
    Tcl_SetObjResult(interp,SWIG_NewPointerObj((void *) result,SWIGTYPE_SWFTextField));
    return TCL_OK;
}

static int
_wrap_destroySWFTextField(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFTextField arg0 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:destroySWFTextField field ",&arg0, SWIGTYPE_SWFTextField) == TCL_ERROR) return TCL_ERROR;
    destroySWFTextField(arg0);
    return TCL_OK;
}

static int
_wrap_SWFTextField_setFont(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFTextField arg0 ;
    SWFBlock arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pp:SWFTextField_setFont field font ",&arg0, SWIGTYPE_SWFTextField,&arg1, SWIGTYPE_SWFBlock) == TCL_ERROR) return TCL_ERROR;
    SWFTextField_setFont(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFTextField_setBounds(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFTextField arg0 ;
    int arg1 ;
    int arg2 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pii:SWFTextField_setBounds field width height ",&arg0, SWIGTYPE_SWFTextField,&arg1,&arg2) == TCL_ERROR) return TCL_ERROR;
    SWFTextField_setBounds(arg0,arg1,arg2);
    return TCL_OK;
}

static int
_wrap_SWFTextField_setFlags(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFTextField arg0 ;
    int arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pi:SWFTextField_setFlags field flags ",&arg0, SWIGTYPE_SWFTextField,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFTextField_setFlags(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFTextField_setColor(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFTextField arg0 ;
    byte arg1 ;
    byte arg2 ;
    byte arg3 ;
    byte arg4 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pbbbb:SWFTextField_setColor field r g b a ",&arg0, SWIGTYPE_SWFTextField,&arg1,&arg2,&arg3,&arg4) == TCL_ERROR) return TCL_ERROR;
    SWFTextField_setColor(arg0,arg1,arg2,arg3,arg4);
    return TCL_OK;
}

static int
_wrap_SWFTextField_setVariableName(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFTextField arg0 ;
    char *arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"ps:SWFTextField_setVariableName field name ",&arg0, SWIGTYPE_SWFTextField,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFTextField_setVariableName(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFTextField_addString(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFTextField arg0 ;
    char *arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"ps:SWFTextField_addString field string ",&arg0, SWIGTYPE_SWFTextField,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFTextField_addString(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFTextField_setHeight(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFTextField arg0 ;
    int arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pi:SWFTextField_setHeight field height ",&arg0, SWIGTYPE_SWFTextField,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFTextField_setHeight(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFTextField_setLeftMargin(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFTextField arg0 ;
    int arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pi:SWFTextField_setLeftMargin field leftMargin ",&arg0, SWIGTYPE_SWFTextField,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFTextField_setLeftMargin(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFTextField_setRightMargin(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFTextField arg0 ;
    int arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pi:SWFTextField_setRightMargin field rightMargin ",&arg0, SWIGTYPE_SWFTextField,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFTextField_setRightMargin(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFTextField_setIndentation(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFTextField arg0 ;
    int arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pi:SWFTextField_setIndentation field indentation ",&arg0, SWIGTYPE_SWFTextField,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFTextField_setIndentation(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFTextField_setLineSpacing(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFTextField arg0 ;
    int arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pi:SWFTextField_setLineSpacing field lineSpacing ",&arg0, SWIGTYPE_SWFTextField,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFTextField_setLineSpacing(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_SWFTextField_setAlignment(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFTextField arg0 ;
    int arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pi:SWFTextField_setAlignment field alignment ",&arg0, SWIGTYPE_SWFTextField,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFTextField_setAlignment(arg0,(SWFTextFieldAlignment )arg1);
    return TCL_OK;
}

static int
_wrap_SWFTextField_setLength(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFTextField arg0 ;
    int arg1 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"pi:SWFTextField_setLength field length ",&arg0, SWIGTYPE_SWFTextField,&arg1) == TCL_ERROR) return TCL_ERROR;
    SWFTextField_setLength(arg0,arg1);
    return TCL_OK;
}

static int
_wrap_newSWFSound(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    FILE *arg0 ;
    SWFSound result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:newSWFSound file ",&arg0, SWIGTYPE_p_FILE) == TCL_ERROR) return TCL_ERROR;
    result = (SWFSound )newSWFSound(arg0);
    Tcl_SetObjResult(interp,SWIG_NewPointerObj((void *) result,SWIGTYPE_SWFSound));
    return TCL_OK;
}

static int
_wrap_destroySWFSound(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFSound arg0 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:destroySWFSound sound ",&arg0, SWIGTYPE_SWFSound) == TCL_ERROR) return TCL_ERROR;
    destroySWFSound(arg0);
    return TCL_OK;
}

static int
_wrap_compileSWFActionCode(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    char *arg0 ;
    SWFAction result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"s:compileSWFActionCode script ",&arg0) == TCL_ERROR) return TCL_ERROR;
    result = (SWFAction )compileSWFActionCode(arg0);
    Tcl_SetObjResult(interp,SWIG_NewPointerObj((void *) result,SWIGTYPE_SWFAction));
    return TCL_OK;
}

static int
_wrap_swfButton_keypress(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    char arg0 ;
    int result ;
    
    if (SWIG_GetArgs(interp, objc, objv,"c:swfButton_keypress c ",&arg0) == TCL_ERROR) return TCL_ERROR;
    result = (int )swfButton_keypress(arg0);
    Tcl_SetObjResult(interp,Tcl_NewIntObj((long) result));
    return TCL_OK;
}

static int
_wrap_newSWFButton(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFButton result ;
    
    if (SWIG_GetArgs(interp, objc, objv,":newSWFButton ") == TCL_ERROR) return TCL_ERROR;
    result = (SWFButton )newSWFButton();
    Tcl_SetObjResult(interp,SWIG_NewPointerObj((void *) result,SWIGTYPE_SWFButton));
    return TCL_OK;
}

static int
_wrap_destroySWFButton(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFButton arg0 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"p:destroySWFButton button ",&arg0, SWIGTYPE_SWFButton) == TCL_ERROR) return TCL_ERROR;
    destroySWFButton(arg0);
    return TCL_OK;
}

static int
_wrap_SWFButton_addShape(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFButton arg0 ;
    SWFCharacter arg1 ;
    byte arg2 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"ppb:SWFButton_addShape button character flags ",&arg0, SWIGTYPE_SWFButton,&arg1, SWIGTYPE_SWFCharacter,&arg2) == TCL_ERROR) return TCL_ERROR;
    SWFButton_addShape(arg0,arg1,arg2);
    return TCL_OK;
}

static int
_wrap_SWFButton_addAction(ClientData clientData, Tcl_Interp *interp, int objc, Tcl_Obj *CONST objv[]) {
    SWFButton arg0 ;
    SWFAction arg1 ;
    int arg2 ;
    
    if (SWIG_GetArgs(interp, objc, objv,"ppi:SWFButton_addAction button action flags ",&arg0, SWIGTYPE_SWFButton,&arg1, SWIGTYPE_SWFAction,&arg2) == TCL_ERROR) return TCL_ERROR;
    SWFButton_addAction(arg0,arg1,arg2);
    return TCL_OK;
}


static swig_command_info swig_commands[] = {
    { SWIG_prefix "Ming_init", _wrap_Ming_init, NULL},
    { SWIG_prefix "destroySWFMovie", _wrap_destroySWFMovie, NULL},
    { SWIG_prefix "newSWFMovie", _wrap_newSWFMovie, NULL},
    { SWIG_prefix "SWFMovie_setRate", _wrap_SWFMovie_setRate, NULL},
    { SWIG_prefix "SWFMovie_setDimension", _wrap_SWFMovie_setDimension, NULL},
    { SWIG_prefix "SWFMovie_setNumberOfFrames", _wrap_SWFMovie_setNumberOfFrames, NULL},
    { SWIG_prefix "SWFMovie_setBackground", _wrap_SWFMovie_setBackground, NULL},
    { SWIG_prefix "SWFMovie_setSoundStream", _wrap_SWFMovie_setSoundStream, NULL},
    { SWIG_prefix "SWFMovie_add", _wrap_SWFMovie_add, NULL},
    { SWIG_prefix "SWFMovie_remove", _wrap_SWFMovie_remove, NULL},
    { SWIG_prefix "SWFMovie_nextFrame", _wrap_SWFMovie_nextFrame, NULL},
    { SWIG_prefix "SWFMovie_labelFrame", _wrap_SWFMovie_labelFrame, NULL},
    { SWIG_prefix "SWFMovie_output", _wrap_SWFMovie_output, NULL},
    { SWIG_prefix "SWFMovie_simpleOutput", _wrap_SWFMovie_simpleOutput, NULL},
    { SWIG_prefix "SWFMovie_save", _wrap_SWFMovie_save, NULL},
    { SWIG_prefix "SWFDisplayItem_rotate", _wrap_SWFDisplayItem_rotate, NULL},
    { SWIG_prefix "SWFDisplayItem_rotateTo", _wrap_SWFDisplayItem_rotateTo, NULL},
    { SWIG_prefix "SWFDisplayItem_move", _wrap_SWFDisplayItem_move, NULL},
    { SWIG_prefix "SWFDisplayItem_moveTo", _wrap_SWFDisplayItem_moveTo, NULL},
    { SWIG_prefix "SWFDisplayItem_scale", _wrap_SWFDisplayItem_scale, NULL},
    { SWIG_prefix "SWFDisplayItem_scaleTo", _wrap_SWFDisplayItem_scaleTo, NULL},
    { SWIG_prefix "SWFDisplayItem_skewX", _wrap_SWFDisplayItem_skewX, NULL},
    { SWIG_prefix "SWFDisplayItem_skewXTo", _wrap_SWFDisplayItem_skewXTo, NULL},
    { SWIG_prefix "SWFDisplayItem_skewY", _wrap_SWFDisplayItem_skewY, NULL},
    { SWIG_prefix "SWFDisplayItem_skewYTo", _wrap_SWFDisplayItem_skewYTo, NULL},
    { SWIG_prefix "SWFDisplayItem_getDepth", _wrap_SWFDisplayItem_getDepth, NULL},
    { SWIG_prefix "SWFDisplayItem_setDepth", _wrap_SWFDisplayItem_setDepth, NULL},
    { SWIG_prefix "SWFDisplayItem_remove", _wrap_SWFDisplayItem_remove, NULL},
    { SWIG_prefix "SWFDisplayItem_setName", _wrap_SWFDisplayItem_setName, NULL},
    { SWIG_prefix "SWFDisplayItem_setRatio", _wrap_SWFDisplayItem_setRatio, NULL},
    { SWIG_prefix "SWFDisplayItem_setCXform", _wrap_SWFDisplayItem_setCXform, NULL},
    { SWIG_prefix "SWFDisplayItem_setColorAdd", _wrap_SWFDisplayItem_setColorAdd, NULL},
    { SWIG_prefix "SWFDisplayItem_setColorMult", _wrap_SWFDisplayItem_setColorMult, NULL},
    { SWIG_prefix "destroySWFFill", _wrap_destroySWFFill, NULL},
    { SWIG_prefix "SWFFill_skewX", _wrap_SWFFill_skewX, NULL},
    { SWIG_prefix "SWFFill_skewXTo", _wrap_SWFFill_skewXTo, NULL},
    { SWIG_prefix "SWFFill_skewY", _wrap_SWFFill_skewY, NULL},
    { SWIG_prefix "SWFFill_skewYTo", _wrap_SWFFill_skewYTo, NULL},
    { SWIG_prefix "SWFFill_scaleX", _wrap_SWFFill_scaleX, NULL},
    { SWIG_prefix "SWFFill_scaleXTo", _wrap_SWFFill_scaleXTo, NULL},
    { SWIG_prefix "SWFFill_scaleY", _wrap_SWFFill_scaleY, NULL},
    { SWIG_prefix "SWFFill_scaleYTo", _wrap_SWFFill_scaleYTo, NULL},
    { SWIG_prefix "SWFFill_scaleXY", _wrap_SWFFill_scaleXY, NULL},
    { SWIG_prefix "SWFFill_scaleXYTo", _wrap_SWFFill_scaleXYTo, NULL},
    { SWIG_prefix "SWFFill_rotate", _wrap_SWFFill_rotate, NULL},
    { SWIG_prefix "SWFFill_rotateTo", _wrap_SWFFill_rotateTo, NULL},
    { SWIG_prefix "SWFFill_move", _wrap_SWFFill_move, NULL},
    { SWIG_prefix "SWFFill_moveTo", _wrap_SWFFill_moveTo, NULL},
    { SWIG_prefix "SWFShape_addSolidFill", _wrap_SWFShape_addSolidFill, NULL},
    { SWIG_prefix "SWFShape_addGradientFill", _wrap_SWFShape_addGradientFill, NULL},
    { SWIG_prefix "SWFShape_addBitmapFill", _wrap_SWFShape_addBitmapFill, NULL},
    { SWIG_prefix "SWFShape_setLeftFill", _wrap_SWFShape_setLeftFill, NULL},
    { SWIG_prefix "SWFShape_setRightFill", _wrap_SWFShape_setRightFill, NULL},
    { SWIG_prefix "SWFShape_setLine", _wrap_SWFShape_setLine, NULL},
    { SWIG_prefix "SWFShape_drawArc", _wrap_SWFShape_drawArc, NULL},
    { SWIG_prefix "SWFShape_drawCircle", _wrap_SWFShape_drawCircle, NULL},
    { SWIG_prefix "SWFShape_drawFontGlyph", _wrap_SWFShape_drawFontGlyph, NULL},
    { SWIG_prefix "newSWFMovieClip", _wrap_newSWFMovieClip, NULL},
    { SWIG_prefix "destroySWFMovieClip", _wrap_destroySWFMovieClip, NULL},
    { SWIG_prefix "SWFMovieClip_setNumberOfFrames", _wrap_SWFMovieClip_setNumberOfFrames, NULL},
    { SWIG_prefix "SWFMovieClip_add", _wrap_SWFMovieClip_add, NULL},
    { SWIG_prefix "SWFMovieClip_remove", _wrap_SWFMovieClip_remove, NULL},
    { SWIG_prefix "SWFMovieClip_nextFrame", _wrap_SWFMovieClip_nextFrame, NULL},
    { SWIG_prefix "SWFMovieClip_labelFrame", _wrap_SWFMovieClip_labelFrame, NULL},
    { SWIG_prefix "newSWFRect", _wrap_newSWFRect, NULL},
    { SWIG_prefix "destroySWFRect", _wrap_destroySWFRect, NULL},
    { SWIG_prefix "SWFRect_getWidth", _wrap_SWFRect_getWidth, NULL},
    { SWIG_prefix "SWFRect_getHeight", _wrap_SWFRect_getHeight, NULL},
    { SWIG_prefix "SWFCharacter_getBounds", _wrap_SWFCharacter_getBounds, NULL},
    { SWIG_prefix "SWFBlock_isCharacter", _wrap_SWFBlock_isCharacter, NULL},
    { SWIG_prefix "destroySWFBitmap", _wrap_destroySWFBitmap, NULL},
    { SWIG_prefix "SWFBitmap_getWidth", _wrap_SWFBitmap_getWidth, NULL},
    { SWIG_prefix "SWFBitmap_getHeight", _wrap_SWFBitmap_getHeight, NULL},
    { SWIG_prefix "newSWFDBLBitmap", _wrap_newSWFDBLBitmap, NULL},
    { SWIG_prefix "newSWFJpegBitmap", _wrap_newSWFJpegBitmap, NULL},
    { SWIG_prefix "newSWFJpegWithAlpha", _wrap_newSWFJpegWithAlpha, NULL},
    { SWIG_prefix "newSWFGradient", _wrap_newSWFGradient, NULL},
    { SWIG_prefix "destroySWFGradient", _wrap_destroySWFGradient, NULL},
    { SWIG_prefix "SWFGradient_addEntry", _wrap_SWFGradient_addEntry, NULL},
    { SWIG_prefix "newSWFMatrix", _wrap_newSWFMatrix, NULL},
    { SWIG_prefix "destroySWFMatrix", _wrap_destroySWFMatrix, NULL},
    { SWIG_prefix "SWFMatrix_set", _wrap_SWFMatrix_set, NULL},
    { SWIG_prefix "newSWFShape", _wrap_newSWFShape, NULL},
    { SWIG_prefix "destroySWFShape", _wrap_destroySWFShape, NULL},
    { SWIG_prefix "SWFShape_moveTo", _wrap_SWFShape_moveTo, NULL},
    { SWIG_prefix "SWFShape_moveToRelative", _wrap_SWFShape_moveToRelative, NULL},
    { SWIG_prefix "SWFShape_lineTo", _wrap_SWFShape_lineTo, NULL},
    { SWIG_prefix "SWFShape_lineToRelative", _wrap_SWFShape_lineToRelative, NULL},
    { SWIG_prefix "SWFShape_curveTo", _wrap_SWFShape_curveTo, NULL},
    { SWIG_prefix "SWFShape_curveToRelative", _wrap_SWFShape_curveToRelative, NULL},
    { SWIG_prefix "SWFShape_end", _wrap_SWFShape_end, NULL},
    { SWIG_prefix "newSWFMorphShape", _wrap_newSWFMorphShape, NULL},
    { SWIG_prefix "destroySWFMorph", _wrap_destroySWFMorph, NULL},
    { SWIG_prefix "SWFMorph_getShape1", _wrap_SWFMorph_getShape1, NULL},
    { SWIG_prefix "SWFMorph_getShape2", _wrap_SWFMorph_getShape2, NULL},
    { SWIG_prefix "newSWFFont", _wrap_newSWFFont, NULL},
    { SWIG_prefix "destroySWFFont", _wrap_destroySWFFont, NULL},
    { SWIG_prefix "loadSWFFontFromFile", _wrap_loadSWFFontFromFile, NULL},
    { SWIG_prefix "SWFFont_getStringWidth", _wrap_SWFFont_getStringWidth, NULL},
    { SWIG_prefix "SWFFont_getAscent", _wrap_SWFFont_getAscent, NULL},
    { SWIG_prefix "SWFFont_getDescent", _wrap_SWFFont_getDescent, NULL},
    { SWIG_prefix "SWFFont_getLeading", _wrap_SWFFont_getLeading, NULL},
    { SWIG_prefix "newSWFText", _wrap_newSWFText, NULL},
    { SWIG_prefix "newSWFText2", _wrap_newSWFText2, NULL},
    { SWIG_prefix "destroySWFText", _wrap_destroySWFText, NULL},
    { SWIG_prefix "SWFText_setFont", _wrap_SWFText_setFont, NULL},
    { SWIG_prefix "SWFText_setHeight", _wrap_SWFText_setHeight, NULL},
    { SWIG_prefix "SWFText_moveTo", _wrap_SWFText_moveTo, NULL},
    { SWIG_prefix "SWFText_setColor", _wrap_SWFText_setColor, NULL},
    { SWIG_prefix "SWFText_addString", _wrap_SWFText_addString, NULL},
    { SWIG_prefix "SWFText_setSpacing", _wrap_SWFText_setSpacing, NULL},
    { SWIG_prefix "SWFText_getStringWidth", _wrap_SWFText_getStringWidth, NULL},
    { SWIG_prefix "newSWFBrowserFont", _wrap_newSWFBrowserFont, NULL},
    { SWIG_prefix "destroySWFBrowserFont", _wrap_destroySWFBrowserFont, NULL},
    { SWIG_prefix "newSWFTextField", _wrap_newSWFTextField, NULL},
    { SWIG_prefix "destroySWFTextField", _wrap_destroySWFTextField, NULL},
    { SWIG_prefix "SWFTextField_setFont", _wrap_SWFTextField_setFont, NULL},
    { SWIG_prefix "SWFTextField_setBounds", _wrap_SWFTextField_setBounds, NULL},
    { SWIG_prefix "SWFTextField_setFlags", _wrap_SWFTextField_setFlags, NULL},
    { SWIG_prefix "SWFTextField_setColor", _wrap_SWFTextField_setColor, NULL},
    { SWIG_prefix "SWFTextField_setVariableName", _wrap_SWFTextField_setVariableName, NULL},
    { SWIG_prefix "SWFTextField_addString", _wrap_SWFTextField_addString, NULL},
    { SWIG_prefix "SWFTextField_setHeight", _wrap_SWFTextField_setHeight, NULL},
    { SWIG_prefix "SWFTextField_setLeftMargin", _wrap_SWFTextField_setLeftMargin, NULL},
    { SWIG_prefix "SWFTextField_setRightMargin", _wrap_SWFTextField_setRightMargin, NULL},
    { SWIG_prefix "SWFTextField_setIndentation", _wrap_SWFTextField_setIndentation, NULL},
    { SWIG_prefix "SWFTextField_setLineSpacing", _wrap_SWFTextField_setLineSpacing, NULL},
    { SWIG_prefix "SWFTextField_setAlignment", _wrap_SWFTextField_setAlignment, NULL},
    { SWIG_prefix "SWFTextField_setLength", _wrap_SWFTextField_setLength, NULL},
    { SWIG_prefix "newSWFSound", _wrap_newSWFSound, NULL},
    { SWIG_prefix "destroySWFSound", _wrap_destroySWFSound, NULL},
    { SWIG_prefix "compileSWFActionCode", _wrap_compileSWFActionCode, NULL},
    { SWIG_prefix "swfButton_keypress", _wrap_swfButton_keypress, NULL},
    { SWIG_prefix "newSWFButton", _wrap_newSWFButton, NULL},
    { SWIG_prefix "destroySWFButton", _wrap_destroySWFButton, NULL},
    { SWIG_prefix "SWFButton_addShape", _wrap_SWFButton_addShape, NULL},
    { SWIG_prefix "SWFButton_addAction", _wrap_SWFButton_addAction, NULL},
    {0, 0, 0}
};

static swig_var_info swig_variables[] = {
    { SWIG_prefix "SWFFILL_SOLID", (void *) &_wrap_const_SWFFILL_SOLID,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFFILL_GRADIENT", (void *) &_wrap_const_SWFFILL_GRADIENT,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFFILL_LINEAR_GRADIENT", (void *) &_wrap_const_SWFFILL_LINEAR_GRADIENT,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFFILL_RADIAL_GRADIENT", (void *) &_wrap_const_SWFFILL_RADIAL_GRADIENT,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFFILL_BITMAP", (void *) &_wrap_const_SWFFILL_BITMAP,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFFILL_TILED_BITMAP", (void *) &_wrap_const_SWFFILL_TILED_BITMAP,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFFILL_CLIPPED_BITMAP", (void *) &_wrap_const_SWFFILL_CLIPPED_BITMAP,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFTEXTFIELD_ONMASK", (void *) &_wrap_const_SWFTEXTFIELD_ONMASK,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFTEXTFIELD_OFFMASK", (void *) &_wrap_const_SWFTEXTFIELD_OFFMASK,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFTEXTFIELD_HASLENGTH", (void *) &_wrap_const_SWFTEXTFIELD_HASLENGTH,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFTEXTFIELD_NOEDIT", (void *) &_wrap_const_SWFTEXTFIELD_NOEDIT,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFTEXTFIELD_PASSWORD", (void *) &_wrap_const_SWFTEXTFIELD_PASSWORD,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFTEXTFIELD_MULTILINE", (void *) &_wrap_const_SWFTEXTFIELD_MULTILINE,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFTEXTFIELD_WORDWRAP", (void *) &_wrap_const_SWFTEXTFIELD_WORDWRAP,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFTEXTFIELD_DRAWBOX", (void *) &_wrap_const_SWFTEXTFIELD_DRAWBOX,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFTEXTFIELD_NOSELECT", (void *) &_wrap_const_SWFTEXTFIELD_NOSELECT,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFTEXTFIELD_ALIGN_LEFT", (void *) &_wrap_const_SWFTEXTFIELD_ALIGN_LEFT,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFTEXTFIELD_ALIGN_RIGHT", (void *) &_wrap_const_SWFTEXTFIELD_ALIGN_RIGHT,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFTEXTFIELD_ALIGN_CENTER", (void *) &_wrap_const_SWFTEXTFIELD_ALIGN_CENTER,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFTEXTFIELD_ALIGN_JUSTIFY", (void *) &_wrap_const_SWFTEXTFIELD_ALIGN_JUSTIFY,swig_int_get,swig_readonly},
    { SWIG_prefix "SWF_SOUND_COMPRESSION", (void *) &_wrap_const_SWF_SOUND_COMPRESSION,swig_int_get,swig_readonly},
    { SWIG_prefix "SWF_SOUND_NOT_COMPRESSED", (void *) &_wrap_const_SWF_SOUND_NOT_COMPRESSED,swig_int_get,swig_readonly},
    { SWIG_prefix "SWF_SOUND_ADPCM_COMPRESSED", (void *) &_wrap_const_SWF_SOUND_ADPCM_COMPRESSED,swig_int_get,swig_readonly},
    { SWIG_prefix "SWF_SOUND_RATE", (void *) &_wrap_const_SWF_SOUND_RATE,swig_int_get,swig_readonly},
    { SWIG_prefix "SWF_SOUND_5KHZ", (void *) &_wrap_const_SWF_SOUND_5KHZ,swig_int_get,swig_readonly},
    { SWIG_prefix "SWF_SOUND_11KHZ", (void *) &_wrap_const_SWF_SOUND_11KHZ,swig_int_get,swig_readonly},
    { SWIG_prefix "SWF_SOUND_22KHZ", (void *) &_wrap_const_SWF_SOUND_22KHZ,swig_int_get,swig_readonly},
    { SWIG_prefix "SWF_SOUND_44KHZ", (void *) &_wrap_const_SWF_SOUND_44KHZ,swig_int_get,swig_readonly},
    { SWIG_prefix "SWF_SOUND_BITS", (void *) &_wrap_const_SWF_SOUND_BITS,swig_int_get,swig_readonly},
    { SWIG_prefix "SWF_SOUND_8BIT", (void *) &_wrap_const_SWF_SOUND_8BIT,swig_int_get,swig_readonly},
    { SWIG_prefix "SWF_SOUND_16BIT", (void *) &_wrap_const_SWF_SOUND_16BIT,swig_int_get,swig_readonly},
    { SWIG_prefix "SWF_SOUND_CHANNELS", (void *) &_wrap_const_SWF_SOUND_CHANNELS,swig_int_get,swig_readonly},
    { SWIG_prefix "SWF_SOUND_MONO", (void *) &_wrap_const_SWF_SOUND_MONO,swig_int_get,swig_readonly},
    { SWIG_prefix "SWF_SOUND_STEREO", (void *) &_wrap_const_SWF_SOUND_STEREO,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFBUTTON_HIT", (void *) &_wrap_const_SWFBUTTON_HIT,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFBUTTON_DOWN", (void *) &_wrap_const_SWFBUTTON_DOWN,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFBUTTON_OVER", (void *) &_wrap_const_SWFBUTTON_OVER,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFBUTTON_UP", (void *) &_wrap_const_SWFBUTTON_UP,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFBUTTON_OVERDOWNTOIDLE", (void *) &_wrap_const_SWFBUTTON_OVERDOWNTOIDLE,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFBUTTON_IDLETOOVERDOWN", (void *) &_wrap_const_SWFBUTTON_IDLETOOVERDOWN,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFBUTTON_OUTDOWNTOIDLE", (void *) &_wrap_const_SWFBUTTON_OUTDOWNTOIDLE,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFBUTTON_OUTDOWNTOOVERDOWN", (void *) &_wrap_const_SWFBUTTON_OUTDOWNTOOVERDOWN,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFBUTTON_OVERDOWNTOOUTDOWN", (void *) &_wrap_const_SWFBUTTON_OVERDOWNTOOUTDOWN,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFBUTTON_OVERDOWNTOOVERUP", (void *) &_wrap_const_SWFBUTTON_OVERDOWNTOOVERUP,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFBUTTON_OVERUPTOOVERDOWN", (void *) &_wrap_const_SWFBUTTON_OVERUPTOOVERDOWN,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFBUTTON_OVERUPTOIDLE", (void *) &_wrap_const_SWFBUTTON_OVERUPTOIDLE,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFBUTTON_IDLETOOVERUP", (void *) &_wrap_const_SWFBUTTON_IDLETOOVERUP,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFBUTTON_MOUSEUPOUTSIDE", (void *) &_wrap_const_SWFBUTTON_MOUSEUPOUTSIDE,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFBUTTON_DRAGOVER", (void *) &_wrap_const_SWFBUTTON_DRAGOVER,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFBUTTON_DRAGOUT", (void *) &_wrap_const_SWFBUTTON_DRAGOUT,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFBUTTON_MOUSEUP", (void *) &_wrap_const_SWFBUTTON_MOUSEUP,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFBUTTON_MOUSEDOWN", (void *) &_wrap_const_SWFBUTTON_MOUSEDOWN,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFBUTTON_MOUSEOUT", (void *) &_wrap_const_SWFBUTTON_MOUSEOUT,swig_int_get,swig_readonly},
    { SWIG_prefix "SWFBUTTON_MOUSEOVER", (void *) &_wrap_const_SWFBUTTON_MOUSEOVER,swig_int_get,swig_readonly},
    {0,0,0,0}
};

/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__SWFMovieClip[] = {{"_SWFMovieClip", 0, "SWFMovieClip "},{"_SWFMovieClip"},{"_SWFMovie"},{"_SWFGradient"},{"_SWFDisplayItem"},{"_SWFShape"},{"_SWFText"},{"_SWFBitmap"},{"_SWFFont"},{"_p_void"},{"_SWFButton"},{"_SWFMorph"},{"_SWFTextField"},{"_SWFBlock"},{"_SWFFill"},{"_SWFMatrix"},{"_SWFSound"},{"_SWFAction"},{"_SWFBrowserFont"},{"_SWFCharacter"},{0}};
static swig_type_info _swigt__SWFMovie[] = {{"_SWFMovie", 0, "SWFMovie "},{"_SWFMovieClip"},{"_SWFMovie"},{"_SWFGradient"},{"_SWFDisplayItem"},{"_SWFShape"},{"_SWFText"},{"_SWFBitmap"},{"_SWFFont"},{"_p_void"},{"_SWFButton"},{"_SWFMorph"},{"_SWFTextField"},{"_SWFBlock"},{"_SWFFill"},{"_SWFMatrix"},{"_SWFSound"},{"_SWFAction"},{"_SWFBrowserFont"},{"_SWFCharacter"},{0}};
static swig_type_info _swigt__SWFGradient[] = {{"_SWFGradient", 0, "SWFGradient "},{"_SWFMovieClip"},{"_SWFMovie"},{"_SWFGradient"},{"_SWFDisplayItem"},{"_SWFShape"},{"_SWFText"},{"_SWFBitmap"},{"_SWFFont"},{"_p_void"},{"_SWFButton"},{"_SWFMorph"},{"_SWFTextField"},{"_SWFBlock"},{"_SWFFill"},{"_SWFMatrix"},{"_SWFSound"},{"_SWFAction"},{"_SWFBrowserFont"},{"_SWFCharacter"},{0}};
static swig_type_info _swigt__SWFDisplayItem[] = {{"_SWFDisplayItem", 0, "SWFDisplayItem "},{"_SWFMovieClip"},{"_SWFMovie"},{"_SWFGradient"},{"_SWFDisplayItem"},{"_SWFShape"},{"_SWFText"},{"_SWFBitmap"},{"_SWFFont"},{"_p_void"},{"_SWFButton"},{"_SWFMorph"},{"_SWFTextField"},{"_SWFBlock"},{"_SWFFill"},{"_SWFMatrix"},{"_SWFSound"},{"_SWFAction"},{"_SWFBrowserFont"},{"_SWFCharacter"},{0}};
static swig_type_info _swigt__SWFShape[] = {{"_SWFShape", 0, "SWFShape "},{"_SWFMovieClip"},{"_SWFMovie"},{"_SWFGradient"},{"_SWFDisplayItem"},{"_SWFShape"},{"_SWFText"},{"_SWFBitmap"},{"_SWFFont"},{"_p_void"},{"_SWFButton"},{"_SWFMorph"},{"_SWFTextField"},{"_SWFBlock"},{"_SWFFill"},{"_SWFMatrix"},{"_SWFSound"},{"_SWFAction"},{"_SWFBrowserFont"},{"_SWFCharacter"},{0}};
static swig_type_info _swigt__SWFBitmap[] = {{"_SWFBitmap", 0, "SWFBitmap "},{"_SWFMovieClip"},{"_SWFMovie"},{"_SWFGradient"},{"_SWFDisplayItem"},{"_SWFShape"},{"_SWFText"},{"_SWFBitmap"},{"_SWFFont"},{"_p_void"},{"_SWFButton"},{"_SWFMorph"},{"_SWFTextField"},{"_SWFBlock"},{"_SWFFill"},{"_SWFMatrix"},{"_SWFSound"},{"_SWFAction"},{"_SWFBrowserFont"},{"_SWFCharacter"},{0}};
static swig_type_info _swigt__p_SWFByteOutputMethod[] = {{"_p_SWFByteOutputMethod", 0, "SWFByteOutputMethod *"},{"_p_SWFByteOutputMethod"},{0}};
static swig_type_info _swigt__p_SWFCXform[] = {{"_p_SWFCXform", 0, "SWFCXform *"},{"_p_SWFCXform"},{0}};
static swig_type_info _swigt__SWFText[] = {{"_SWFText", 0, "SWFText "},{"_SWFMovieClip"},{"_SWFMovie"},{"_SWFGradient"},{"_SWFDisplayItem"},{"_SWFShape"},{"_SWFText"},{"_SWFBitmap"},{"_SWFFont"},{"_p_void"},{"_SWFButton"},{"_SWFMorph"},{"_SWFTextField"},{"_SWFBlock"},{"_SWFFill"},{"_SWFMatrix"},{"_SWFSound"},{"_SWFAction"},{"_SWFBrowserFont"},{"_SWFCharacter"},{0}};
static swig_type_info _swigt__SWFFont[] = {{"_SWFFont", 0, "SWFFont "},{"_SWFMovieClip"},{"_SWFMovie"},{"_SWFGradient"},{"_SWFDisplayItem"},{"_SWFShape"},{"_SWFText"},{"_SWFBitmap"},{"_SWFFont"},{"_p_void"},{"_SWFButton"},{"_SWFMorph"},{"_SWFTextField"},{"_SWFBlock"},{"_SWFFill"},{"_SWFMatrix"},{"_SWFSound"},{"_SWFAction"},{"_SWFBrowserFont"},{"_SWFCharacter"},{0}};
static swig_type_info _swigt__p_void[] = {{"_p_void", 0, "void *"},{"_SWFMovieClip"},{"_SWFMovie"},{"_SWFGradient"},{"_SWFDisplayItem"},{"_SWFShape"},{"_SWFText"},{"_SWFBitmap"},{"_SWFFont"},{"_p_void"},{"_SWFButton"},{"_SWFMorph"},{"_SWFTextField"},{"_SWFBlock"},{"_SWFFill"},{"_SWFMatrix"},{"_SWFSound"},{"_SWFAction"},{"_SWFBrowserFont"},{"_SWFCharacter"},{0}};
static swig_type_info _swigt__SWFMorph[] = {{"_SWFMorph", 0, "SWFMorph "},{"_SWFMovieClip"},{"_SWFMovie"},{"_SWFGradient"},{"_SWFDisplayItem"},{"_SWFShape"},{"_SWFText"},{"_SWFBitmap"},{"_SWFFont"},{"_p_void"},{"_SWFButton"},{"_SWFMorph"},{"_SWFTextField"},{"_SWFBlock"},{"_SWFFill"},{"_SWFMatrix"},{"_SWFSound"},{"_SWFAction"},{"_SWFBrowserFont"},{"_SWFCharacter"},{0}};
static swig_type_info _swigt__SWFButton[] = {{"_SWFButton", 0, "SWFButton "},{"_SWFMovieClip"},{"_SWFMovie"},{"_SWFGradient"},{"_SWFDisplayItem"},{"_SWFShape"},{"_SWFText"},{"_SWFBitmap"},{"_SWFFont"},{"_p_void"},{"_SWFButton"},{"_SWFMorph"},{"_SWFTextField"},{"_SWFBlock"},{"_SWFFill"},{"_SWFMatrix"},{"_SWFSound"},{"_SWFAction"},{"_SWFBrowserFont"},{"_SWFCharacter"},{0}};
static swig_type_info _swigt__SWFBlock[] = {{"_SWFBlock", 0, "SWFBlock "},{"_SWFMovieClip"},{"_SWFMovie"},{"_SWFGradient"},{"_SWFDisplayItem"},{"_SWFShape"},{"_SWFText"},{"_SWFBitmap"},{"_SWFFont"},{"_p_void"},{"_SWFButton"},{"_SWFMorph"},{"_SWFTextField"},{"_SWFBlock"},{"_SWFFill"},{"_SWFMatrix"},{"_SWFSound"},{"_SWFAction"},{"_SWFBrowserFont"},{"_SWFCharacter"},{0}};
static swig_type_info _swigt__SWFTextField[] = {{"_SWFTextField", 0, "SWFTextField "},{"_SWFMovieClip"},{"_SWFMovie"},{"_SWFGradient"},{"_SWFDisplayItem"},{"_SWFShape"},{"_SWFText"},{"_SWFBitmap"},{"_SWFFont"},{"_p_void"},{"_SWFButton"},{"_SWFMorph"},{"_SWFTextField"},{"_SWFBlock"},{"_SWFFill"},{"_SWFMatrix"},{"_SWFSound"},{"_SWFAction"},{"_SWFBrowserFont"},{"_SWFCharacter"},{0}};
static swig_type_info _swigt__p_FILE[] = {{"_p_FILE", 0, "FILE *"},{"_p_FILE"},{0}};
static swig_type_info _swigt__p_SWFRect[] = {{"_p_SWFRect", 0, "SWFRect *"},{"_p_SWFRect"},{0}};
static swig_type_info _swigt__SWFFill[] = {{"_SWFFill", 0, "SWFFill "},{"_SWFMovieClip"},{"_SWFMovie"},{"_SWFGradient"},{"_SWFDisplayItem"},{"_SWFShape"},{"_SWFText"},{"_SWFBitmap"},{"_SWFFont"},{"_p_void"},{"_SWFButton"},{"_SWFMorph"},{"_SWFBlock"},{"_SWFTextField"},{"_SWFFill"},{"_SWFMatrix"},{"_SWFSound"},{"_SWFAction"},{"_SWFBrowserFont"},{"_SWFCharacter"},{0}};
static swig_type_info _swigt__SWFMatrix[] = {{"_SWFMatrix", 0, "SWFMatrix "},{"_SWFMovieClip"},{"_SWFMovie"},{"_SWFGradient"},{"_SWFDisplayItem"},{"_SWFShape"},{"_SWFText"},{"_SWFBitmap"},{"_SWFFont"},{"_p_void"},{"_SWFButton"},{"_SWFMorph"},{"_SWFBlock"},{"_SWFTextField"},{"_SWFFill"},{"_SWFMatrix"},{"_SWFSound"},{"_SWFAction"},{"_SWFBrowserFont"},{"_SWFCharacter"},{0}};
static swig_type_info _swigt__SWFSound[] = {{"_SWFSound", 0, "SWFSound "},{"_SWFMovieClip"},{"_SWFMovie"},{"_SWFGradient"},{"_SWFDisplayItem"},{"_SWFShape"},{"_SWFText"},{"_SWFBitmap"},{"_SWFFont"},{"_p_void"},{"_SWFButton"},{"_SWFMorph"},{"_SWFBlock"},{"_SWFTextField"},{"_SWFFill"},{"_SWFMatrix"},{"_SWFSound"},{"_SWFAction"},{"_SWFBrowserFont"},{"_SWFCharacter"},{0}};
static swig_type_info _swigt__SWFAction[] = {{"_SWFAction", 0, "SWFAction "},{"_SWFMovieClip"},{"_SWFMovie"},{"_SWFGradient"},{"_SWFDisplayItem"},{"_SWFShape"},{"_SWFText"},{"_SWFBitmap"},{"_SWFFont"},{"_p_void"},{"_SWFButton"},{"_SWFMorph"},{"_SWFBlock"},{"_SWFTextField"},{"_SWFFill"},{"_SWFMatrix"},{"_SWFSound"},{"_SWFAction"},{"_SWFBrowserFont"},{"_SWFCharacter"},{0}};
static swig_type_info _swigt__SWFCharacter[] = {{"_SWFCharacter", 0, "SWFCharacter "},{"_SWFMovieClip"},{"_SWFMovie"},{"_SWFGradient"},{"_SWFDisplayItem"},{"_SWFShape"},{"_SWFText"},{"_SWFBitmap"},{"_SWFFont"},{"_p_void"},{"_SWFButton"},{"_SWFMorph"},{"_SWFBlock"},{"_SWFTextField"},{"_SWFFill"},{"_SWFMatrix"},{"_SWFSound"},{"_SWFAction"},{"_SWFBrowserFont"},{"_SWFCharacter"},{0}};
static swig_type_info _swigt__p_int[] = {{"_p_int", 0, "int *"},{"_p_int"},{0}};
static swig_type_info _swigt__SWFBrowserFont[] = {{"_SWFBrowserFont", 0, "SWFBrowserFont "},{"_SWFMovieClip"},{"_SWFMovie"},{"_SWFGradient"},{"_SWFDisplayItem"},{"_SWFShape"},{"_SWFText"},{"_SWFBitmap"},{"_SWFFont"},{"_p_void"},{"_SWFButton"},{"_SWFMorph"},{"_SWFBlock"},{"_SWFTextField"},{"_SWFFill"},{"_SWFMatrix"},{"_SWFSound"},{"_SWFAction"},{"_SWFBrowserFont"},{"_SWFCharacter"},{0}};

static swig_type_info *swig_types_initial[] = {
_swigt__SWFMovieClip, 
_swigt__SWFMovie, 
_swigt__SWFGradient, 
_swigt__SWFDisplayItem, 
_swigt__SWFShape, 
_swigt__SWFBitmap, 
_swigt__p_SWFByteOutputMethod, 
_swigt__p_SWFCXform, 
_swigt__SWFText, 
_swigt__SWFFont, 
_swigt__p_void, 
_swigt__SWFMorph, 
_swigt__SWFButton, 
_swigt__SWFBlock, 
_swigt__SWFTextField, 
_swigt__p_FILE, 
_swigt__p_SWFRect, 
_swigt__SWFFill, 
_swigt__SWFMatrix, 
_swigt__SWFSound, 
_swigt__SWFAction, 
_swigt__SWFCharacter, 
_swigt__p_int, 
_swigt__SWFBrowserFont, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

SWIGEXPORT(int) Mingc_Init(Tcl_Interp *interp) {
    int i;
    if (interp == 0) return TCL_ERROR;
    for (i = 0; swig_types_initial[i]; i++) {
        swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
    }
    for (i = 0; swig_commands[i].name; i++) {
        Tcl_CreateObjCommand(interp, (char *) swig_commands[i].name, swig_commands[i].wrapper, swig_commands[i].clientdata, NULL);
    }
    for (i = 0; swig_variables[i].name; i++) {
        Tcl_SetVar(interp, (char *) swig_variables[i].name, "", TCL_GLOBAL_ONLY);
        Tcl_TraceVar(interp, (char *) swig_variables[i].name, TCL_TRACE_READS | TCL_GLOBAL_ONLY, swig_variables[i].get, (ClientData) swig_variables[i].addr);
        Tcl_TraceVar(interp, (char *) swig_variables[i].name, TCL_TRACE_WRITES | TCL_GLOBAL_ONLY, swig_variables[i].set, (ClientData) swig_variables[i].addr);
    }
    return TCL_OK;
}

