#!/usr/bin/perl -w
# Generated by swftoperl converter included with ming. Have fun. 

# Change this to your needs. If you installed perl-ming global you don't need this.
#use lib("/home/peter/mystuff/lib/site_perl");

# We import all because our converter is not so clever to select only needed. ;-)
use SWF qw(:ALL);
# Just copy from a sample, needed to use Constants like SWFFILL_RADIAL_GRADIENT
use SWF::Constants qw(:Text :Button :DisplayItem :Fill);

$m = new SWF::Movie();


# SWF_SETBACKGROUNDCOLOR 
$m->setBackground(0xff, 0xff, 0xff);

# SWF_DEFINESPRITE 

	#  MovieClip 1 
$character1 = new SWF::MovieClip(); # 1 frames 

# SWF_SHOWFRAME 
$character1->nextFrame(); # end of clip frame 1 

# SWF_END 

# SWF_PLACEOBJECT2 
# PlaceFlagHasCharacter 
$m->add($character1);
# PlaceFlagHasMatrix 
# outputSWF_MATRIX is broken, so it is being skipped.. 

# SWF_SHOWFRAME 
$m->nextFrame(); # end of frame 1 

# SWF_END 

$m->save("test02.swf");
