/* outputscript.c */
extern char *methodcall(char *varname, char *method);
extern char *newobj(char *varname, char *obj);
extern void outputSWF_RGBA(SWF_RGBA *color, char *pname);
extern void outputSWF_MATRIX(SWF_MATRIX *matrix, char *fname);
extern void outputSWF_GRADIENT(SWF_GRADIENT *gradient, char *gname);
extern void outputSWF_FILLSTYLE(SWF_FILLSTYLE *fillstyle, char *parentname, int i);
extern void outputSWF_FILLSTYLEARRAY(SWF_FILLSTYLEARRAY *fillstylearray, char *parentname);
extern void outputSWF_LINESTYLE(SWF_LINESTYLE *linestyle, char *parentname, int i);
extern void outputSWF_LINESTYLEARRAY(SWF_LINESTYLEARRAY *linestylearray, char *parentname);
extern void outputSWF_SHAPERECORD(SWF_SHAPERECORD *shaperec, char *parentname);
extern void outputSWF_SHAPE(SWF_SHAPE *shape, char *name);
extern void outputSWF_SHAPEWITHSTYLE(SWF_SHAPEWITHSTYLE *shape, int level, char *name);
extern void outputSWF_CHARACTERSET(SWF_Parserstruct *pblock);
extern void outputSWF_DEFINEBITS(SWF_Parserstruct *pblock);
extern void outputSWF_DEFINEBITSJPEG2(SWF_Parserstruct *pblock);
extern void outputSWF_DEFINEBITSJPEG3(SWF_Parserstruct *pblock);
extern void outputSWF_DEFINEBITSPTR(SWF_Parserstruct *pblock);
extern void outputSWF_DEFINEBUTTON(SWF_Parserstruct *pblock);
extern void outputSWF_DEFINEBUTTON2(SWF_Parserstruct *pblock);
extern void outputSWF_DEFINEBUTTONCXFORM(SWF_Parserstruct *pblock);
extern void outputSWF_DEFINEBUTTONSOUND(SWF_Parserstruct *pblock);
extern void outputSWF_DEFINECOMMANDOBJ(SWF_Parserstruct *pblock);
extern void outputSWF_DEFINEEDITTEXT(SWF_Parserstruct *pblock);
extern void outputSWF_DEFINEFONT(SWF_Parserstruct *pblock);
extern void outputSWF_DEFINEFONT2(SWF_Parserstruct *pblock);
extern void outputSWF_DEFINEFONTINFO(SWF_Parserstruct *pblock);
extern void outputSWF_DEFINELOSSLESS(SWF_Parserstruct *pblock);
extern void outputSWF_DEFINELOSSLESS2(SWF_Parserstruct *pblock);
extern void outputSWF_DEFINEMORPHSHAPE(SWF_Parserstruct *pblock);
extern void outputSWF_DEFINESHAPE(SWF_Parserstruct *pblock);
extern void outputSWF_DEFINESHAPE2(SWF_Parserstruct *pblock);
extern void outputSWF_DEFINESHAPE3(SWF_Parserstruct *pblock);
extern void outputSWF_DEFINESOUND(SWF_Parserstruct *pblock);
extern void outputSWF_DEFINESPRITE(SWF_Parserstruct *pblock);
extern void outputSWF_DEFINETEXT(SWF_Parserstruct *pblock);
extern void outputSWF_DEFINETEXT2(SWF_Parserstruct *pblock);
extern void outputSWF_DEFINETEXTFORMAT(SWF_Parserstruct *pblock);
extern void outputSWF_DEFINEVIDEO(SWF_Parserstruct *pblock);
extern void outputSWF_DEFINEVIDEOSTREAM(SWF_Parserstruct *pblock);
extern void outputSWF_DOACTION(SWF_Parserstruct *pblock);
extern void outputSWF_ENABLEDEBUGGER(SWF_Parserstruct *pblock);
extern void outputSWF_END(SWF_Parserstruct *pblock);
extern void outputSWF_EXPORTASSETS(SWF_Parserstruct *pblock);
extern void outputSWF_FONTREF(SWF_Parserstruct *pblock);
extern void outputSWF_FRAMELABEL(SWF_Parserstruct *pblock);
extern void outputSWF_FRAMETAG(SWF_Parserstruct *pblock);
extern void outputSWF_FREEALL(SWF_Parserstruct *pblock);
extern void outputSWF_FREECHARACTER(SWF_Parserstruct *pblock);
extern void outputSWF_GENCOMMAND(SWF_Parserstruct *pblock);
extern void outputSWF_IMPORTASSETS(SWF_Parserstruct *pblock);
extern void outputSWF_JPEGTABLES(SWF_Parserstruct *pblock);
extern void outputSWF_NAMECHARACTER(SWF_Parserstruct *pblock);
extern void outputSWF_PATHSAREPOSTSCRIPT(SWF_Parserstruct *pblock);
extern void outputSWF_PLACEOBJECT(SWF_Parserstruct *pblock);
extern void outputSWF_PLACEOBJECT2(SWF_Parserstruct *pblock);
extern void outputSWF_PREBUILT(SWF_Parserstruct *pblock);
extern void outputSWF_PREBUILTCLIP(SWF_Parserstruct *pblock);
extern void outputSWF_PROTECT(SWF_Parserstruct *pblock);
extern void outputSWF_REMOVEOBJECT(SWF_Parserstruct *pblock);
extern void outputSWF_REMOVEOBJECT2(SWF_Parserstruct *pblock);
extern void outputSWF_SERIALNUMBER(SWF_Parserstruct *pblock);
extern void outputSWF_SETBACKGROUNDCOLOR(SWF_Parserstruct *pblock);
extern void outputSWF_SHOWFRAME(SWF_Parserstruct *pblock);
extern void outputSWF_SOUNDSTREAMBLOCK(SWF_Parserstruct *pblock);
extern void outputSWF_SOUNDSTREAMHEAD(SWF_Parserstruct *pblock);
extern void outputSWF_SOUNDSTREAMHEAD2(SWF_Parserstruct *pblock);
extern void outputSWF_STARTSOUND(SWF_Parserstruct *pblock);
extern void outputSWF_SYNCFRAME(SWF_Parserstruct *pblock);
extern void outputSWF_INITACTION(SWF_Parserstruct *pblock);
extern void outputSWF_VIDEOFRAME(SWF_Parserstruct *pblock);
extern void outputHeader(struct Movie *m);
extern void outputTrailer(struct Movie *m);
extern void outputBlock(int type, SWF_Parserstruct *blockp, FILE *stream, int offset, int lenght);
