targetPath(myTarget);
trace(targetPath(myTarget));
getUrl("test");
getUrl("test", "window");
getUrl("test", "window", "POST");
loadVariables("test", window, "POST");
loadVariablesNum("test", 1, "POST");
loadMovie("url", object);
loadMovieNum("url", object);
call(1);
startDrag(object, 1);
startDrag(object, 0, 0, 0, 200, 200);
stopDrag();
duplicateMovieClip(movie, "newMovie", 100);
duplicateMovieClip("movie", "newMovie", 100);
nextFrame();
prevFrame();
play();
stop();
toggleQuality();
gotoAndPlay(1);
gotoAndStop(1);
gotoAndPlay("here");
gotoAndStop("here");
setTarget("xx");

