# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.3
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_mingc', [dirname(__file__)])
        except ImportError:
            import _mingc
            return _mingc
        if fp is not None:
            try:
                _mod = imp.load_module('_mingc', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _mingc = swig_import_helper()
    del swig_import_helper
else:
    import _mingc
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def new_intp():
    return _mingc.new_intp()
new_intp = _mingc.new_intp

def copy_intp(value):
    return _mingc.copy_intp(value)
copy_intp = _mingc.copy_intp

def delete_intp(obj):
    return _mingc.delete_intp(obj)
delete_intp = _mingc.delete_intp

def intp_assign(obj, value):
    return _mingc.intp_assign(obj, value)
intp_assign = _mingc.intp_assign

def intp_value(obj):
    return _mingc.intp_value(obj)
intp_value = _mingc.intp_value

def new_floatp():
    return _mingc.new_floatp()
new_floatp = _mingc.new_floatp

def copy_floatp(value):
    return _mingc.copy_floatp(value)
copy_floatp = _mingc.copy_floatp

def delete_floatp(obj):
    return _mingc.delete_floatp(obj)
delete_floatp = _mingc.delete_floatp

def floatp_assign(obj, value):
    return _mingc.floatp_assign(obj, value)
floatp_assign = _mingc.floatp_assign

def floatp_value(obj):
    return _mingc.floatp_value(obj)
floatp_value = _mingc.floatp_value
class floatArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, floatArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, floatArray, name)
    __repr__ = _swig_repr

    def __init__(self, nelements):
        this = _mingc.new_floatArray(nelements)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _mingc.delete_floatArray
    __del__ = lambda self: None

    def __getitem__(self, index):
        return _mingc.floatArray___getitem__(self, index)

    def __setitem__(self, index, value):
        return _mingc.floatArray___setitem__(self, index, value)

    def cast(self):
        return _mingc.floatArray_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _mingc.floatArray_frompointer
    if _newclass:
        frompointer = staticmethod(_mingc.floatArray_frompointer)
floatArray_swigregister = _mingc.floatArray_swigregister
floatArray_swigregister(floatArray)

def floatArray_frompointer(t):
    return _mingc.floatArray_frompointer(t)
floatArray_frompointer = _mingc.floatArray_frompointer


def Ming_init():
    return _mingc.Ming_init()
Ming_init = _mingc.Ming_init

def Ming_cleanup():
    return _mingc.Ming_cleanup()
Ming_cleanup = _mingc.Ming_cleanup

def Ming_collectGarbage():
    return _mingc.Ming_collectGarbage()
Ming_collectGarbage = _mingc.Ming_collectGarbage

def Ming_useConstants(flag):
    return _mingc.Ming_useConstants(flag)
Ming_useConstants = _mingc.Ming_useConstants

def Ming_setCubicThreshold(num):
    return _mingc.Ming_setCubicThreshold(num)
Ming_setCubicThreshold = _mingc.Ming_setCubicThreshold

def Ming_setScale(scale):
    return _mingc.Ming_setScale(scale)
Ming_setScale = _mingc.Ming_setScale

def Ming_getScale():
    return _mingc.Ming_getScale()
Ming_getScale = _mingc.Ming_getScale

def Ming_useSWFVersion(version):
    return _mingc.Ming_useSWFVersion(version)
Ming_useSWFVersion = _mingc.Ming_useSWFVersion

def Ming_setSWFCompression(level):
    return _mingc.Ming_setSWFCompression(level)
Ming_setSWFCompression = _mingc.Ming_setSWFCompression

def SWFMatrix_getScaleX(m):
    return _mingc.SWFMatrix_getScaleX(m)
SWFMatrix_getScaleX = _mingc.SWFMatrix_getScaleX

def SWFMatrix_getRotate0(m):
    return _mingc.SWFMatrix_getRotate0(m)
SWFMatrix_getRotate0 = _mingc.SWFMatrix_getRotate0

def SWFMatrix_getRotate1(m):
    return _mingc.SWFMatrix_getRotate1(m)
SWFMatrix_getRotate1 = _mingc.SWFMatrix_getRotate1

def SWFMatrix_getScaleY(m):
    return _mingc.SWFMatrix_getScaleY(m)
SWFMatrix_getScaleY = _mingc.SWFMatrix_getScaleY

def SWFMatrix_getTranslateX(m):
    return _mingc.SWFMatrix_getTranslateX(m)
SWFMatrix_getTranslateX = _mingc.SWFMatrix_getTranslateX

def SWFMatrix_getTranslateY(m):
    return _mingc.SWFMatrix_getTranslateY(m)
SWFMatrix_getTranslateY = _mingc.SWFMatrix_getTranslateY

def newSWFInput_file(f):
    return _mingc.newSWFInput_file(f)
newSWFInput_file = _mingc.newSWFInput_file

def newSWFInput_stream(f):
    return _mingc.newSWFInput_stream(f)
newSWFInput_stream = _mingc.newSWFInput_stream

def newSWFInput_buffer(buffer, length):
    return _mingc.newSWFInput_buffer(buffer, length)
newSWFInput_buffer = _mingc.newSWFInput_buffer

def newSWFInput_allocedBuffer(buffer, length):
    return _mingc.newSWFInput_allocedBuffer(buffer, length)
newSWFInput_allocedBuffer = _mingc.newSWFInput_allocedBuffer

def destroySWFInput(input):
    return _mingc.destroySWFInput(input)
destroySWFInput = _mingc.destroySWFInput

def SWFInput_length(input):
    return _mingc.SWFInput_length(input)
SWFInput_length = _mingc.SWFInput_length

def SWFInput_rewind(input):
    return _mingc.SWFInput_rewind(input)
SWFInput_rewind = _mingc.SWFInput_rewind

def SWFInput_tell(input):
    return _mingc.SWFInput_tell(input)
SWFInput_tell = _mingc.SWFInput_tell

def SWFInput_seek(input, offset, whence):
    return _mingc.SWFInput_seek(input, offset, whence)
SWFInput_seek = _mingc.SWFInput_seek

def SWFInput_eof(input):
    return _mingc.SWFInput_eof(input)
SWFInput_eof = _mingc.SWFInput_eof

def SWFCharacter_getWidth(character):
    return _mingc.SWFCharacter_getWidth(character)
SWFCharacter_getWidth = _mingc.SWFCharacter_getWidth

def SWFCharacter_getHeight(character):
    return _mingc.SWFCharacter_getHeight(character)
SWFCharacter_getHeight = _mingc.SWFCharacter_getHeight

def newSWFBitmap_fromInput(input):
    return _mingc.newSWFBitmap_fromInput(input)
newSWFBitmap_fromInput = _mingc.newSWFBitmap_fromInput

def destroySWFBitmap(bitmap):
    return _mingc.destroySWFBitmap(bitmap)
destroySWFBitmap = _mingc.destroySWFBitmap

def SWFBitmap_getWidth(b):
    return _mingc.SWFBitmap_getWidth(b)
SWFBitmap_getWidth = _mingc.SWFBitmap_getWidth

def SWFBitmap_getHeight(b):
    return _mingc.SWFBitmap_getHeight(b)
SWFBitmap_getHeight = _mingc.SWFBitmap_getHeight

def newSWFDBLBitmap(f):
    return _mingc.newSWFDBLBitmap(f)
newSWFDBLBitmap = _mingc.newSWFDBLBitmap

def newSWFDBLBitmap_fromInput(input):
    return _mingc.newSWFDBLBitmap_fromInput(input)
newSWFDBLBitmap_fromInput = _mingc.newSWFDBLBitmap_fromInput

def newSWFJpegBitmap(f):
    return _mingc.newSWFJpegBitmap(f)
newSWFJpegBitmap = _mingc.newSWFJpegBitmap

def newSWFJpegBitmap_fromInput(input):
    return _mingc.newSWFJpegBitmap_fromInput(input)
newSWFJpegBitmap_fromInput = _mingc.newSWFJpegBitmap_fromInput

def newSWFJpegWithAlpha(f, alpha):
    return _mingc.newSWFJpegWithAlpha(f, alpha)
newSWFJpegWithAlpha = _mingc.newSWFJpegWithAlpha

def newSWFJpegWithAlpha_fromInput(input, alpha):
    return _mingc.newSWFJpegWithAlpha_fromInput(input, alpha)
newSWFJpegWithAlpha_fromInput = _mingc.newSWFJpegWithAlpha_fromInput
SWF_GRADIENT_PAD = _mingc.SWF_GRADIENT_PAD
SWF_GRADIENT_REFLECT = _mingc.SWF_GRADIENT_REFLECT
SWF_GRADIENT_REPEAT = _mingc.SWF_GRADIENT_REPEAT
SWF_GRADIENT_NORMAL = _mingc.SWF_GRADIENT_NORMAL
SWF_GRADIENT_LINEAR = _mingc.SWF_GRADIENT_LINEAR

def newSWFGradient():
    return _mingc.newSWFGradient()
newSWFGradient = _mingc.newSWFGradient

def destroySWFGradient(gradient):
    return _mingc.destroySWFGradient(gradient)
destroySWFGradient = _mingc.destroySWFGradient

def SWFGradient_addEntry(gradient, ratio, r, g, b, a):
    return _mingc.SWFGradient_addEntry(gradient, ratio, r, g, b, a)
SWFGradient_addEntry = _mingc.SWFGradient_addEntry

def SWFGradient_setSpreadMode(gradient, mode):
    return _mingc.SWFGradient_setSpreadMode(gradient, mode)
SWFGradient_setSpreadMode = _mingc.SWFGradient_setSpreadMode

def SWFGradient_setInterpolationMode(gradient, mode):
    return _mingc.SWFGradient_setInterpolationMode(gradient, mode)
SWFGradient_setInterpolationMode = _mingc.SWFGradient_setInterpolationMode

def SWFGradient_setFocalPoint(gradient, focalPoint):
    return _mingc.SWFGradient_setFocalPoint(gradient, focalPoint)
SWFGradient_setFocalPoint = _mingc.SWFGradient_setFocalPoint
SWFFILL_SOLID = _mingc.SWFFILL_SOLID
SWFFILL_GRADIENT = _mingc.SWFFILL_GRADIENT
SWFFILL_LINEAR_GRADIENT = _mingc.SWFFILL_LINEAR_GRADIENT
SWFFILL_RADIAL_GRADIENT = _mingc.SWFFILL_RADIAL_GRADIENT
SWFFILL_BITMAP = _mingc.SWFFILL_BITMAP
SWFFILL_TILED_BITMAP = _mingc.SWFFILL_TILED_BITMAP
SWFFILL_CLIPPED_BITMAP = _mingc.SWFFILL_CLIPPED_BITMAP

def newSWFSolidFillStyle(r, g, b, a):
    return _mingc.newSWFSolidFillStyle(r, g, b, a)
newSWFSolidFillStyle = _mingc.newSWFSolidFillStyle

def newSWFGradientFillStyle(gradient, radial):
    return _mingc.newSWFGradientFillStyle(gradient, radial)
newSWFGradientFillStyle = _mingc.newSWFGradientFillStyle

def newSWFBitmapFillStyle(bitmap, flags):
    return _mingc.newSWFBitmapFillStyle(bitmap, flags)
newSWFBitmapFillStyle = _mingc.newSWFBitmapFillStyle

def SWFFillStyle_getMatrix(fill):
    return _mingc.SWFFillStyle_getMatrix(fill)
SWFFillStyle_getMatrix = _mingc.SWFFillStyle_getMatrix

def newSWFLineStyle(width, r, g, b, a):
    return _mingc.newSWFLineStyle(width, r, g, b, a)
newSWFLineStyle = _mingc.newSWFLineStyle
SWF_LINESTYLE_CAP_ROUND = _mingc.SWF_LINESTYLE_CAP_ROUND
SWF_LINESTYLE_CAP_NONE = _mingc.SWF_LINESTYLE_CAP_NONE
SWF_LINESTYLE_CAP_SQUARE = _mingc.SWF_LINESTYLE_CAP_SQUARE
SWF_LINESTYLE_JOIN_ROUND = _mingc.SWF_LINESTYLE_JOIN_ROUND
SWF_LINESTYLE_JOIN_BEVEL = _mingc.SWF_LINESTYLE_JOIN_BEVEL
SWF_LINESTYLE_JOIN_MITER = _mingc.SWF_LINESTYLE_JOIN_MITER
SWF_LINESTYLE_FLAG_NOHSCALE = _mingc.SWF_LINESTYLE_FLAG_NOHSCALE
SWF_LINESTYLE_FLAG_NOVSCALE = _mingc.SWF_LINESTYLE_FLAG_NOVSCALE
SWF_LINESTYLE_FLAG_HINTING = _mingc.SWF_LINESTYLE_FLAG_HINTING
SWF_LINESTYLE_FLAG_NOCLOSE = _mingc.SWF_LINESTYLE_FLAG_NOCLOSE
SWF_LINESTYLE_FLAG_ENDCAP_ROUND = _mingc.SWF_LINESTYLE_FLAG_ENDCAP_ROUND
SWF_LINESTYLE_FLAG_ENDCAP_NONE = _mingc.SWF_LINESTYLE_FLAG_ENDCAP_NONE
SWF_LINESTYLE_FLAG_ENDCAP_SQUARE = _mingc.SWF_LINESTYLE_FLAG_ENDCAP_SQUARE

def newSWFLineStyle2(width, r, g, b, a, flags, miterLimit):
    return _mingc.newSWFLineStyle2(width, r, g, b, a, flags, miterLimit)
newSWFLineStyle2 = _mingc.newSWFLineStyle2

def newSWFLineStyle2_filled(width, fill, flags, miterLimit):
    return _mingc.newSWFLineStyle2_filled(width, fill, flags, miterLimit)
newSWFLineStyle2_filled = _mingc.newSWFLineStyle2_filled
SWF_SHAPE3 = _mingc.SWF_SHAPE3
SWF_SHAPE4 = _mingc.SWF_SHAPE4
SWF_SHAPE_USESCALINGSTROKES = _mingc.SWF_SHAPE_USESCALINGSTROKES
SWF_SHAPE_USENONSCALINGSTROKES = _mingc.SWF_SHAPE_USENONSCALINGSTROKES

def newSWFShape():
    return _mingc.newSWFShape()
newSWFShape = _mingc.newSWFShape

def newSWFShapeFromBitmap(bitmap, flag):
    return _mingc.newSWFShapeFromBitmap(bitmap, flag)
newSWFShapeFromBitmap = _mingc.newSWFShapeFromBitmap

def destroySWFShape(shape):
    return _mingc.destroySWFShape(shape)
destroySWFShape = _mingc.destroySWFShape

def SWFShape_end(shape):
    return _mingc.SWFShape_end(shape)
SWFShape_end = _mingc.SWFShape_end

def SWFShape_useVersion(shape, version):
    return _mingc.SWFShape_useVersion(shape, version)
SWFShape_useVersion = _mingc.SWFShape_useVersion

def SWFShape_getVersion(shape):
    return _mingc.SWFShape_getVersion(shape)
SWFShape_getVersion = _mingc.SWFShape_getVersion

def SWFShape_setRenderHintingFlags(shape, flags):
    return _mingc.SWFShape_setRenderHintingFlags(shape, flags)
SWFShape_setRenderHintingFlags = _mingc.SWFShape_setRenderHintingFlags

def SWFShape_movePenTo(shape, x, y):
    return _mingc.SWFShape_movePenTo(shape, x, y)
SWFShape_movePenTo = _mingc.SWFShape_movePenTo

def SWFShape_movePen(shape, x, y):
    return _mingc.SWFShape_movePen(shape, x, y)
SWFShape_movePen = _mingc.SWFShape_movePen

def SWFShape_getPenX(shape):
    return _mingc.SWFShape_getPenX(shape)
SWFShape_getPenX = _mingc.SWFShape_getPenX

def SWFShape_getPenY(shape):
    return _mingc.SWFShape_getPenY(shape)
SWFShape_getPenY = _mingc.SWFShape_getPenY

def SWFShape_getPen(shape, penX, penY):
    return _mingc.SWFShape_getPen(shape, penX, penY)
SWFShape_getPen = _mingc.SWFShape_getPen

def SWFShape_drawLineTo(shape, x, y):
    return _mingc.SWFShape_drawLineTo(shape, x, y)
SWFShape_drawLineTo = _mingc.SWFShape_drawLineTo

def SWFShape_drawLine(shape, dx, dy):
    return _mingc.SWFShape_drawLine(shape, dx, dy)
SWFShape_drawLine = _mingc.SWFShape_drawLine

def SWFShape_drawCurveTo(shape, controlx, controly, anchorx, anchory):
    return _mingc.SWFShape_drawCurveTo(shape, controlx, controly, anchorx, anchory)
SWFShape_drawCurveTo = _mingc.SWFShape_drawCurveTo

def SWFShape_drawCurve(shape, controldx, controldy, anchordx, anchordy):
    return _mingc.SWFShape_drawCurve(shape, controldx, controldy, anchordx, anchordy)
SWFShape_drawCurve = _mingc.SWFShape_drawCurve

def SWFShape_hideLine(shape):
    return _mingc.SWFShape_hideLine(shape)
SWFShape_hideLine = _mingc.SWFShape_hideLine

def SWFShape_addSolidFillStyle(shape, r, g, b, a):
    return _mingc.SWFShape_addSolidFillStyle(shape, r, g, b, a)
SWFShape_addSolidFillStyle = _mingc.SWFShape_addSolidFillStyle

def SWFShape_addGradientFillStyle(shape, gradient, flags):
    return _mingc.SWFShape_addGradientFillStyle(shape, gradient, flags)
SWFShape_addGradientFillStyle = _mingc.SWFShape_addGradientFillStyle

def SWFShape_addBitmapFillStyle(shape, bitmap, flags):
    return _mingc.SWFShape_addBitmapFillStyle(shape, bitmap, flags)
SWFShape_addBitmapFillStyle = _mingc.SWFShape_addBitmapFillStyle

def SWFShape_setLeftFillStyle(shape, fill):
    return _mingc.SWFShape_setLeftFillStyle(shape, fill)
SWFShape_setLeftFillStyle = _mingc.SWFShape_setLeftFillStyle

def SWFShape_setRightFillStyle(shape, fill):
    return _mingc.SWFShape_setRightFillStyle(shape, fill)
SWFShape_setRightFillStyle = _mingc.SWFShape_setRightFillStyle

def newSWFMorphShape():
    return _mingc.newSWFMorphShape()
newSWFMorphShape = _mingc.newSWFMorphShape

def destroySWFMorph(morph):
    return _mingc.destroySWFMorph(morph)
destroySWFMorph = _mingc.destroySWFMorph

def SWFMorph_getShape1(morph):
    return _mingc.SWFMorph_getShape1(morph)
SWFMorph_getShape1 = _mingc.SWFMorph_getShape1

def SWFMorph_getShape2(morph):
    return _mingc.SWFMorph_getShape2(morph)
SWFMorph_getShape2 = _mingc.SWFMorph_getShape2

def newSWFFont_fromFile(filename):
    return _mingc.newSWFFont_fromFile(filename)
newSWFFont_fromFile = _mingc.newSWFFont_fromFile

def destroySWFFont(font):
    return _mingc.destroySWFFont(font)
destroySWFFont = _mingc.destroySWFFont

def SWFFont_getStringWidth(font, string):
    return _mingc.SWFFont_getStringWidth(font, string)
SWFFont_getStringWidth = _mingc.SWFFont_getStringWidth

def SWFFont_getUTF8StringWidth(font, string):
    return _mingc.SWFFont_getUTF8StringWidth(font, string)
SWFFont_getUTF8StringWidth = _mingc.SWFFont_getUTF8StringWidth

def SWFFont_getWideStringWidth(font, string, len):
    return _mingc.SWFFont_getWideStringWidth(font, string, len)
SWFFont_getWideStringWidth = _mingc.SWFFont_getWideStringWidth

def SWFFont_getAscent(font):
    return _mingc.SWFFont_getAscent(font)
SWFFont_getAscent = _mingc.SWFFont_getAscent

def SWFFont_getDescent(font):
    return _mingc.SWFFont_getDescent(font)
SWFFont_getDescent = _mingc.SWFFont_getDescent

def SWFFont_getLeading(font):
    return _mingc.SWFFont_getLeading(font)
SWFFont_getLeading = _mingc.SWFFont_getLeading

def SWFFont_getName(font):
    return _mingc.SWFFont_getName(font)
SWFFont_getName = _mingc.SWFFont_getName

def SWFFont_getGlyphCount(font):
    return _mingc.SWFFont_getGlyphCount(font)
SWFFont_getGlyphCount = _mingc.SWFFont_getGlyphCount

def newSWFFontCollection_fromFile(filename):
    return _mingc.newSWFFontCollection_fromFile(filename)
newSWFFontCollection_fromFile = _mingc.newSWFFontCollection_fromFile

def SWFFontCollection_getFontCount(collection):
    return _mingc.SWFFontCollection_getFontCount(collection)
SWFFontCollection_getFontCount = _mingc.SWFFontCollection_getFontCount

def SWFFontCollection_getFont(collection, index):
    return _mingc.SWFFontCollection_getFont(collection, index)
SWFFontCollection_getFont = _mingc.SWFFontCollection_getFont

def destroySWFFontCollection(collection):
    return _mingc.destroySWFFontCollection(collection)
destroySWFFontCollection = _mingc.destroySWFFontCollection

def newSWFText():
    return _mingc.newSWFText()
newSWFText = _mingc.newSWFText

def newSWFText2():
    return _mingc.newSWFText2()
newSWFText2 = _mingc.newSWFText2

def destroySWFText(text):
    return _mingc.destroySWFText(text)
destroySWFText = _mingc.destroySWFText

def SWFText_setFont(text, font):
    return _mingc.SWFText_setFont(text, font)
SWFText_setFont = _mingc.SWFText_setFont

def SWFText_setHeight(text, height):
    return _mingc.SWFText_setHeight(text, height)
SWFText_setHeight = _mingc.SWFText_setHeight

def SWFText_setColor(text, r, g, b, a):
    return _mingc.SWFText_setColor(text, r, g, b, a)
SWFText_setColor = _mingc.SWFText_setColor

def SWFText_moveTo(text, x, y):
    return _mingc.SWFText_moveTo(text, x, y)
SWFText_moveTo = _mingc.SWFText_moveTo

def SWFText_addString(text, string, advance):
    return _mingc.SWFText_addString(text, string, advance)
SWFText_addString = _mingc.SWFText_addString

def SWFText_addUTF8String(text, string, advance):
    return _mingc.SWFText_addUTF8String(text, string, advance)
SWFText_addUTF8String = _mingc.SWFText_addUTF8String

def SWFText_addWideString(text, string, strlen, advance):
    return _mingc.SWFText_addWideString(text, string, strlen, advance)
SWFText_addWideString = _mingc.SWFText_addWideString

def SWFText_setSpacing(text, spacing):
    return _mingc.SWFText_setSpacing(text, spacing)
SWFText_setSpacing = _mingc.SWFText_setSpacing

def SWFText_getStringWidth(text, string):
    return _mingc.SWFText_getStringWidth(text, string)
SWFText_getStringWidth = _mingc.SWFText_getStringWidth

def SWFText_getUTF8StringWidth(text, string):
    return _mingc.SWFText_getUTF8StringWidth(text, string)
SWFText_getUTF8StringWidth = _mingc.SWFText_getUTF8StringWidth

def SWFText_getWideStringWidth(text, string):
    return _mingc.SWFText_getWideStringWidth(text, string)
SWFText_getWideStringWidth = _mingc.SWFText_getWideStringWidth

def SWFText_getAscent(text):
    return _mingc.SWFText_getAscent(text)
SWFText_getAscent = _mingc.SWFText_getAscent

def SWFText_getDescent(text):
    return _mingc.SWFText_getDescent(text)
SWFText_getDescent = _mingc.SWFText_getDescent

def SWFText_getLeading(text):
    return _mingc.SWFText_getLeading(text)
SWFText_getLeading = _mingc.SWFText_getLeading

def newSWFBrowserFont(name):
    return _mingc.newSWFBrowserFont(name)
newSWFBrowserFont = _mingc.newSWFBrowserFont

def destroySWFBrowserFont(browserFont):
    return _mingc.destroySWFBrowserFont(browserFont)
destroySWFBrowserFont = _mingc.destroySWFBrowserFont

def SWFFontCharacter_addChars(font, string):
    return _mingc.SWFFontCharacter_addChars(font, string)
SWFFontCharacter_addChars = _mingc.SWFFontCharacter_addChars

def SWFFontCharacter_addUTF8Chars(font, string):
    return _mingc.SWFFontCharacter_addUTF8Chars(font, string)
SWFFontCharacter_addUTF8Chars = _mingc.SWFFontCharacter_addUTF8Chars
SWFTEXTFIELD_ONMASK = _mingc.SWFTEXTFIELD_ONMASK
SWFTEXTFIELD_OFFMASK = _mingc.SWFTEXTFIELD_OFFMASK
SWFTEXTFIELD_HASFONT = _mingc.SWFTEXTFIELD_HASFONT
SWFTEXTFIELD_HASLENGTH = _mingc.SWFTEXTFIELD_HASLENGTH
SWFTEXTFIELD_HASCOLOR = _mingc.SWFTEXTFIELD_HASCOLOR
SWFTEXTFIELD_NOEDIT = _mingc.SWFTEXTFIELD_NOEDIT
SWFTEXTFIELD_PASSWORD = _mingc.SWFTEXTFIELD_PASSWORD
SWFTEXTFIELD_MULTILINE = _mingc.SWFTEXTFIELD_MULTILINE
SWFTEXTFIELD_WORDWRAP = _mingc.SWFTEXTFIELD_WORDWRAP
SWFTEXTFIELD_HASTEXT = _mingc.SWFTEXTFIELD_HASTEXT
SWFTEXTFIELD_USEFONT = _mingc.SWFTEXTFIELD_USEFONT
SWFTEXTFIELD_HTML = _mingc.SWFTEXTFIELD_HTML
SWFTEXTFIELD_DRAWBOX = _mingc.SWFTEXTFIELD_DRAWBOX
SWFTEXTFIELD_NOSELECT = _mingc.SWFTEXTFIELD_NOSELECT
SWFTEXTFIELD_HASLAYOUT = _mingc.SWFTEXTFIELD_HASLAYOUT
SWFTEXTFIELD_AUTOSIZE = _mingc.SWFTEXTFIELD_AUTOSIZE
SWFTEXTFIELD_ALIGN_LEFT = _mingc.SWFTEXTFIELD_ALIGN_LEFT
SWFTEXTFIELD_ALIGN_RIGHT = _mingc.SWFTEXTFIELD_ALIGN_RIGHT
SWFTEXTFIELD_ALIGN_CENTER = _mingc.SWFTEXTFIELD_ALIGN_CENTER
SWFTEXTFIELD_ALIGN_JUSTIFY = _mingc.SWFTEXTFIELD_ALIGN_JUSTIFY

def newSWFTextField():
    return _mingc.newSWFTextField()
newSWFTextField = _mingc.newSWFTextField

def destroySWFTextField(textField):
    return _mingc.destroySWFTextField(textField)
destroySWFTextField = _mingc.destroySWFTextField

def SWFTextField_setFont(field, font):
    return _mingc.SWFTextField_setFont(field, font)
SWFTextField_setFont = _mingc.SWFTextField_setFont

def SWFTextField_setBounds(field, width, height):
    return _mingc.SWFTextField_setBounds(field, width, height)
SWFTextField_setBounds = _mingc.SWFTextField_setBounds

def SWFTextField_setFlags(field, flags):
    return _mingc.SWFTextField_setFlags(field, flags)
SWFTextField_setFlags = _mingc.SWFTextField_setFlags

def SWFTextField_setColor(field, r, g, b, a):
    return _mingc.SWFTextField_setColor(field, r, g, b, a)
SWFTextField_setColor = _mingc.SWFTextField_setColor

def SWFTextField_setVariableName(field, name):
    return _mingc.SWFTextField_setVariableName(field, name)
SWFTextField_setVariableName = _mingc.SWFTextField_setVariableName

def SWFTextField_addString(field, string):
    return _mingc.SWFTextField_addString(field, string)
SWFTextField_addString = _mingc.SWFTextField_addString

def SWFTextField_addUTF8String(field, string):
    return _mingc.SWFTextField_addUTF8String(field, string)
SWFTextField_addUTF8String = _mingc.SWFTextField_addUTF8String

def SWFTextField_setHeight(field, height):
    return _mingc.SWFTextField_setHeight(field, height)
SWFTextField_setHeight = _mingc.SWFTextField_setHeight

def SWFTextField_setFieldHeight(field, height):
    return _mingc.SWFTextField_setFieldHeight(field, height)
SWFTextField_setFieldHeight = _mingc.SWFTextField_setFieldHeight

def SWFTextField_setLeftMargin(field, leftMargin):
    return _mingc.SWFTextField_setLeftMargin(field, leftMargin)
SWFTextField_setLeftMargin = _mingc.SWFTextField_setLeftMargin

def SWFTextField_setRightMargin(field, rightMargin):
    return _mingc.SWFTextField_setRightMargin(field, rightMargin)
SWFTextField_setRightMargin = _mingc.SWFTextField_setRightMargin

def SWFTextField_setIndentation(field, indentation):
    return _mingc.SWFTextField_setIndentation(field, indentation)
SWFTextField_setIndentation = _mingc.SWFTextField_setIndentation

def SWFTextField_setLineSpacing(field, lineSpacing):
    return _mingc.SWFTextField_setLineSpacing(field, lineSpacing)
SWFTextField_setLineSpacing = _mingc.SWFTextField_setLineSpacing

def SWFTextField_setPadding(field, padding):
    return _mingc.SWFTextField_setPadding(field, padding)
SWFTextField_setPadding = _mingc.SWFTextField_setPadding

def SWFTextField_addChars(field, string):
    return _mingc.SWFTextField_addChars(field, string)
SWFTextField_addChars = _mingc.SWFTextField_addChars

def SWFTextField_setAlignment(field, alignment):
    return _mingc.SWFTextField_setAlignment(field, alignment)
SWFTextField_setAlignment = _mingc.SWFTextField_setAlignment

def SWFTextField_setLength(field, length):
    return _mingc.SWFTextField_setLength(field, length)
SWFTextField_setLength = _mingc.SWFTextField_setLength

def newSWFSoundStream(file):
    return _mingc.newSWFSoundStream(file)
newSWFSoundStream = _mingc.newSWFSoundStream

def newSWFSoundStreamFromFileno(fd):
    return _mingc.newSWFSoundStreamFromFileno(fd)
newSWFSoundStreamFromFileno = _mingc.newSWFSoundStreamFromFileno

def newSWFSoundStream_fromInput(input):
    return _mingc.newSWFSoundStream_fromInput(input)
newSWFSoundStream_fromInput = _mingc.newSWFSoundStream_fromInput

def destroySWFSoundStream(soundStream):
    return _mingc.destroySWFSoundStream(soundStream)
destroySWFSoundStream = _mingc.destroySWFSoundStream

def SWFSoundStream_getDuration(arg1):
    return _mingc.SWFSoundStream_getDuration(arg1)
SWFSoundStream_getDuration = _mingc.SWFSoundStream_getDuration

def SWFSoundStream_setInitialMp3Delay(soundStream, delay):
    return _mingc.SWFSoundStream_setInitialMp3Delay(soundStream, delay)
SWFSoundStream_setInitialMp3Delay = _mingc.SWFSoundStream_setInitialMp3Delay

def newSWFSound(file, flags):
    return _mingc.newSWFSound(file, flags)
newSWFSound = _mingc.newSWFSound

def newSWFSoundFromFileno(fd, flags):
    return _mingc.newSWFSoundFromFileno(fd, flags)
newSWFSoundFromFileno = _mingc.newSWFSoundFromFileno

def newSWFSound_fromInput(input, flags):
    return _mingc.newSWFSound_fromInput(input, flags)
newSWFSound_fromInput = _mingc.newSWFSound_fromInput

def newSWFSound_fromSoundStream(stream):
    return _mingc.newSWFSound_fromSoundStream(stream)
newSWFSound_fromSoundStream = _mingc.newSWFSound_fromSoundStream

def destroySWFSound(sound):
    return _mingc.destroySWFSound(sound)
destroySWFSound = _mingc.destroySWFSound

def SWFSound_setInitialMp3Delay(sound, delay):
    return _mingc.SWFSound_setInitialMp3Delay(sound, delay)
SWFSound_setInitialMp3Delay = _mingc.SWFSound_setInitialMp3Delay
SWF_SOUND_COMPRESSION = _mingc.SWF_SOUND_COMPRESSION
SWF_SOUND_NOT_COMPRESSED = _mingc.SWF_SOUND_NOT_COMPRESSED
SWF_SOUND_ADPCM_COMPRESSED = _mingc.SWF_SOUND_ADPCM_COMPRESSED
SWF_SOUND_MP3_COMPRESSED = _mingc.SWF_SOUND_MP3_COMPRESSED
SWF_SOUND_NOT_COMPRESSED_LE = _mingc.SWF_SOUND_NOT_COMPRESSED_LE
SWF_SOUND_NELLY_COMPRESSED = _mingc.SWF_SOUND_NELLY_COMPRESSED
SWF_SOUND_RATE = _mingc.SWF_SOUND_RATE
SWF_SOUND_5KHZ = _mingc.SWF_SOUND_5KHZ
SWF_SOUND_11KHZ = _mingc.SWF_SOUND_11KHZ
SWF_SOUND_22KHZ = _mingc.SWF_SOUND_22KHZ
SWF_SOUND_44KHZ = _mingc.SWF_SOUND_44KHZ
SWF_SOUND_BITS = _mingc.SWF_SOUND_BITS
SWF_SOUND_8BITS = _mingc.SWF_SOUND_8BITS
SWF_SOUND_16BITS = _mingc.SWF_SOUND_16BITS
SWF_SOUND_CHANNELS = _mingc.SWF_SOUND_CHANNELS
SWF_SOUND_MONO = _mingc.SWF_SOUND_MONO
SWF_SOUND_STEREO = _mingc.SWF_SOUND_STEREO

def SWFSoundInstance_setLoopInPoint(instance, point):
    return _mingc.SWFSoundInstance_setLoopInPoint(instance, point)
SWFSoundInstance_setLoopInPoint = _mingc.SWFSoundInstance_setLoopInPoint

def SWFSoundInstance_setLoopOutPoint(instance, point):
    return _mingc.SWFSoundInstance_setLoopOutPoint(instance, point)
SWFSoundInstance_setLoopOutPoint = _mingc.SWFSoundInstance_setLoopOutPoint

def SWFSoundInstance_setLoopCount(instance, count):
    return _mingc.SWFSoundInstance_setLoopCount(instance, count)
SWFSoundInstance_setLoopCount = _mingc.SWFSoundInstance_setLoopCount

def SWFSoundInstance_setNoMultiple(instance):
    return _mingc.SWFSoundInstance_setNoMultiple(instance)
SWFSoundInstance_setNoMultiple = _mingc.SWFSoundInstance_setNoMultiple

def newSWFCXform(rAdd, gAdd, bAdd, aAdd, rMult, gMult, bMult, aMult):
    return _mingc.newSWFCXform(rAdd, gAdd, bAdd, aAdd, rMult, gMult, bMult, aMult)
newSWFCXform = _mingc.newSWFCXform

def newSWFAddCXform(rAdd, gAdd, bAdd, aAdd):
    return _mingc.newSWFAddCXform(rAdd, gAdd, bAdd, aAdd)
newSWFAddCXform = _mingc.newSWFAddCXform

def newSWFMultCXform(rMult, gMult, bMult, aMult):
    return _mingc.newSWFMultCXform(rMult, gMult, bMult, aMult)
newSWFMultCXform = _mingc.newSWFMultCXform

def destroySWFCXform(cXform):
    return _mingc.destroySWFCXform(cXform)
destroySWFCXform = _mingc.destroySWFCXform

def SWFCXform_setColorAdd(cXform, rAdd, gAdd, bAdd, aAdd):
    return _mingc.SWFCXform_setColorAdd(cXform, rAdd, gAdd, bAdd, aAdd)
SWFCXform_setColorAdd = _mingc.SWFCXform_setColorAdd

def SWFCXform_setColorMult(cXform, rMult, gMult, bMult, aMult):
    return _mingc.SWFCXform_setColorMult(cXform, rMult, gMult, bMult, aMult)
SWFCXform_setColorMult = _mingc.SWFCXform_setColorMult

def newSWFAction(script):
    return _mingc.newSWFAction(script)
newSWFAction = _mingc.newSWFAction

def newSWFAction_fromFile(filename):
    return _mingc.newSWFAction_fromFile(filename)
newSWFAction_fromFile = _mingc.newSWFAction_fromFile

def SWFAction_compile(action, swfVersion, length):
    return _mingc.SWFAction_compile(action, swfVersion, length)
SWFAction_compile = _mingc.SWFAction_compile

def destroySWFAction(action):
    return _mingc.destroySWFAction(action)
destroySWFAction = _mingc.destroySWFAction

def SWFAction_getByteCode(action, length):
    return _mingc.SWFAction_getByteCode(action, length)
SWFAction_getByteCode = _mingc.SWFAction_getByteCode

def newSWFInitAction(action):
    return _mingc.newSWFInitAction(action)
newSWFInitAction = _mingc.newSWFInitAction

def newSWFInitAction_withId(action, id):
    return _mingc.newSWFInitAction_withId(action, id)
newSWFInitAction_withId = _mingc.newSWFInitAction_withId
SWFBUTTON_HIT = _mingc.SWFBUTTON_HIT
SWFBUTTON_DOWN = _mingc.SWFBUTTON_DOWN
SWFBUTTON_OVER = _mingc.SWFBUTTON_OVER
SWFBUTTON_UP = _mingc.SWFBUTTON_UP
SWFBUTTONRECORD_HITSTATE = _mingc.SWFBUTTONRECORD_HITSTATE
SWFBUTTONRECORD_DOWNSTATE = _mingc.SWFBUTTONRECORD_DOWNSTATE
SWFBUTTONRECORD_OVERSTATE = _mingc.SWFBUTTONRECORD_OVERSTATE
SWFBUTTONRECORD_UPSTATE = _mingc.SWFBUTTONRECORD_UPSTATE
SWFBUTTON_OVERDOWNTOIDLE = _mingc.SWFBUTTON_OVERDOWNTOIDLE
SWFBUTTON_IDLETOOVERDOWN = _mingc.SWFBUTTON_IDLETOOVERDOWN
SWFBUTTON_OUTDOWNTOIDLE = _mingc.SWFBUTTON_OUTDOWNTOIDLE
SWFBUTTON_OUTDOWNTOOVERDOWN = _mingc.SWFBUTTON_OUTDOWNTOOVERDOWN
SWFBUTTON_OVERDOWNTOOUTDOWN = _mingc.SWFBUTTON_OVERDOWNTOOUTDOWN
SWFBUTTON_OVERDOWNTOOVERUP = _mingc.SWFBUTTON_OVERDOWNTOOVERUP
SWFBUTTON_OVERUPTOOVERDOWN = _mingc.SWFBUTTON_OVERUPTOOVERDOWN
SWFBUTTON_OVERUPTOIDLE = _mingc.SWFBUTTON_OVERUPTOIDLE
SWFBUTTON_IDLETOOVERUP = _mingc.SWFBUTTON_IDLETOOVERUP
SWFBUTTON_MOUSEUPOUTSIDE = _mingc.SWFBUTTON_MOUSEUPOUTSIDE
SWFBUTTON_DRAGOVER = _mingc.SWFBUTTON_DRAGOVER
SWFBUTTON_DRAGOUT = _mingc.SWFBUTTON_DRAGOUT
SWFBUTTON_MOUSEUP = _mingc.SWFBUTTON_MOUSEUP
SWFBUTTON_MOUSEDOWN = _mingc.SWFBUTTON_MOUSEDOWN
SWFBUTTON_MOUSEOUT = _mingc.SWFBUTTON_MOUSEOUT
SWFBUTTON_MOUSEOVER = _mingc.SWFBUTTON_MOUSEOVER

def newSWFButton():
    return _mingc.newSWFButton()
newSWFButton = _mingc.newSWFButton

def destroySWFButton(button):
    return _mingc.destroySWFButton(button)
destroySWFButton = _mingc.destroySWFButton

def SWFButton_addCharacter(arg1, arg2, flags):
    return _mingc.SWFButton_addCharacter(arg1, arg2, flags)
SWFButton_addCharacter = _mingc.SWFButton_addCharacter

def SWFButton_addAction(button, action, flags):
    return _mingc.SWFButton_addAction(button, action, flags)
SWFButton_addAction = _mingc.SWFButton_addAction

def SWFButton_addSound(button, action, flags):
    return _mingc.SWFButton_addSound(button, action, flags)
SWFButton_addSound = _mingc.SWFButton_addSound

def SWFButton_setMenu(button, flag):
    return _mingc.SWFButton_setMenu(button, flag)
SWFButton_setMenu = _mingc.SWFButton_setMenu

def SWFButton_setScalingGrid(b, x, y, w, h):
    return _mingc.SWFButton_setScalingGrid(b, x, y, w, h)
SWFButton_setScalingGrid = _mingc.SWFButton_setScalingGrid

def SWFButton_removeScalingGrid(b):
    return _mingc.SWFButton_removeScalingGrid(b)
SWFButton_removeScalingGrid = _mingc.SWFButton_removeScalingGrid

def SWFButtonRecord_setDepth(b, depth):
    return _mingc.SWFButtonRecord_setDepth(b, depth)
SWFButtonRecord_setDepth = _mingc.SWFButtonRecord_setDepth

def SWFButtonRecord_addFilter(b, f):
    return _mingc.SWFButtonRecord_addFilter(b, f)
SWFButtonRecord_addFilter = _mingc.SWFButtonRecord_addFilter

def SWFButtonRecord_setBlendMode(b, mode):
    return _mingc.SWFButtonRecord_setBlendMode(b, mode)
SWFButtonRecord_setBlendMode = _mingc.SWFButtonRecord_setBlendMode

def SWFButtonRecord_move(record, x, y):
    return _mingc.SWFButtonRecord_move(record, x, y)
SWFButtonRecord_move = _mingc.SWFButtonRecord_move

def SWFButtonRecord_moveTo(record, x, y):
    return _mingc.SWFButtonRecord_moveTo(record, x, y)
SWFButtonRecord_moveTo = _mingc.SWFButtonRecord_moveTo

def SWFButtonRecord_rotate(record, deg):
    return _mingc.SWFButtonRecord_rotate(record, deg)
SWFButtonRecord_rotate = _mingc.SWFButtonRecord_rotate

def SWFButtonRecord_rotateTo(record, deg):
    return _mingc.SWFButtonRecord_rotateTo(record, deg)
SWFButtonRecord_rotateTo = _mingc.SWFButtonRecord_rotateTo

def SWFButtonRecord_scale(record, scaleX, scaleY):
    return _mingc.SWFButtonRecord_scale(record, scaleX, scaleY)
SWFButtonRecord_scale = _mingc.SWFButtonRecord_scale

def SWFButtonRecord_scaleTo(record, scaleX, scaleY):
    return _mingc.SWFButtonRecord_scaleTo(record, scaleX, scaleY)
SWFButtonRecord_scaleTo = _mingc.SWFButtonRecord_scaleTo

def SWFButtonRecord_skewX(record, skewX):
    return _mingc.SWFButtonRecord_skewX(record, skewX)
SWFButtonRecord_skewX = _mingc.SWFButtonRecord_skewX

def SWFButtonRecord_skewXTo(record, skewX):
    return _mingc.SWFButtonRecord_skewXTo(record, skewX)
SWFButtonRecord_skewXTo = _mingc.SWFButtonRecord_skewXTo

def SWFButtonRecord_skewY(record, skewY):
    return _mingc.SWFButtonRecord_skewY(record, skewY)
SWFButtonRecord_skewY = _mingc.SWFButtonRecord_skewY

def SWFButtonRecord_skewYTo(record, skewY):
    return _mingc.SWFButtonRecord_skewYTo(record, skewY)
SWFButtonRecord_skewYTo = _mingc.SWFButtonRecord_skewYTo
SWFVIDEOSTREAM_MODE_AUTO = _mingc.SWFVIDEOSTREAM_MODE_AUTO
SWFVIDEOSTREAM_MODE_MANUAL = _mingc.SWFVIDEOSTREAM_MODE_MANUAL

def newSWFVideoStream_fromFile(f):
    return _mingc.newSWFVideoStream_fromFile(f)
newSWFVideoStream_fromFile = _mingc.newSWFVideoStream_fromFile

def newSWFVideoStream_fromInput(input):
    return _mingc.newSWFVideoStream_fromInput(input)
newSWFVideoStream_fromInput = _mingc.newSWFVideoStream_fromInput

def newSWFVideoStream():
    return _mingc.newSWFVideoStream()
newSWFVideoStream = _mingc.newSWFVideoStream

def SWFVideoStream_setDimension(stream, width, height):
    return _mingc.SWFVideoStream_setDimension(stream, width, height)
SWFVideoStream_setDimension = _mingc.SWFVideoStream_setDimension

def SWFVideoStream_getNumFrames(stream):
    return _mingc.SWFVideoStream_getNumFrames(stream)
SWFVideoStream_getNumFrames = _mingc.SWFVideoStream_getNumFrames

def SWFVideoStream_hasAudio(stream):
    return _mingc.SWFVideoStream_hasAudio(stream)
SWFVideoStream_hasAudio = _mingc.SWFVideoStream_hasAudio

def SWFVideoStream_setFrameMode(stream, mode):
    return _mingc.SWFVideoStream_setFrameMode(stream, mode)
SWFVideoStream_setFrameMode = _mingc.SWFVideoStream_setFrameMode

def SWFVideoStream_nextFrame(stream):
    return _mingc.SWFVideoStream_nextFrame(stream)
SWFVideoStream_nextFrame = _mingc.SWFVideoStream_nextFrame

def SWFVideoStream_seek(stream, frame, whence):
    return _mingc.SWFVideoStream_seek(stream, frame, whence)
SWFVideoStream_seek = _mingc.SWFVideoStream_seek

def destroySWFVideoStream(stream):
    return _mingc.destroySWFVideoStream(stream)
destroySWFVideoStream = _mingc.destroySWFVideoStream

def newSWFSprite():
    return _mingc.newSWFSprite()
newSWFSprite = _mingc.newSWFSprite

def destroySWFSprite(sprite):
    return _mingc.destroySWFSprite(sprite)
destroySWFSprite = _mingc.destroySWFSprite

def SWFSprite_addBlock(sprite, block):
    return _mingc.SWFSprite_addBlock(sprite, block)
SWFSprite_addBlock = _mingc.SWFSprite_addBlock

def newSWFPosition(matrix):
    return _mingc.newSWFPosition(matrix)
newSWFPosition = _mingc.newSWFPosition

def destroySWFPosition(position):
    return _mingc.destroySWFPosition(position)
destroySWFPosition = _mingc.destroySWFPosition

def SWFPosition_skewX(position, x):
    return _mingc.SWFPosition_skewX(position, x)
SWFPosition_skewX = _mingc.SWFPosition_skewX

def SWFPosition_skewXTo(position, x):
    return _mingc.SWFPosition_skewXTo(position, x)
SWFPosition_skewXTo = _mingc.SWFPosition_skewXTo

def SWFPosition_skewY(position, y):
    return _mingc.SWFPosition_skewY(position, y)
SWFPosition_skewY = _mingc.SWFPosition_skewY

def SWFPosition_skewYTo(position, y):
    return _mingc.SWFPosition_skewYTo(position, y)
SWFPosition_skewYTo = _mingc.SWFPosition_skewYTo

def SWFPosition_scaleX(position, x):
    return _mingc.SWFPosition_scaleX(position, x)
SWFPosition_scaleX = _mingc.SWFPosition_scaleX

def SWFPosition_scaleXTo(position, x):
    return _mingc.SWFPosition_scaleXTo(position, x)
SWFPosition_scaleXTo = _mingc.SWFPosition_scaleXTo

def SWFPosition_scaleY(position, y):
    return _mingc.SWFPosition_scaleY(position, y)
SWFPosition_scaleY = _mingc.SWFPosition_scaleY

def SWFPosition_scaleYTo(position, y):
    return _mingc.SWFPosition_scaleYTo(position, y)
SWFPosition_scaleYTo = _mingc.SWFPosition_scaleYTo

def SWFPosition_scaleXY(position, x, y):
    return _mingc.SWFPosition_scaleXY(position, x, y)
SWFPosition_scaleXY = _mingc.SWFPosition_scaleXY

def SWFPosition_scaleXYTo(position, x, y):
    return _mingc.SWFPosition_scaleXYTo(position, x, y)
SWFPosition_scaleXYTo = _mingc.SWFPosition_scaleXYTo

def SWFPosition_getMatrix(p):
    return _mingc.SWFPosition_getMatrix(p)
SWFPosition_getMatrix = _mingc.SWFPosition_getMatrix

def SWFPosition_setMatrix(p, a, b, c, d, x, y):
    return _mingc.SWFPosition_setMatrix(p, a, b, c, d, x, y)
SWFPosition_setMatrix = _mingc.SWFPosition_setMatrix

def SWFPosition_rotate(position, degrees):
    return _mingc.SWFPosition_rotate(position, degrees)
SWFPosition_rotate = _mingc.SWFPosition_rotate

def SWFPosition_rotateTo(position, degrees):
    return _mingc.SWFPosition_rotateTo(position, degrees)
SWFPosition_rotateTo = _mingc.SWFPosition_rotateTo

def SWFPosition_move(position, x, y):
    return _mingc.SWFPosition_move(position, x, y)
SWFPosition_move = _mingc.SWFPosition_move

def SWFPosition_moveTo(position, x, y):
    return _mingc.SWFPosition_moveTo(position, x, y)
SWFPosition_moveTo = _mingc.SWFPosition_moveTo

def SWFPosition_getRotation(position):
    return _mingc.SWFPosition_getRotation(position)
SWFPosition_getRotation = _mingc.SWFPosition_getRotation

def SWFPosition_getX(position):
    return _mingc.SWFPosition_getX(position)
SWFPosition_getX = _mingc.SWFPosition_getX

def SWFPosition_getY(position):
    return _mingc.SWFPosition_getY(position)
SWFPosition_getY = _mingc.SWFPosition_getY

def SWFPosition_getXY(position, outX, outY):
    return _mingc.SWFPosition_getXY(position, outX, outY)
SWFPosition_getXY = _mingc.SWFPosition_getXY

def SWFPosition_getXScale(position):
    return _mingc.SWFPosition_getXScale(position)
SWFPosition_getXScale = _mingc.SWFPosition_getXScale

def SWFPosition_getYScale(position):
    return _mingc.SWFPosition_getYScale(position)
SWFPosition_getYScale = _mingc.SWFPosition_getYScale

def SWFPosition_getXYScale(position, outXScale, outYScale):
    return _mingc.SWFPosition_getXYScale(position, outXScale, outYScale)
SWFPosition_getXYScale = _mingc.SWFPosition_getXYScale

def SWFPosition_getXSkew(position):
    return _mingc.SWFPosition_getXSkew(position)
SWFPosition_getXSkew = _mingc.SWFPosition_getXSkew

def SWFPosition_getYSkew(position):
    return _mingc.SWFPosition_getYSkew(position)
SWFPosition_getYSkew = _mingc.SWFPosition_getYSkew

def SWFPosition_getXYSkew(position, outXSkew, outYSkew):
    return _mingc.SWFPosition_getXYSkew(position, outXSkew, outYSkew)
SWFPosition_getXYSkew = _mingc.SWFPosition_getXYSkew

def SWFDisplayItem_getCharacter(item):
    return _mingc.SWFDisplayItem_getCharacter(item)
SWFDisplayItem_getCharacter = _mingc.SWFDisplayItem_getCharacter

def SWFDisplayItem_endMask(item):
    return _mingc.SWFDisplayItem_endMask(item)
SWFDisplayItem_endMask = _mingc.SWFDisplayItem_endMask

def SWFDisplayItem_move(item, x, y):
    return _mingc.SWFDisplayItem_move(item, x, y)
SWFDisplayItem_move = _mingc.SWFDisplayItem_move

def SWFDisplayItem_moveTo(item, x, y):
    return _mingc.SWFDisplayItem_moveTo(item, x, y)
SWFDisplayItem_moveTo = _mingc.SWFDisplayItem_moveTo

def SWFDisplayItem_rotate(item, degrees):
    return _mingc.SWFDisplayItem_rotate(item, degrees)
SWFDisplayItem_rotate = _mingc.SWFDisplayItem_rotate

def SWFDisplayItem_rotateTo(item, degrees):
    return _mingc.SWFDisplayItem_rotateTo(item, degrees)
SWFDisplayItem_rotateTo = _mingc.SWFDisplayItem_rotateTo

def SWFDisplayItem_scale(item, xScale, yScale):
    return _mingc.SWFDisplayItem_scale(item, xScale, yScale)
SWFDisplayItem_scale = _mingc.SWFDisplayItem_scale

def SWFDisplayItem_scaleTo(item, xScale, yScale):
    return _mingc.SWFDisplayItem_scaleTo(item, xScale, yScale)
SWFDisplayItem_scaleTo = _mingc.SWFDisplayItem_scaleTo

def SWFDisplayItem_skewX(item, x):
    return _mingc.SWFDisplayItem_skewX(item, x)
SWFDisplayItem_skewX = _mingc.SWFDisplayItem_skewX

def SWFDisplayItem_skewXTo(item, x):
    return _mingc.SWFDisplayItem_skewXTo(item, x)
SWFDisplayItem_skewXTo = _mingc.SWFDisplayItem_skewXTo

def SWFDisplayItem_skewY(item, y):
    return _mingc.SWFDisplayItem_skewY(item, y)
SWFDisplayItem_skewY = _mingc.SWFDisplayItem_skewY

def SWFDisplayItem_skewYTo(item, y):
    return _mingc.SWFDisplayItem_skewYTo(item, y)
SWFDisplayItem_skewYTo = _mingc.SWFDisplayItem_skewYTo

def SWFDisplayItem_getPosition(item, x, y):
    return _mingc.SWFDisplayItem_getPosition(item, x, y)
SWFDisplayItem_getPosition = _mingc.SWFDisplayItem_getPosition

def SWFDisplayItem_getRotation(item, degrees):
    return _mingc.SWFDisplayItem_getRotation(item, degrees)
SWFDisplayItem_getRotation = _mingc.SWFDisplayItem_getRotation

def SWFDisplayItem_getScale(item, xScale, yScale):
    return _mingc.SWFDisplayItem_getScale(item, xScale, yScale)
SWFDisplayItem_getScale = _mingc.SWFDisplayItem_getScale

def SWFDisplayItem_getSkew(item, xSkew, ySkew):
    return _mingc.SWFDisplayItem_getSkew(item, xSkew, ySkew)
SWFDisplayItem_getSkew = _mingc.SWFDisplayItem_getSkew

def SWFDisplayItem_getMatrix(item):
    return _mingc.SWFDisplayItem_getMatrix(item)
SWFDisplayItem_getMatrix = _mingc.SWFDisplayItem_getMatrix

def SWFDisplayItem_setMatrix(i, a, b, c, d, x, y):
    return _mingc.SWFDisplayItem_setMatrix(i, a, b, c, d, x, y)
SWFDisplayItem_setMatrix = _mingc.SWFDisplayItem_setMatrix

def SWFDisplayItem_getDepth(item):
    return _mingc.SWFDisplayItem_getDepth(item)
SWFDisplayItem_getDepth = _mingc.SWFDisplayItem_getDepth

def SWFDisplayItem_setDepth(item, depth):
    return _mingc.SWFDisplayItem_setDepth(item, depth)
SWFDisplayItem_setDepth = _mingc.SWFDisplayItem_setDepth

def SWFDisplayItem_remove(item):
    return _mingc.SWFDisplayItem_remove(item)
SWFDisplayItem_remove = _mingc.SWFDisplayItem_remove

def SWFDisplayItem_setName(item, name):
    return _mingc.SWFDisplayItem_setName(item, name)
SWFDisplayItem_setName = _mingc.SWFDisplayItem_setName

def SWFDisplayItem_setMaskLevel(item, masklevel):
    return _mingc.SWFDisplayItem_setMaskLevel(item, masklevel)
SWFDisplayItem_setMaskLevel = _mingc.SWFDisplayItem_setMaskLevel

def SWFDisplayItem_setRatio(item, ratio):
    return _mingc.SWFDisplayItem_setRatio(item, ratio)
SWFDisplayItem_setRatio = _mingc.SWFDisplayItem_setRatio

def SWFDisplayItem_setCXform(item, cXform):
    return _mingc.SWFDisplayItem_setCXform(item, cXform)
SWFDisplayItem_setCXform = _mingc.SWFDisplayItem_setCXform

def SWFDisplayItem_setColorAdd(item, r, g, b, a):
    return _mingc.SWFDisplayItem_setColorAdd(item, r, g, b, a)
SWFDisplayItem_setColorAdd = _mingc.SWFDisplayItem_setColorAdd

def SWFDisplayItem_setColorMult(item, r, g, b, a):
    return _mingc.SWFDisplayItem_setColorMult(item, r, g, b, a)
SWFDisplayItem_setColorMult = _mingc.SWFDisplayItem_setColorMult
SWFACTION_ONLOAD = _mingc.SWFACTION_ONLOAD
SWFACTION_ENTERFRAME = _mingc.SWFACTION_ENTERFRAME
SWFACTION_UNLOAD = _mingc.SWFACTION_UNLOAD
SWFACTION_MOUSEMOVE = _mingc.SWFACTION_MOUSEMOVE
SWFACTION_MOUSEDOWN = _mingc.SWFACTION_MOUSEDOWN
SWFACTION_MOUSEUP = _mingc.SWFACTION_MOUSEUP
SWFACTION_KEYDOWN = _mingc.SWFACTION_KEYDOWN
SWFACTION_KEYUP = _mingc.SWFACTION_KEYUP
SWFACTION_DATA = _mingc.SWFACTION_DATA

def SWFDisplayItem_addAction(item, action, flags):
    return _mingc.SWFDisplayItem_addAction(item, action, flags)
SWFDisplayItem_addAction = _mingc.SWFDisplayItem_addAction

def SWFDisplayItem_cacheAsBitmap(item, flag):
    return _mingc.SWFDisplayItem_cacheAsBitmap(item, flag)
SWFDisplayItem_cacheAsBitmap = _mingc.SWFDisplayItem_cacheAsBitmap
SWFBLEND_MODE_NULL = _mingc.SWFBLEND_MODE_NULL
SWFBLEND_MODE_NORMAL = _mingc.SWFBLEND_MODE_NORMAL
SWFBLEND_MODE_LAYER = _mingc.SWFBLEND_MODE_LAYER
SWFBLEND_MODE_MULT = _mingc.SWFBLEND_MODE_MULT
SWFBLEND_MODE_SCREEN = _mingc.SWFBLEND_MODE_SCREEN
SWFBLEND_MODE_LIGHTEN = _mingc.SWFBLEND_MODE_LIGHTEN
SWFBLEND_MODE_DARKEN = _mingc.SWFBLEND_MODE_DARKEN
SWFBLEND_MODE_DIFF = _mingc.SWFBLEND_MODE_DIFF
SWFBLEND_MODE_ADD = _mingc.SWFBLEND_MODE_ADD
SWFBLEND_MODE_SUB = _mingc.SWFBLEND_MODE_SUB
SWFBLEND_MODE_INV = _mingc.SWFBLEND_MODE_INV
SWFBLEND_MODE_ALPHA = _mingc.SWFBLEND_MODE_ALPHA
SWFBLEND_MODE_ERASE = _mingc.SWFBLEND_MODE_ERASE
SWFBLEND_MODE_OVERLAY = _mingc.SWFBLEND_MODE_OVERLAY
SWFBLEND_MODE_HARDLIGHT = _mingc.SWFBLEND_MODE_HARDLIGHT

def SWFDisplayItem_setBlendMode(item, mode):
    return _mingc.SWFDisplayItem_setBlendMode(item, mode)
SWFDisplayItem_setBlendMode = _mingc.SWFDisplayItem_setBlendMode

def newSWFFill(fillstyle):
    return _mingc.newSWFFill(fillstyle)
newSWFFill = _mingc.newSWFFill

def destroySWFFill(fill):
    return _mingc.destroySWFFill(fill)
destroySWFFill = _mingc.destroySWFFill

def SWFFill_getFillStyle(fill):
    return _mingc.SWFFill_getFillStyle(fill)
SWFFill_getFillStyle = _mingc.SWFFill_getFillStyle

def SWFFill_skewX(fill, x):
    return _mingc.SWFFill_skewX(fill, x)
SWFFill_skewX = _mingc.SWFFill_skewX

def SWFFill_skewXTo(fill, x):
    return _mingc.SWFFill_skewXTo(fill, x)
SWFFill_skewXTo = _mingc.SWFFill_skewXTo

def SWFFill_skewY(fill, y):
    return _mingc.SWFFill_skewY(fill, y)
SWFFill_skewY = _mingc.SWFFill_skewY

def SWFFill_skewYTo(fill, y):
    return _mingc.SWFFill_skewYTo(fill, y)
SWFFill_skewYTo = _mingc.SWFFill_skewYTo

def SWFFill_scaleX(fill, x):
    return _mingc.SWFFill_scaleX(fill, x)
SWFFill_scaleX = _mingc.SWFFill_scaleX

def SWFFill_scaleXTo(fill, x):
    return _mingc.SWFFill_scaleXTo(fill, x)
SWFFill_scaleXTo = _mingc.SWFFill_scaleXTo

def SWFFill_scaleY(fill, y):
    return _mingc.SWFFill_scaleY(fill, y)
SWFFill_scaleY = _mingc.SWFFill_scaleY

def SWFFill_scaleYTo(fill, y):
    return _mingc.SWFFill_scaleYTo(fill, y)
SWFFill_scaleYTo = _mingc.SWFFill_scaleYTo

def SWFFill_scaleXY(fill, x, y):
    return _mingc.SWFFill_scaleXY(fill, x, y)
SWFFill_scaleXY = _mingc.SWFFill_scaleXY

def SWFFill_scaleXYTo(fill, x, y):
    return _mingc.SWFFill_scaleXYTo(fill, x, y)
SWFFill_scaleXYTo = _mingc.SWFFill_scaleXYTo

def SWFFill_rotate(fill, degrees):
    return _mingc.SWFFill_rotate(fill, degrees)
SWFFill_rotate = _mingc.SWFFill_rotate

def SWFFill_rotateTo(fill, degrees):
    return _mingc.SWFFill_rotateTo(fill, degrees)
SWFFill_rotateTo = _mingc.SWFFill_rotateTo

def SWFFill_move(fill, x, y):
    return _mingc.SWFFill_move(fill, x, y)
SWFFill_move = _mingc.SWFFill_move

def SWFFill_moveTo(fill, x, y):
    return _mingc.SWFFill_moveTo(fill, x, y)
SWFFill_moveTo = _mingc.SWFFill_moveTo

def SWFFill_setMatrix(fill, a, b, c, d, x, y):
    return _mingc.SWFFill_setMatrix(fill, a, b, c, d, x, y)
SWFFill_setMatrix = _mingc.SWFFill_setMatrix

def SWFShape_setLine(shape, width, r, g, b, a):
    return _mingc.SWFShape_setLine(shape, width, r, g, b, a)
SWFShape_setLine = _mingc.SWFShape_setLine

def SWFShape_setLine2Filled(shape, width, fill, flags, miterLimit):
    return _mingc.SWFShape_setLine2Filled(shape, width, fill, flags, miterLimit)
SWFShape_setLine2Filled = _mingc.SWFShape_setLine2Filled

def SWFShape_setLine2(shape, width, r, g, b, a, flags, miterLimit):
    return _mingc.SWFShape_setLine2(shape, width, r, g, b, a, flags, miterLimit)
SWFShape_setLine2 = _mingc.SWFShape_setLine2

def SWFShape_addSolidFill(shape, r, g, b, a):
    return _mingc.SWFShape_addSolidFill(shape, r, g, b, a)
SWFShape_addSolidFill = _mingc.SWFShape_addSolidFill

def SWFShape_addGradientFill(shape, gradient, flags):
    return _mingc.SWFShape_addGradientFill(shape, gradient, flags)
SWFShape_addGradientFill = _mingc.SWFShape_addGradientFill

def SWFShape_addBitmapFill(shape, bitmap, flags):
    return _mingc.SWFShape_addBitmapFill(shape, bitmap, flags)
SWFShape_addBitmapFill = _mingc.SWFShape_addBitmapFill

def SWFShape_setLeftFill(shape, fill):
    return _mingc.SWFShape_setLeftFill(shape, fill)
SWFShape_setLeftFill = _mingc.SWFShape_setLeftFill

def SWFShape_setRightFill(shape, fill):
    return _mingc.SWFShape_setRightFill(shape, fill)
SWFShape_setRightFill = _mingc.SWFShape_setRightFill

def SWFShape_drawArc(shape, r, startAngle, endAngle):
    return _mingc.SWFShape_drawArc(shape, r, startAngle, endAngle)
SWFShape_drawArc = _mingc.SWFShape_drawArc

def SWFShape_drawCircle(shape, r):
    return _mingc.SWFShape_drawCircle(shape, r)
SWFShape_drawCircle = _mingc.SWFShape_drawCircle

def SWFShape_drawGlyph(shape, font, c):
    return _mingc.SWFShape_drawGlyph(shape, font, c)
SWFShape_drawGlyph = _mingc.SWFShape_drawGlyph

def SWFShape_drawSizedGlyph(shape, font, c, size):
    return _mingc.SWFShape_drawSizedGlyph(shape, font, c, size)
SWFShape_drawSizedGlyph = _mingc.SWFShape_drawSizedGlyph

def SWFShape_drawCubic(shape, bx, by, cx, cy, dx, dy):
    return _mingc.SWFShape_drawCubic(shape, bx, by, cx, cy, dx, dy)
SWFShape_drawCubic = _mingc.SWFShape_drawCubic

def SWFShape_drawCubicTo(shape, bx, by, cx, cy, dx, dy):
    return _mingc.SWFShape_drawCubicTo(shape, bx, by, cx, cy, dx, dy)
SWFShape_drawCubicTo = _mingc.SWFShape_drawCubicTo

def SWFShape_drawCharacterBounds(shape, character):
    return _mingc.SWFShape_drawCharacterBounds(shape, character)
SWFShape_drawCharacterBounds = _mingc.SWFShape_drawCharacterBounds

def newSWFMovieClip():
    return _mingc.newSWFMovieClip()
newSWFMovieClip = _mingc.newSWFMovieClip

def destroySWFMovieClip(movieClip):
    return _mingc.destroySWFMovieClip(movieClip)
destroySWFMovieClip = _mingc.destroySWFMovieClip

def SWFMovieClip_setNumberOfFrames(clip, frames):
    return _mingc.SWFMovieClip_setNumberOfFrames(clip, frames)
SWFMovieClip_setNumberOfFrames = _mingc.SWFMovieClip_setNumberOfFrames

def SWFMovieClip_nextFrame(clip):
    return _mingc.SWFMovieClip_nextFrame(clip)
SWFMovieClip_nextFrame = _mingc.SWFMovieClip_nextFrame

def SWFMovieClip_labelFrame(clip, label):
    return _mingc.SWFMovieClip_labelFrame(clip, label)
SWFMovieClip_labelFrame = _mingc.SWFMovieClip_labelFrame

def SWFMovieClip_add(clip, block):
    return _mingc.SWFMovieClip_add(clip, block)
SWFMovieClip_add = _mingc.SWFMovieClip_add

def SWFMovieClip_remove(clip, item):
    return _mingc.SWFMovieClip_remove(clip, item)
SWFMovieClip_remove = _mingc.SWFMovieClip_remove

def SWFMovieClip_setSoundStreamAt(clip, sound, rate, skipSound):
    return _mingc.SWFMovieClip_setSoundStreamAt(clip, sound, rate, skipSound)
SWFMovieClip_setSoundStreamAt = _mingc.SWFMovieClip_setSoundStreamAt

def SWFMovieClip_setSoundStream(clip, sound, rate):
    return _mingc.SWFMovieClip_setSoundStream(clip, sound, rate)
SWFMovieClip_setSoundStream = _mingc.SWFMovieClip_setSoundStream

def SWFMovieClip_startSound(clip, sound):
    return _mingc.SWFMovieClip_startSound(clip, sound)
SWFMovieClip_startSound = _mingc.SWFMovieClip_startSound

def SWFMovieClip_stopSound(clip, sound):
    return _mingc.SWFMovieClip_stopSound(clip, sound)
SWFMovieClip_stopSound = _mingc.SWFMovieClip_stopSound

def destroySWFPrebuiltClip(clip):
    return _mingc.destroySWFPrebuiltClip(clip)
destroySWFPrebuiltClip = _mingc.destroySWFPrebuiltClip

def newSWFPrebuiltClip_fromFile(filename):
    return _mingc.newSWFPrebuiltClip_fromFile(filename)
newSWFPrebuiltClip_fromFile = _mingc.newSWFPrebuiltClip_fromFile

def newSWFPrebuiltClip_fromInput(input):
    return _mingc.newSWFPrebuiltClip_fromInput(input)
newSWFPrebuiltClip_fromInput = _mingc.newSWFPrebuiltClip_fromInput

def newSWFBinaryData(blob, length):
    return _mingc.newSWFBinaryData(blob, length)
newSWFBinaryData = _mingc.newSWFBinaryData

def newSWFMovie():
    return _mingc.newSWFMovie()
newSWFMovie = _mingc.newSWFMovie

def newSWFMovieWithVersion(version):
    return _mingc.newSWFMovieWithVersion(version)
newSWFMovieWithVersion = _mingc.newSWFMovieWithVersion

def destroySWFMovie(movie):
    return _mingc.destroySWFMovie(movie)
destroySWFMovie = _mingc.destroySWFMovie

def SWFMovie_setRate(movie, rate):
    return _mingc.SWFMovie_setRate(movie, rate)
SWFMovie_setRate = _mingc.SWFMovie_setRate

def SWFMovie_getRate(movie):
    return _mingc.SWFMovie_getRate(movie)
SWFMovie_getRate = _mingc.SWFMovie_getRate

def SWFMovie_setDimension(movie, x, y):
    return _mingc.SWFMovie_setDimension(movie, x, y)
SWFMovie_setDimension = _mingc.SWFMovie_setDimension

def SWFMovie_setNumberOfFrames(movie, frames):
    return _mingc.SWFMovie_setNumberOfFrames(movie, frames)
SWFMovie_setNumberOfFrames = _mingc.SWFMovie_setNumberOfFrames

def SWFMovie_addExport(movie, block, name):
    return _mingc.SWFMovie_addExport(movie, block, name)
SWFMovie_addExport = _mingc.SWFMovie_addExport

def SWFMovie_setBackground(movie, r, g, b):
    return _mingc.SWFMovie_setBackground(movie, r, g, b)
SWFMovie_setBackground = _mingc.SWFMovie_setBackground

def SWFMovie_setSoundStream(movie, sound):
    return _mingc.SWFMovie_setSoundStream(movie, sound)
SWFMovie_setSoundStream = _mingc.SWFMovie_setSoundStream

def SWFMovie_setSoundStreamAt(movie, stream, skip):
    return _mingc.SWFMovie_setSoundStreamAt(movie, stream, skip)
SWFMovie_setSoundStreamAt = _mingc.SWFMovie_setSoundStreamAt

def SWFMovie_startSound(movie, sound):
    return _mingc.SWFMovie_startSound(movie, sound)
SWFMovie_startSound = _mingc.SWFMovie_startSound

def SWFMovie_stopSound(movie, sound):
    return _mingc.SWFMovie_stopSound(movie, sound)
SWFMovie_stopSound = _mingc.SWFMovie_stopSound

def SWFMovie_add(movie, block):
    return _mingc.SWFMovie_add(movie, block)
SWFMovie_add = _mingc.SWFMovie_add

def SWFMovie_remove(movie, item):
    return _mingc.SWFMovie_remove(movie, item)
SWFMovie_remove = _mingc.SWFMovie_remove

def SWFMovie_nextFrame(movie):
    return _mingc.SWFMovie_nextFrame(movie)
SWFMovie_nextFrame = _mingc.SWFMovie_nextFrame

def SWFMovie_labelFrame(movie, label):
    return _mingc.SWFMovie_labelFrame(movie, label)
SWFMovie_labelFrame = _mingc.SWFMovie_labelFrame

def SWFMovie_output(movie, method, data):
    return _mingc.SWFMovie_output(movie, method, data)
SWFMovie_output = _mingc.SWFMovie_output

def SWFMovie_save(movie, filename):
    return _mingc.SWFMovie_save(movie, filename)
SWFMovie_save = _mingc.SWFMovie_save

def SWFMovie_protect(movie, password):
    return _mingc.SWFMovie_protect(movie, password)
SWFMovie_protect = _mingc.SWFMovie_protect

def SWFMovie_setNetworkAccess(movie, flag):
    return _mingc.SWFMovie_setNetworkAccess(movie, flag)
SWFMovie_setNetworkAccess = _mingc.SWFMovie_setNetworkAccess

def SWFMovie_addMetadata(movie, xml):
    return _mingc.SWFMovie_addMetadata(movie, xml)
SWFMovie_addMetadata = _mingc.SWFMovie_addMetadata

def SWFMovie_setScriptLimits(movie, maxRecursion, timeout):
    return _mingc.SWFMovie_setScriptLimits(movie, maxRecursion, timeout)
SWFMovie_setScriptLimits = _mingc.SWFMovie_setScriptLimits

def SWFMovie_setTabIndex(movie, depth, i):
    return _mingc.SWFMovie_setTabIndex(movie, depth, i)
SWFMovie_setTabIndex = _mingc.SWFMovie_setTabIndex

def SWFMovie_importFont(movie, filename, name):
    return _mingc.SWFMovie_importFont(movie, filename, name)
SWFMovie_importFont = _mingc.SWFMovie_importFont

def SWFMovie_addFont(movie, font):
    return _mingc.SWFMovie_addFont(movie, font)
SWFMovie_addFont = _mingc.SWFMovie_addFont

def SWFMovie_importCharacter(movie, filename, name):
    return _mingc.SWFMovie_importCharacter(movie, filename, name)
SWFMovie_importCharacter = _mingc.SWFMovie_importCharacter

def SWFMovie_assignSymbol(m, character, name):
    return _mingc.SWFMovie_assignSymbol(m, character, name)
SWFMovie_assignSymbol = _mingc.SWFMovie_assignSymbol

def SWFMovie_defineScene(m, offset, name):
    return _mingc.SWFMovie_defineScene(m, offset, name)
SWFMovie_defineScene = _mingc.SWFMovie_defineScene

def SWFMovie_namedAnchor(movie, label):
    return _mingc.SWFMovie_namedAnchor(movie, label)
SWFMovie_namedAnchor = _mingc.SWFMovie_namedAnchor

def SWFMovie_writeExports(movie):
    return _mingc.SWFMovie_writeExports(movie)
SWFMovie_writeExports = _mingc.SWFMovie_writeExports
SWFFILTER_MODE_INNER = _mingc.SWFFILTER_MODE_INNER
SWFFILTER_MODE_KO = _mingc.SWFFILTER_MODE_KO
SWFFILTER_MODE_COMPOSITE = _mingc.SWFFILTER_MODE_COMPOSITE
SWFFILTER_MODE_ONTOP = _mingc.SWFFILTER_MODE_ONTOP
SWFFILTER_FLAG_CLAMP = _mingc.SWFFILTER_FLAG_CLAMP
SWFFILTER_FLAG_PRESERVE_ALPHA = _mingc.SWFFILTER_FLAG_PRESERVE_ALPHA
SWFFILTER_TYPE_DROPSHADOW = _mingc.SWFFILTER_TYPE_DROPSHADOW
SWFFILTER_TYPE_BLUR = _mingc.SWFFILTER_TYPE_BLUR
SWFFILTER_TYPE_GLOW = _mingc.SWFFILTER_TYPE_GLOW
SWFFILTER_TYPE_BEVEL = _mingc.SWFFILTER_TYPE_BEVEL
SWFFILTER_TYPE_GRADIENTGLOW = _mingc.SWFFILTER_TYPE_GRADIENTGLOW
SWFFILTER_TYPE_CONVOLUTION = _mingc.SWFFILTER_TYPE_CONVOLUTION
SWFFILTER_TYPE_COLORMATRIX = _mingc.SWFFILTER_TYPE_COLORMATRIX
SWFFILTER_TYPE_GRADIENTBEVEL = _mingc.SWFFILTER_TYPE_GRADIENTBEVEL
class SWFColor(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SWFColor, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SWFColor, name)
    __repr__ = _swig_repr
    __swig_setmethods__["red"] = _mingc.SWFColor_red_set
    __swig_getmethods__["red"] = _mingc.SWFColor_red_get
    if _newclass:
        red = _swig_property(_mingc.SWFColor_red_get, _mingc.SWFColor_red_set)
    __swig_setmethods__["green"] = _mingc.SWFColor_green_set
    __swig_getmethods__["green"] = _mingc.SWFColor_green_get
    if _newclass:
        green = _swig_property(_mingc.SWFColor_green_get, _mingc.SWFColor_green_set)
    __swig_setmethods__["blue"] = _mingc.SWFColor_blue_set
    __swig_getmethods__["blue"] = _mingc.SWFColor_blue_get
    if _newclass:
        blue = _swig_property(_mingc.SWFColor_blue_get, _mingc.SWFColor_blue_set)
    __swig_setmethods__["alpha"] = _mingc.SWFColor_alpha_set
    __swig_getmethods__["alpha"] = _mingc.SWFColor_alpha_get
    if _newclass:
        alpha = _swig_property(_mingc.SWFColor_alpha_get, _mingc.SWFColor_alpha_set)

    def __init__(self):
        this = _mingc.new_SWFColor()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _mingc.delete_SWFColor
    __del__ = lambda self: None
SWFColor_swigregister = _mingc.SWFColor_swigregister
SWFColor_swigregister(SWFColor)


def newSWFShadow(angle, distance, strength):
    return _mingc.newSWFShadow(angle, distance, strength)
newSWFShadow = _mingc.newSWFShadow

def destroySWFShadow(s):
    return _mingc.destroySWFShadow(s)
destroySWFShadow = _mingc.destroySWFShadow

def newSWFBlur(blurX, blurY, passes):
    return _mingc.newSWFBlur(blurX, blurY, passes)
newSWFBlur = _mingc.newSWFBlur

def destroySWFBlur(b):
    return _mingc.destroySWFBlur(b)
destroySWFBlur = _mingc.destroySWFBlur

def newSWFFilterMatrix(cols, rows, vals):
    return _mingc.newSWFFilterMatrix(cols, rows, vals)
newSWFFilterMatrix = _mingc.newSWFFilterMatrix

def destroySWFFilterMatrix(m):
    return _mingc.destroySWFFilterMatrix(m)
destroySWFFilterMatrix = _mingc.destroySWFFilterMatrix

def destroySWFFilter(filter):
    return _mingc.destroySWFFilter(filter)
destroySWFFilter = _mingc.destroySWFFilter

def newColorMatrixFilter(matrix):
    return _mingc.newColorMatrixFilter(matrix)
newColorMatrixFilter = _mingc.newColorMatrixFilter

def newConvolutionFilter(matrix, divisor, bias, color, flags):
    return _mingc.newConvolutionFilter(matrix, divisor, bias, color, flags)
newConvolutionFilter = _mingc.newConvolutionFilter

def newGradientBevelFilter(gradient, blur, shadow, flags):
    return _mingc.newGradientBevelFilter(gradient, blur, shadow, flags)
newGradientBevelFilter = _mingc.newGradientBevelFilter

def newGradientGlowFilter(gradient, blur, shadow, flags):
    return _mingc.newGradientGlowFilter(gradient, blur, shadow, flags)
newGradientGlowFilter = _mingc.newGradientGlowFilter

def newBevelFilter(shadowColor, highlightColor, blur, shadow, flags):
    return _mingc.newBevelFilter(shadowColor, highlightColor, blur, shadow, flags)
newBevelFilter = _mingc.newBevelFilter

def newGlowFilter(color, blur, strength, flags):
    return _mingc.newGlowFilter(color, blur, strength, flags)
newGlowFilter = _mingc.newGlowFilter

def newBlurFilter(blur):
    return _mingc.newBlurFilter(blur)
newBlurFilter = _mingc.newBlurFilter

def newDropShadowFilter(color, blur, shadow, flags):
    return _mingc.newDropShadowFilter(color, blur, shadow, flags)
newDropShadowFilter = _mingc.newDropShadowFilter

def SWFDisplayItem_addFilter(item, filter):
    return _mingc.SWFDisplayItem_addFilter(item, filter)
SWFDisplayItem_addFilter = _mingc.SWFDisplayItem_addFilter
# This file is compatible with both classic and new-style classes.


