# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_mingc', [dirname(__file__)])
        except ImportError:
            import _mingc
            return _mingc
        if fp is not None:
            try:
                _mod = imp.load_module('_mingc', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _mingc = swig_import_helper()
    del swig_import_helper
else:
    import _mingc
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def new_intp():
  return _mingc.new_intp()
new_intp = _mingc.new_intp

def copy_intp(*args):
  return _mingc.copy_intp(*args)
copy_intp = _mingc.copy_intp

def delete_intp(*args):
  return _mingc.delete_intp(*args)
delete_intp = _mingc.delete_intp

def intp_assign(*args):
  return _mingc.intp_assign(*args)
intp_assign = _mingc.intp_assign

def intp_value(*args):
  return _mingc.intp_value(*args)
intp_value = _mingc.intp_value

def new_floatp():
  return _mingc.new_floatp()
new_floatp = _mingc.new_floatp

def copy_floatp(*args):
  return _mingc.copy_floatp(*args)
copy_floatp = _mingc.copy_floatp

def delete_floatp(*args):
  return _mingc.delete_floatp(*args)
delete_floatp = _mingc.delete_floatp

def floatp_assign(*args):
  return _mingc.floatp_assign(*args)
floatp_assign = _mingc.floatp_assign

def floatp_value(*args):
  return _mingc.floatp_value(*args)
floatp_value = _mingc.floatp_value
class floatArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, floatArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, floatArray, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _mingc.new_floatArray(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _mingc.delete_floatArray
    __del__ = lambda self : None;
    def __getitem__(self, *args): return _mingc.floatArray___getitem__(self, *args)
    def __setitem__(self, *args): return _mingc.floatArray___setitem__(self, *args)
    def cast(self): return _mingc.floatArray_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _mingc.floatArray_frompointer
    if _newclass:frompointer = staticmethod(_mingc.floatArray_frompointer)
floatArray_swigregister = _mingc.floatArray_swigregister
floatArray_swigregister(floatArray)

def floatArray_frompointer(*args):
  return _mingc.floatArray_frompointer(*args)
floatArray_frompointer = _mingc.floatArray_frompointer


def Ming_init():
  return _mingc.Ming_init()
Ming_init = _mingc.Ming_init

def Ming_cleanup():
  return _mingc.Ming_cleanup()
Ming_cleanup = _mingc.Ming_cleanup

def Ming_collectGarbage():
  return _mingc.Ming_collectGarbage()
Ming_collectGarbage = _mingc.Ming_collectGarbage

def Ming_useConstants(*args):
  return _mingc.Ming_useConstants(*args)
Ming_useConstants = _mingc.Ming_useConstants

def Ming_setCubicThreshold(*args):
  return _mingc.Ming_setCubicThreshold(*args)
Ming_setCubicThreshold = _mingc.Ming_setCubicThreshold

def Ming_setScale(*args):
  return _mingc.Ming_setScale(*args)
Ming_setScale = _mingc.Ming_setScale

def Ming_getScale():
  return _mingc.Ming_getScale()
Ming_getScale = _mingc.Ming_getScale

def Ming_useSWFVersion(*args):
  return _mingc.Ming_useSWFVersion(*args)
Ming_useSWFVersion = _mingc.Ming_useSWFVersion

def Ming_setSWFCompression(*args):
  return _mingc.Ming_setSWFCompression(*args)
Ming_setSWFCompression = _mingc.Ming_setSWFCompression

def SWFMatrix_getScaleX(*args):
  return _mingc.SWFMatrix_getScaleX(*args)
SWFMatrix_getScaleX = _mingc.SWFMatrix_getScaleX

def SWFMatrix_getRotate0(*args):
  return _mingc.SWFMatrix_getRotate0(*args)
SWFMatrix_getRotate0 = _mingc.SWFMatrix_getRotate0

def SWFMatrix_getRotate1(*args):
  return _mingc.SWFMatrix_getRotate1(*args)
SWFMatrix_getRotate1 = _mingc.SWFMatrix_getRotate1

def SWFMatrix_getScaleY(*args):
  return _mingc.SWFMatrix_getScaleY(*args)
SWFMatrix_getScaleY = _mingc.SWFMatrix_getScaleY

def SWFMatrix_getTranslateX(*args):
  return _mingc.SWFMatrix_getTranslateX(*args)
SWFMatrix_getTranslateX = _mingc.SWFMatrix_getTranslateX

def SWFMatrix_getTranslateY(*args):
  return _mingc.SWFMatrix_getTranslateY(*args)
SWFMatrix_getTranslateY = _mingc.SWFMatrix_getTranslateY

def newSWFInput_file(*args):
  return _mingc.newSWFInput_file(*args)
newSWFInput_file = _mingc.newSWFInput_file

def newSWFInput_stream(*args):
  return _mingc.newSWFInput_stream(*args)
newSWFInput_stream = _mingc.newSWFInput_stream

def newSWFInput_buffer(*args):
  return _mingc.newSWFInput_buffer(*args)
newSWFInput_buffer = _mingc.newSWFInput_buffer

def newSWFInput_allocedBuffer(*args):
  return _mingc.newSWFInput_allocedBuffer(*args)
newSWFInput_allocedBuffer = _mingc.newSWFInput_allocedBuffer

def destroySWFInput(*args):
  return _mingc.destroySWFInput(*args)
destroySWFInput = _mingc.destroySWFInput

def SWFInput_length(*args):
  return _mingc.SWFInput_length(*args)
SWFInput_length = _mingc.SWFInput_length

def SWFInput_rewind(*args):
  return _mingc.SWFInput_rewind(*args)
SWFInput_rewind = _mingc.SWFInput_rewind

def SWFInput_tell(*args):
  return _mingc.SWFInput_tell(*args)
SWFInput_tell = _mingc.SWFInput_tell

def SWFInput_seek(*args):
  return _mingc.SWFInput_seek(*args)
SWFInput_seek = _mingc.SWFInput_seek

def SWFInput_eof(*args):
  return _mingc.SWFInput_eof(*args)
SWFInput_eof = _mingc.SWFInput_eof

def SWFCharacter_getWidth(*args):
  return _mingc.SWFCharacter_getWidth(*args)
SWFCharacter_getWidth = _mingc.SWFCharacter_getWidth

def SWFCharacter_getHeight(*args):
  return _mingc.SWFCharacter_getHeight(*args)
SWFCharacter_getHeight = _mingc.SWFCharacter_getHeight

def newSWFBitmap_fromInput(*args):
  return _mingc.newSWFBitmap_fromInput(*args)
newSWFBitmap_fromInput = _mingc.newSWFBitmap_fromInput

def destroySWFBitmap(*args):
  return _mingc.destroySWFBitmap(*args)
destroySWFBitmap = _mingc.destroySWFBitmap

def SWFBitmap_getWidth(*args):
  return _mingc.SWFBitmap_getWidth(*args)
SWFBitmap_getWidth = _mingc.SWFBitmap_getWidth

def SWFBitmap_getHeight(*args):
  return _mingc.SWFBitmap_getHeight(*args)
SWFBitmap_getHeight = _mingc.SWFBitmap_getHeight

def newSWFDBLBitmap(*args):
  return _mingc.newSWFDBLBitmap(*args)
newSWFDBLBitmap = _mingc.newSWFDBLBitmap

def newSWFDBLBitmap_fromInput(*args):
  return _mingc.newSWFDBLBitmap_fromInput(*args)
newSWFDBLBitmap_fromInput = _mingc.newSWFDBLBitmap_fromInput

def newSWFJpegBitmap(*args):
  return _mingc.newSWFJpegBitmap(*args)
newSWFJpegBitmap = _mingc.newSWFJpegBitmap

def newSWFJpegBitmap_fromInput(*args):
  return _mingc.newSWFJpegBitmap_fromInput(*args)
newSWFJpegBitmap_fromInput = _mingc.newSWFJpegBitmap_fromInput

def newSWFJpegWithAlpha(*args):
  return _mingc.newSWFJpegWithAlpha(*args)
newSWFJpegWithAlpha = _mingc.newSWFJpegWithAlpha

def newSWFJpegWithAlpha_fromInput(*args):
  return _mingc.newSWFJpegWithAlpha_fromInput(*args)
newSWFJpegWithAlpha_fromInput = _mingc.newSWFJpegWithAlpha_fromInput
SWF_GRADIENT_PAD = _mingc.SWF_GRADIENT_PAD
SWF_GRADIENT_REFLECT = _mingc.SWF_GRADIENT_REFLECT
SWF_GRADIENT_REPEAT = _mingc.SWF_GRADIENT_REPEAT
SWF_GRADIENT_NORMAL = _mingc.SWF_GRADIENT_NORMAL
SWF_GRADIENT_LINEAR = _mingc.SWF_GRADIENT_LINEAR

def newSWFGradient():
  return _mingc.newSWFGradient()
newSWFGradient = _mingc.newSWFGradient

def destroySWFGradient(*args):
  return _mingc.destroySWFGradient(*args)
destroySWFGradient = _mingc.destroySWFGradient

def SWFGradient_addEntry(*args):
  return _mingc.SWFGradient_addEntry(*args)
SWFGradient_addEntry = _mingc.SWFGradient_addEntry

def SWFGradient_setSpreadMode(*args):
  return _mingc.SWFGradient_setSpreadMode(*args)
SWFGradient_setSpreadMode = _mingc.SWFGradient_setSpreadMode

def SWFGradient_setInterpolationMode(*args):
  return _mingc.SWFGradient_setInterpolationMode(*args)
SWFGradient_setInterpolationMode = _mingc.SWFGradient_setInterpolationMode

def SWFGradient_setFocalPoint(*args):
  return _mingc.SWFGradient_setFocalPoint(*args)
SWFGradient_setFocalPoint = _mingc.SWFGradient_setFocalPoint
SWFFILL_SOLID = _mingc.SWFFILL_SOLID
SWFFILL_GRADIENT = _mingc.SWFFILL_GRADIENT
SWFFILL_LINEAR_GRADIENT = _mingc.SWFFILL_LINEAR_GRADIENT
SWFFILL_RADIAL_GRADIENT = _mingc.SWFFILL_RADIAL_GRADIENT
SWFFILL_BITMAP = _mingc.SWFFILL_BITMAP
SWFFILL_TILED_BITMAP = _mingc.SWFFILL_TILED_BITMAP
SWFFILL_CLIPPED_BITMAP = _mingc.SWFFILL_CLIPPED_BITMAP

def newSWFSolidFillStyle(*args):
  return _mingc.newSWFSolidFillStyle(*args)
newSWFSolidFillStyle = _mingc.newSWFSolidFillStyle

def newSWFGradientFillStyle(*args):
  return _mingc.newSWFGradientFillStyle(*args)
newSWFGradientFillStyle = _mingc.newSWFGradientFillStyle

def newSWFBitmapFillStyle(*args):
  return _mingc.newSWFBitmapFillStyle(*args)
newSWFBitmapFillStyle = _mingc.newSWFBitmapFillStyle

def SWFFillStyle_getMatrix(*args):
  return _mingc.SWFFillStyle_getMatrix(*args)
SWFFillStyle_getMatrix = _mingc.SWFFillStyle_getMatrix

def newSWFLineStyle(*args):
  return _mingc.newSWFLineStyle(*args)
newSWFLineStyle = _mingc.newSWFLineStyle
SWF_LINESTYLE_CAP_ROUND = _mingc.SWF_LINESTYLE_CAP_ROUND
SWF_LINESTYLE_CAP_NONE = _mingc.SWF_LINESTYLE_CAP_NONE
SWF_LINESTYLE_CAP_SQUARE = _mingc.SWF_LINESTYLE_CAP_SQUARE
SWF_LINESTYLE_JOIN_ROUND = _mingc.SWF_LINESTYLE_JOIN_ROUND
SWF_LINESTYLE_JOIN_BEVEL = _mingc.SWF_LINESTYLE_JOIN_BEVEL
SWF_LINESTYLE_JOIN_MITER = _mingc.SWF_LINESTYLE_JOIN_MITER
SWF_LINESTYLE_FLAG_NOHSCALE = _mingc.SWF_LINESTYLE_FLAG_NOHSCALE
SWF_LINESTYLE_FLAG_NOVSCALE = _mingc.SWF_LINESTYLE_FLAG_NOVSCALE
SWF_LINESTYLE_FLAG_HINTING = _mingc.SWF_LINESTYLE_FLAG_HINTING
SWF_LINESTYLE_FLAG_NOCLOSE = _mingc.SWF_LINESTYLE_FLAG_NOCLOSE
SWF_LINESTYLE_FLAG_ENDCAP_ROUND = _mingc.SWF_LINESTYLE_FLAG_ENDCAP_ROUND
SWF_LINESTYLE_FLAG_ENDCAP_NONE = _mingc.SWF_LINESTYLE_FLAG_ENDCAP_NONE
SWF_LINESTYLE_FLAG_ENDCAP_SQUARE = _mingc.SWF_LINESTYLE_FLAG_ENDCAP_SQUARE

def newSWFLineStyle2(*args):
  return _mingc.newSWFLineStyle2(*args)
newSWFLineStyle2 = _mingc.newSWFLineStyle2

def newSWFLineStyle2_filled(*args):
  return _mingc.newSWFLineStyle2_filled(*args)
newSWFLineStyle2_filled = _mingc.newSWFLineStyle2_filled
SWF_SHAPE3 = _mingc.SWF_SHAPE3
SWF_SHAPE4 = _mingc.SWF_SHAPE4
SWF_SHAPE_USESCALINGSTROKES = _mingc.SWF_SHAPE_USESCALINGSTROKES
SWF_SHAPE_USENONSCALINGSTROKES = _mingc.SWF_SHAPE_USENONSCALINGSTROKES

def newSWFShape():
  return _mingc.newSWFShape()
newSWFShape = _mingc.newSWFShape

def newSWFShapeFromBitmap(*args):
  return _mingc.newSWFShapeFromBitmap(*args)
newSWFShapeFromBitmap = _mingc.newSWFShapeFromBitmap

def destroySWFShape(*args):
  return _mingc.destroySWFShape(*args)
destroySWFShape = _mingc.destroySWFShape

def SWFShape_end(*args):
  return _mingc.SWFShape_end(*args)
SWFShape_end = _mingc.SWFShape_end

def SWFShape_useVersion(*args):
  return _mingc.SWFShape_useVersion(*args)
SWFShape_useVersion = _mingc.SWFShape_useVersion

def SWFShape_getVersion(*args):
  return _mingc.SWFShape_getVersion(*args)
SWFShape_getVersion = _mingc.SWFShape_getVersion

def SWFShape_setRenderHintingFlags(*args):
  return _mingc.SWFShape_setRenderHintingFlags(*args)
SWFShape_setRenderHintingFlags = _mingc.SWFShape_setRenderHintingFlags

def SWFShape_movePenTo(*args):
  return _mingc.SWFShape_movePenTo(*args)
SWFShape_movePenTo = _mingc.SWFShape_movePenTo

def SWFShape_movePen(*args):
  return _mingc.SWFShape_movePen(*args)
SWFShape_movePen = _mingc.SWFShape_movePen

def SWFShape_getPenX(*args):
  return _mingc.SWFShape_getPenX(*args)
SWFShape_getPenX = _mingc.SWFShape_getPenX

def SWFShape_getPenY(*args):
  return _mingc.SWFShape_getPenY(*args)
SWFShape_getPenY = _mingc.SWFShape_getPenY

def SWFShape_getPen(*args):
  return _mingc.SWFShape_getPen(*args)
SWFShape_getPen = _mingc.SWFShape_getPen

def SWFShape_drawLineTo(*args):
  return _mingc.SWFShape_drawLineTo(*args)
SWFShape_drawLineTo = _mingc.SWFShape_drawLineTo

def SWFShape_drawLine(*args):
  return _mingc.SWFShape_drawLine(*args)
SWFShape_drawLine = _mingc.SWFShape_drawLine

def SWFShape_drawCurveTo(*args):
  return _mingc.SWFShape_drawCurveTo(*args)
SWFShape_drawCurveTo = _mingc.SWFShape_drawCurveTo

def SWFShape_drawCurve(*args):
  return _mingc.SWFShape_drawCurve(*args)
SWFShape_drawCurve = _mingc.SWFShape_drawCurve

def SWFShape_hideLine(*args):
  return _mingc.SWFShape_hideLine(*args)
SWFShape_hideLine = _mingc.SWFShape_hideLine

def SWFShape_addSolidFillStyle(*args):
  return _mingc.SWFShape_addSolidFillStyle(*args)
SWFShape_addSolidFillStyle = _mingc.SWFShape_addSolidFillStyle

def SWFShape_addGradientFillStyle(*args):
  return _mingc.SWFShape_addGradientFillStyle(*args)
SWFShape_addGradientFillStyle = _mingc.SWFShape_addGradientFillStyle

def SWFShape_addBitmapFillStyle(*args):
  return _mingc.SWFShape_addBitmapFillStyle(*args)
SWFShape_addBitmapFillStyle = _mingc.SWFShape_addBitmapFillStyle

def SWFShape_setLeftFillStyle(*args):
  return _mingc.SWFShape_setLeftFillStyle(*args)
SWFShape_setLeftFillStyle = _mingc.SWFShape_setLeftFillStyle

def SWFShape_setRightFillStyle(*args):
  return _mingc.SWFShape_setRightFillStyle(*args)
SWFShape_setRightFillStyle = _mingc.SWFShape_setRightFillStyle

def newSWFMorphShape():
  return _mingc.newSWFMorphShape()
newSWFMorphShape = _mingc.newSWFMorphShape

def destroySWFMorph(*args):
  return _mingc.destroySWFMorph(*args)
destroySWFMorph = _mingc.destroySWFMorph

def SWFMorph_getShape1(*args):
  return _mingc.SWFMorph_getShape1(*args)
SWFMorph_getShape1 = _mingc.SWFMorph_getShape1

def SWFMorph_getShape2(*args):
  return _mingc.SWFMorph_getShape2(*args)
SWFMorph_getShape2 = _mingc.SWFMorph_getShape2

def newSWFFont_fromFile(*args):
  return _mingc.newSWFFont_fromFile(*args)
newSWFFont_fromFile = _mingc.newSWFFont_fromFile

def destroySWFFont(*args):
  return _mingc.destroySWFFont(*args)
destroySWFFont = _mingc.destroySWFFont

def SWFFont_getStringWidth(*args):
  return _mingc.SWFFont_getStringWidth(*args)
SWFFont_getStringWidth = _mingc.SWFFont_getStringWidth

def SWFFont_getUTF8StringWidth(*args):
  return _mingc.SWFFont_getUTF8StringWidth(*args)
SWFFont_getUTF8StringWidth = _mingc.SWFFont_getUTF8StringWidth

def SWFFont_getWideStringWidth(*args):
  return _mingc.SWFFont_getWideStringWidth(*args)
SWFFont_getWideStringWidth = _mingc.SWFFont_getWideStringWidth

def SWFFont_getAscent(*args):
  return _mingc.SWFFont_getAscent(*args)
SWFFont_getAscent = _mingc.SWFFont_getAscent

def SWFFont_getDescent(*args):
  return _mingc.SWFFont_getDescent(*args)
SWFFont_getDescent = _mingc.SWFFont_getDescent

def SWFFont_getLeading(*args):
  return _mingc.SWFFont_getLeading(*args)
SWFFont_getLeading = _mingc.SWFFont_getLeading

def SWFFont_getName(*args):
  return _mingc.SWFFont_getName(*args)
SWFFont_getName = _mingc.SWFFont_getName

def SWFFont_getGlyphCount(*args):
  return _mingc.SWFFont_getGlyphCount(*args)
SWFFont_getGlyphCount = _mingc.SWFFont_getGlyphCount

def newSWFFontCollection_fromFile(*args):
  return _mingc.newSWFFontCollection_fromFile(*args)
newSWFFontCollection_fromFile = _mingc.newSWFFontCollection_fromFile

def SWFFontCollection_getFontCount(*args):
  return _mingc.SWFFontCollection_getFontCount(*args)
SWFFontCollection_getFontCount = _mingc.SWFFontCollection_getFontCount

def SWFFontCollection_getFont(*args):
  return _mingc.SWFFontCollection_getFont(*args)
SWFFontCollection_getFont = _mingc.SWFFontCollection_getFont

def destroySWFFontCollection(*args):
  return _mingc.destroySWFFontCollection(*args)
destroySWFFontCollection = _mingc.destroySWFFontCollection

def newSWFText():
  return _mingc.newSWFText()
newSWFText = _mingc.newSWFText

def newSWFText2():
  return _mingc.newSWFText2()
newSWFText2 = _mingc.newSWFText2

def destroySWFText(*args):
  return _mingc.destroySWFText(*args)
destroySWFText = _mingc.destroySWFText

def SWFText_setFont(*args):
  return _mingc.SWFText_setFont(*args)
SWFText_setFont = _mingc.SWFText_setFont

def SWFText_setHeight(*args):
  return _mingc.SWFText_setHeight(*args)
SWFText_setHeight = _mingc.SWFText_setHeight

def SWFText_setColor(*args):
  return _mingc.SWFText_setColor(*args)
SWFText_setColor = _mingc.SWFText_setColor

def SWFText_moveTo(*args):
  return _mingc.SWFText_moveTo(*args)
SWFText_moveTo = _mingc.SWFText_moveTo

def SWFText_addString(*args):
  return _mingc.SWFText_addString(*args)
SWFText_addString = _mingc.SWFText_addString

def SWFText_addUTF8String(*args):
  return _mingc.SWFText_addUTF8String(*args)
SWFText_addUTF8String = _mingc.SWFText_addUTF8String

def SWFText_addWideString(*args):
  return _mingc.SWFText_addWideString(*args)
SWFText_addWideString = _mingc.SWFText_addWideString

def SWFText_setSpacing(*args):
  return _mingc.SWFText_setSpacing(*args)
SWFText_setSpacing = _mingc.SWFText_setSpacing

def SWFText_getStringWidth(*args):
  return _mingc.SWFText_getStringWidth(*args)
SWFText_getStringWidth = _mingc.SWFText_getStringWidth

def SWFText_getUTF8StringWidth(*args):
  return _mingc.SWFText_getUTF8StringWidth(*args)
SWFText_getUTF8StringWidth = _mingc.SWFText_getUTF8StringWidth

def SWFText_getWideStringWidth(*args):
  return _mingc.SWFText_getWideStringWidth(*args)
SWFText_getWideStringWidth = _mingc.SWFText_getWideStringWidth

def SWFText_getAscent(*args):
  return _mingc.SWFText_getAscent(*args)
SWFText_getAscent = _mingc.SWFText_getAscent

def SWFText_getDescent(*args):
  return _mingc.SWFText_getDescent(*args)
SWFText_getDescent = _mingc.SWFText_getDescent

def SWFText_getLeading(*args):
  return _mingc.SWFText_getLeading(*args)
SWFText_getLeading = _mingc.SWFText_getLeading

def newSWFBrowserFont(*args):
  return _mingc.newSWFBrowserFont(*args)
newSWFBrowserFont = _mingc.newSWFBrowserFont

def destroySWFBrowserFont(*args):
  return _mingc.destroySWFBrowserFont(*args)
destroySWFBrowserFont = _mingc.destroySWFBrowserFont

def SWFFontCharacter_addChars(*args):
  return _mingc.SWFFontCharacter_addChars(*args)
SWFFontCharacter_addChars = _mingc.SWFFontCharacter_addChars

def SWFFontCharacter_addUTF8Chars(*args):
  return _mingc.SWFFontCharacter_addUTF8Chars(*args)
SWFFontCharacter_addUTF8Chars = _mingc.SWFFontCharacter_addUTF8Chars
SWFTEXTFIELD_ONMASK = _mingc.SWFTEXTFIELD_ONMASK
SWFTEXTFIELD_OFFMASK = _mingc.SWFTEXTFIELD_OFFMASK
SWFTEXTFIELD_HASFONT = _mingc.SWFTEXTFIELD_HASFONT
SWFTEXTFIELD_HASLENGTH = _mingc.SWFTEXTFIELD_HASLENGTH
SWFTEXTFIELD_HASCOLOR = _mingc.SWFTEXTFIELD_HASCOLOR
SWFTEXTFIELD_NOEDIT = _mingc.SWFTEXTFIELD_NOEDIT
SWFTEXTFIELD_PASSWORD = _mingc.SWFTEXTFIELD_PASSWORD
SWFTEXTFIELD_MULTILINE = _mingc.SWFTEXTFIELD_MULTILINE
SWFTEXTFIELD_WORDWRAP = _mingc.SWFTEXTFIELD_WORDWRAP
SWFTEXTFIELD_HASTEXT = _mingc.SWFTEXTFIELD_HASTEXT
SWFTEXTFIELD_USEFONT = _mingc.SWFTEXTFIELD_USEFONT
SWFTEXTFIELD_HTML = _mingc.SWFTEXTFIELD_HTML
SWFTEXTFIELD_DRAWBOX = _mingc.SWFTEXTFIELD_DRAWBOX
SWFTEXTFIELD_NOSELECT = _mingc.SWFTEXTFIELD_NOSELECT
SWFTEXTFIELD_HASLAYOUT = _mingc.SWFTEXTFIELD_HASLAYOUT
SWFTEXTFIELD_AUTOSIZE = _mingc.SWFTEXTFIELD_AUTOSIZE
SWFTEXTFIELD_ALIGN_LEFT = _mingc.SWFTEXTFIELD_ALIGN_LEFT
SWFTEXTFIELD_ALIGN_RIGHT = _mingc.SWFTEXTFIELD_ALIGN_RIGHT
SWFTEXTFIELD_ALIGN_CENTER = _mingc.SWFTEXTFIELD_ALIGN_CENTER
SWFTEXTFIELD_ALIGN_JUSTIFY = _mingc.SWFTEXTFIELD_ALIGN_JUSTIFY

def newSWFTextField():
  return _mingc.newSWFTextField()
newSWFTextField = _mingc.newSWFTextField

def destroySWFTextField(*args):
  return _mingc.destroySWFTextField(*args)
destroySWFTextField = _mingc.destroySWFTextField

def SWFTextField_setFont(*args):
  return _mingc.SWFTextField_setFont(*args)
SWFTextField_setFont = _mingc.SWFTextField_setFont

def SWFTextField_setBounds(*args):
  return _mingc.SWFTextField_setBounds(*args)
SWFTextField_setBounds = _mingc.SWFTextField_setBounds

def SWFTextField_setFlags(*args):
  return _mingc.SWFTextField_setFlags(*args)
SWFTextField_setFlags = _mingc.SWFTextField_setFlags

def SWFTextField_setColor(*args):
  return _mingc.SWFTextField_setColor(*args)
SWFTextField_setColor = _mingc.SWFTextField_setColor

def SWFTextField_setVariableName(*args):
  return _mingc.SWFTextField_setVariableName(*args)
SWFTextField_setVariableName = _mingc.SWFTextField_setVariableName

def SWFTextField_addString(*args):
  return _mingc.SWFTextField_addString(*args)
SWFTextField_addString = _mingc.SWFTextField_addString

def SWFTextField_addUTF8String(*args):
  return _mingc.SWFTextField_addUTF8String(*args)
SWFTextField_addUTF8String = _mingc.SWFTextField_addUTF8String

def SWFTextField_setHeight(*args):
  return _mingc.SWFTextField_setHeight(*args)
SWFTextField_setHeight = _mingc.SWFTextField_setHeight

def SWFTextField_setFieldHeight(*args):
  return _mingc.SWFTextField_setFieldHeight(*args)
SWFTextField_setFieldHeight = _mingc.SWFTextField_setFieldHeight

def SWFTextField_setLeftMargin(*args):
  return _mingc.SWFTextField_setLeftMargin(*args)
SWFTextField_setLeftMargin = _mingc.SWFTextField_setLeftMargin

def SWFTextField_setRightMargin(*args):
  return _mingc.SWFTextField_setRightMargin(*args)
SWFTextField_setRightMargin = _mingc.SWFTextField_setRightMargin

def SWFTextField_setIndentation(*args):
  return _mingc.SWFTextField_setIndentation(*args)
SWFTextField_setIndentation = _mingc.SWFTextField_setIndentation

def SWFTextField_setLineSpacing(*args):
  return _mingc.SWFTextField_setLineSpacing(*args)
SWFTextField_setLineSpacing = _mingc.SWFTextField_setLineSpacing

def SWFTextField_setPadding(*args):
  return _mingc.SWFTextField_setPadding(*args)
SWFTextField_setPadding = _mingc.SWFTextField_setPadding

def SWFTextField_addChars(*args):
  return _mingc.SWFTextField_addChars(*args)
SWFTextField_addChars = _mingc.SWFTextField_addChars

def SWFTextField_setAlignment(*args):
  return _mingc.SWFTextField_setAlignment(*args)
SWFTextField_setAlignment = _mingc.SWFTextField_setAlignment

def SWFTextField_setLength(*args):
  return _mingc.SWFTextField_setLength(*args)
SWFTextField_setLength = _mingc.SWFTextField_setLength

def newSWFSoundStream(*args):
  return _mingc.newSWFSoundStream(*args)
newSWFSoundStream = _mingc.newSWFSoundStream

def newSWFSoundStreamFromFileno(*args):
  return _mingc.newSWFSoundStreamFromFileno(*args)
newSWFSoundStreamFromFileno = _mingc.newSWFSoundStreamFromFileno

def newSWFSoundStream_fromInput(*args):
  return _mingc.newSWFSoundStream_fromInput(*args)
newSWFSoundStream_fromInput = _mingc.newSWFSoundStream_fromInput

def destroySWFSoundStream(*args):
  return _mingc.destroySWFSoundStream(*args)
destroySWFSoundStream = _mingc.destroySWFSoundStream

def SWFSoundStream_getDuration(*args):
  return _mingc.SWFSoundStream_getDuration(*args)
SWFSoundStream_getDuration = _mingc.SWFSoundStream_getDuration

def SWFSoundStream_setInitialMp3Delay(*args):
  return _mingc.SWFSoundStream_setInitialMp3Delay(*args)
SWFSoundStream_setInitialMp3Delay = _mingc.SWFSoundStream_setInitialMp3Delay

def newSWFSound(*args):
  return _mingc.newSWFSound(*args)
newSWFSound = _mingc.newSWFSound

def newSWFSoundFromFileno(*args):
  return _mingc.newSWFSoundFromFileno(*args)
newSWFSoundFromFileno = _mingc.newSWFSoundFromFileno

def newSWFSound_fromInput(*args):
  return _mingc.newSWFSound_fromInput(*args)
newSWFSound_fromInput = _mingc.newSWFSound_fromInput

def newSWFSound_fromSoundStream(*args):
  return _mingc.newSWFSound_fromSoundStream(*args)
newSWFSound_fromSoundStream = _mingc.newSWFSound_fromSoundStream

def destroySWFSound(*args):
  return _mingc.destroySWFSound(*args)
destroySWFSound = _mingc.destroySWFSound

def SWFSound_setInitialMp3Delay(*args):
  return _mingc.SWFSound_setInitialMp3Delay(*args)
SWFSound_setInitialMp3Delay = _mingc.SWFSound_setInitialMp3Delay
SWF_SOUND_COMPRESSION = _mingc.SWF_SOUND_COMPRESSION
SWF_SOUND_NOT_COMPRESSED = _mingc.SWF_SOUND_NOT_COMPRESSED
SWF_SOUND_ADPCM_COMPRESSED = _mingc.SWF_SOUND_ADPCM_COMPRESSED
SWF_SOUND_MP3_COMPRESSED = _mingc.SWF_SOUND_MP3_COMPRESSED
SWF_SOUND_NOT_COMPRESSED_LE = _mingc.SWF_SOUND_NOT_COMPRESSED_LE
SWF_SOUND_NELLY_COMPRESSED = _mingc.SWF_SOUND_NELLY_COMPRESSED
SWF_SOUND_RATE = _mingc.SWF_SOUND_RATE
SWF_SOUND_5KHZ = _mingc.SWF_SOUND_5KHZ
SWF_SOUND_11KHZ = _mingc.SWF_SOUND_11KHZ
SWF_SOUND_22KHZ = _mingc.SWF_SOUND_22KHZ
SWF_SOUND_44KHZ = _mingc.SWF_SOUND_44KHZ
SWF_SOUND_BITS = _mingc.SWF_SOUND_BITS
SWF_SOUND_8BITS = _mingc.SWF_SOUND_8BITS
SWF_SOUND_16BITS = _mingc.SWF_SOUND_16BITS
SWF_SOUND_CHANNELS = _mingc.SWF_SOUND_CHANNELS
SWF_SOUND_MONO = _mingc.SWF_SOUND_MONO
SWF_SOUND_STEREO = _mingc.SWF_SOUND_STEREO

def SWFSoundInstance_setLoopInPoint(*args):
  return _mingc.SWFSoundInstance_setLoopInPoint(*args)
SWFSoundInstance_setLoopInPoint = _mingc.SWFSoundInstance_setLoopInPoint

def SWFSoundInstance_setLoopOutPoint(*args):
  return _mingc.SWFSoundInstance_setLoopOutPoint(*args)
SWFSoundInstance_setLoopOutPoint = _mingc.SWFSoundInstance_setLoopOutPoint

def SWFSoundInstance_setLoopCount(*args):
  return _mingc.SWFSoundInstance_setLoopCount(*args)
SWFSoundInstance_setLoopCount = _mingc.SWFSoundInstance_setLoopCount

def SWFSoundInstance_setNoMultiple(*args):
  return _mingc.SWFSoundInstance_setNoMultiple(*args)
SWFSoundInstance_setNoMultiple = _mingc.SWFSoundInstance_setNoMultiple

def newSWFCXform(*args):
  return _mingc.newSWFCXform(*args)
newSWFCXform = _mingc.newSWFCXform

def newSWFAddCXform(*args):
  return _mingc.newSWFAddCXform(*args)
newSWFAddCXform = _mingc.newSWFAddCXform

def newSWFMultCXform(*args):
  return _mingc.newSWFMultCXform(*args)
newSWFMultCXform = _mingc.newSWFMultCXform

def destroySWFCXform(*args):
  return _mingc.destroySWFCXform(*args)
destroySWFCXform = _mingc.destroySWFCXform

def SWFCXform_setColorAdd(*args):
  return _mingc.SWFCXform_setColorAdd(*args)
SWFCXform_setColorAdd = _mingc.SWFCXform_setColorAdd

def SWFCXform_setColorMult(*args):
  return _mingc.SWFCXform_setColorMult(*args)
SWFCXform_setColorMult = _mingc.SWFCXform_setColorMult

def newSWFAction(*args):
  return _mingc.newSWFAction(*args)
newSWFAction = _mingc.newSWFAction

def newSWFAction_fromFile(*args):
  return _mingc.newSWFAction_fromFile(*args)
newSWFAction_fromFile = _mingc.newSWFAction_fromFile

def SWFAction_compile(*args):
  return _mingc.SWFAction_compile(*args)
SWFAction_compile = _mingc.SWFAction_compile

def destroySWFAction(*args):
  return _mingc.destroySWFAction(*args)
destroySWFAction = _mingc.destroySWFAction

def SWFAction_getByteCode(*args):
  return _mingc.SWFAction_getByteCode(*args)
SWFAction_getByteCode = _mingc.SWFAction_getByteCode

def newSWFInitAction(*args):
  return _mingc.newSWFInitAction(*args)
newSWFInitAction = _mingc.newSWFInitAction

def newSWFInitAction_withId(*args):
  return _mingc.newSWFInitAction_withId(*args)
newSWFInitAction_withId = _mingc.newSWFInitAction_withId
SWFBUTTON_HIT = _mingc.SWFBUTTON_HIT
SWFBUTTON_DOWN = _mingc.SWFBUTTON_DOWN
SWFBUTTON_OVER = _mingc.SWFBUTTON_OVER
SWFBUTTON_UP = _mingc.SWFBUTTON_UP
SWFBUTTONRECORD_HITSTATE = _mingc.SWFBUTTONRECORD_HITSTATE
SWFBUTTONRECORD_DOWNSTATE = _mingc.SWFBUTTONRECORD_DOWNSTATE
SWFBUTTONRECORD_OVERSTATE = _mingc.SWFBUTTONRECORD_OVERSTATE
SWFBUTTONRECORD_UPSTATE = _mingc.SWFBUTTONRECORD_UPSTATE
SWFBUTTON_OVERDOWNTOIDLE = _mingc.SWFBUTTON_OVERDOWNTOIDLE
SWFBUTTON_IDLETOOVERDOWN = _mingc.SWFBUTTON_IDLETOOVERDOWN
SWFBUTTON_OUTDOWNTOIDLE = _mingc.SWFBUTTON_OUTDOWNTOIDLE
SWFBUTTON_OUTDOWNTOOVERDOWN = _mingc.SWFBUTTON_OUTDOWNTOOVERDOWN
SWFBUTTON_OVERDOWNTOOUTDOWN = _mingc.SWFBUTTON_OVERDOWNTOOUTDOWN
SWFBUTTON_OVERDOWNTOOVERUP = _mingc.SWFBUTTON_OVERDOWNTOOVERUP
SWFBUTTON_OVERUPTOOVERDOWN = _mingc.SWFBUTTON_OVERUPTOOVERDOWN
SWFBUTTON_OVERUPTOIDLE = _mingc.SWFBUTTON_OVERUPTOIDLE
SWFBUTTON_IDLETOOVERUP = _mingc.SWFBUTTON_IDLETOOVERUP
SWFBUTTON_MOUSEUPOUTSIDE = _mingc.SWFBUTTON_MOUSEUPOUTSIDE
SWFBUTTON_DRAGOVER = _mingc.SWFBUTTON_DRAGOVER
SWFBUTTON_DRAGOUT = _mingc.SWFBUTTON_DRAGOUT
SWFBUTTON_MOUSEUP = _mingc.SWFBUTTON_MOUSEUP
SWFBUTTON_MOUSEDOWN = _mingc.SWFBUTTON_MOUSEDOWN
SWFBUTTON_MOUSEOUT = _mingc.SWFBUTTON_MOUSEOUT
SWFBUTTON_MOUSEOVER = _mingc.SWFBUTTON_MOUSEOVER

def newSWFButton():
  return _mingc.newSWFButton()
newSWFButton = _mingc.newSWFButton

def destroySWFButton(*args):
  return _mingc.destroySWFButton(*args)
destroySWFButton = _mingc.destroySWFButton

def SWFButton_addCharacter(*args):
  return _mingc.SWFButton_addCharacter(*args)
SWFButton_addCharacter = _mingc.SWFButton_addCharacter

def SWFButton_addAction(*args):
  return _mingc.SWFButton_addAction(*args)
SWFButton_addAction = _mingc.SWFButton_addAction

def SWFButton_addSound(*args):
  return _mingc.SWFButton_addSound(*args)
SWFButton_addSound = _mingc.SWFButton_addSound

def SWFButton_setMenu(*args):
  return _mingc.SWFButton_setMenu(*args)
SWFButton_setMenu = _mingc.SWFButton_setMenu

def SWFButton_setScalingGrid(*args):
  return _mingc.SWFButton_setScalingGrid(*args)
SWFButton_setScalingGrid = _mingc.SWFButton_setScalingGrid

def SWFButton_removeScalingGrid(*args):
  return _mingc.SWFButton_removeScalingGrid(*args)
SWFButton_removeScalingGrid = _mingc.SWFButton_removeScalingGrid

def SWFButtonRecord_setDepth(*args):
  return _mingc.SWFButtonRecord_setDepth(*args)
SWFButtonRecord_setDepth = _mingc.SWFButtonRecord_setDepth

def SWFButtonRecord_addFilter(*args):
  return _mingc.SWFButtonRecord_addFilter(*args)
SWFButtonRecord_addFilter = _mingc.SWFButtonRecord_addFilter

def SWFButtonRecord_setBlendMode(*args):
  return _mingc.SWFButtonRecord_setBlendMode(*args)
SWFButtonRecord_setBlendMode = _mingc.SWFButtonRecord_setBlendMode

def SWFButtonRecord_move(*args):
  return _mingc.SWFButtonRecord_move(*args)
SWFButtonRecord_move = _mingc.SWFButtonRecord_move

def SWFButtonRecord_moveTo(*args):
  return _mingc.SWFButtonRecord_moveTo(*args)
SWFButtonRecord_moveTo = _mingc.SWFButtonRecord_moveTo

def SWFButtonRecord_rotate(*args):
  return _mingc.SWFButtonRecord_rotate(*args)
SWFButtonRecord_rotate = _mingc.SWFButtonRecord_rotate

def SWFButtonRecord_rotateTo(*args):
  return _mingc.SWFButtonRecord_rotateTo(*args)
SWFButtonRecord_rotateTo = _mingc.SWFButtonRecord_rotateTo

def SWFButtonRecord_scale(*args):
  return _mingc.SWFButtonRecord_scale(*args)
SWFButtonRecord_scale = _mingc.SWFButtonRecord_scale

def SWFButtonRecord_scaleTo(*args):
  return _mingc.SWFButtonRecord_scaleTo(*args)
SWFButtonRecord_scaleTo = _mingc.SWFButtonRecord_scaleTo

def SWFButtonRecord_skewX(*args):
  return _mingc.SWFButtonRecord_skewX(*args)
SWFButtonRecord_skewX = _mingc.SWFButtonRecord_skewX

def SWFButtonRecord_skewXTo(*args):
  return _mingc.SWFButtonRecord_skewXTo(*args)
SWFButtonRecord_skewXTo = _mingc.SWFButtonRecord_skewXTo

def SWFButtonRecord_skewY(*args):
  return _mingc.SWFButtonRecord_skewY(*args)
SWFButtonRecord_skewY = _mingc.SWFButtonRecord_skewY

def SWFButtonRecord_skewYTo(*args):
  return _mingc.SWFButtonRecord_skewYTo(*args)
SWFButtonRecord_skewYTo = _mingc.SWFButtonRecord_skewYTo
SWFVIDEOSTREAM_MODE_AUTO = _mingc.SWFVIDEOSTREAM_MODE_AUTO
SWFVIDEOSTREAM_MODE_MANUAL = _mingc.SWFVIDEOSTREAM_MODE_MANUAL

def newSWFVideoStream_fromFile(*args):
  return _mingc.newSWFVideoStream_fromFile(*args)
newSWFVideoStream_fromFile = _mingc.newSWFVideoStream_fromFile

def newSWFVideoStream_fromInput(*args):
  return _mingc.newSWFVideoStream_fromInput(*args)
newSWFVideoStream_fromInput = _mingc.newSWFVideoStream_fromInput

def newSWFVideoStream():
  return _mingc.newSWFVideoStream()
newSWFVideoStream = _mingc.newSWFVideoStream

def SWFVideoStream_setDimension(*args):
  return _mingc.SWFVideoStream_setDimension(*args)
SWFVideoStream_setDimension = _mingc.SWFVideoStream_setDimension

def SWFVideoStream_getNumFrames(*args):
  return _mingc.SWFVideoStream_getNumFrames(*args)
SWFVideoStream_getNumFrames = _mingc.SWFVideoStream_getNumFrames

def SWFVideoStream_hasAudio(*args):
  return _mingc.SWFVideoStream_hasAudio(*args)
SWFVideoStream_hasAudio = _mingc.SWFVideoStream_hasAudio

def SWFVideoStream_setFrameMode(*args):
  return _mingc.SWFVideoStream_setFrameMode(*args)
SWFVideoStream_setFrameMode = _mingc.SWFVideoStream_setFrameMode

def SWFVideoStream_nextFrame(*args):
  return _mingc.SWFVideoStream_nextFrame(*args)
SWFVideoStream_nextFrame = _mingc.SWFVideoStream_nextFrame

def SWFVideoStream_seek(*args):
  return _mingc.SWFVideoStream_seek(*args)
SWFVideoStream_seek = _mingc.SWFVideoStream_seek

def destroySWFVideoStream(*args):
  return _mingc.destroySWFVideoStream(*args)
destroySWFVideoStream = _mingc.destroySWFVideoStream

def newSWFSprite():
  return _mingc.newSWFSprite()
newSWFSprite = _mingc.newSWFSprite

def destroySWFSprite(*args):
  return _mingc.destroySWFSprite(*args)
destroySWFSprite = _mingc.destroySWFSprite

def SWFSprite_addBlock(*args):
  return _mingc.SWFSprite_addBlock(*args)
SWFSprite_addBlock = _mingc.SWFSprite_addBlock

def newSWFPosition(*args):
  return _mingc.newSWFPosition(*args)
newSWFPosition = _mingc.newSWFPosition

def destroySWFPosition(*args):
  return _mingc.destroySWFPosition(*args)
destroySWFPosition = _mingc.destroySWFPosition

def SWFPosition_skewX(*args):
  return _mingc.SWFPosition_skewX(*args)
SWFPosition_skewX = _mingc.SWFPosition_skewX

def SWFPosition_skewXTo(*args):
  return _mingc.SWFPosition_skewXTo(*args)
SWFPosition_skewXTo = _mingc.SWFPosition_skewXTo

def SWFPosition_skewY(*args):
  return _mingc.SWFPosition_skewY(*args)
SWFPosition_skewY = _mingc.SWFPosition_skewY

def SWFPosition_skewYTo(*args):
  return _mingc.SWFPosition_skewYTo(*args)
SWFPosition_skewYTo = _mingc.SWFPosition_skewYTo

def SWFPosition_scaleX(*args):
  return _mingc.SWFPosition_scaleX(*args)
SWFPosition_scaleX = _mingc.SWFPosition_scaleX

def SWFPosition_scaleXTo(*args):
  return _mingc.SWFPosition_scaleXTo(*args)
SWFPosition_scaleXTo = _mingc.SWFPosition_scaleXTo

def SWFPosition_scaleY(*args):
  return _mingc.SWFPosition_scaleY(*args)
SWFPosition_scaleY = _mingc.SWFPosition_scaleY

def SWFPosition_scaleYTo(*args):
  return _mingc.SWFPosition_scaleYTo(*args)
SWFPosition_scaleYTo = _mingc.SWFPosition_scaleYTo

def SWFPosition_scaleXY(*args):
  return _mingc.SWFPosition_scaleXY(*args)
SWFPosition_scaleXY = _mingc.SWFPosition_scaleXY

def SWFPosition_scaleXYTo(*args):
  return _mingc.SWFPosition_scaleXYTo(*args)
SWFPosition_scaleXYTo = _mingc.SWFPosition_scaleXYTo

def SWFPosition_getMatrix(*args):
  return _mingc.SWFPosition_getMatrix(*args)
SWFPosition_getMatrix = _mingc.SWFPosition_getMatrix

def SWFPosition_setMatrix(*args):
  return _mingc.SWFPosition_setMatrix(*args)
SWFPosition_setMatrix = _mingc.SWFPosition_setMatrix

def SWFPosition_rotate(*args):
  return _mingc.SWFPosition_rotate(*args)
SWFPosition_rotate = _mingc.SWFPosition_rotate

def SWFPosition_rotateTo(*args):
  return _mingc.SWFPosition_rotateTo(*args)
SWFPosition_rotateTo = _mingc.SWFPosition_rotateTo

def SWFPosition_move(*args):
  return _mingc.SWFPosition_move(*args)
SWFPosition_move = _mingc.SWFPosition_move

def SWFPosition_moveTo(*args):
  return _mingc.SWFPosition_moveTo(*args)
SWFPosition_moveTo = _mingc.SWFPosition_moveTo

def SWFPosition_getRotation(*args):
  return _mingc.SWFPosition_getRotation(*args)
SWFPosition_getRotation = _mingc.SWFPosition_getRotation

def SWFPosition_getX(*args):
  return _mingc.SWFPosition_getX(*args)
SWFPosition_getX = _mingc.SWFPosition_getX

def SWFPosition_getY(*args):
  return _mingc.SWFPosition_getY(*args)
SWFPosition_getY = _mingc.SWFPosition_getY

def SWFPosition_getXY(*args):
  return _mingc.SWFPosition_getXY(*args)
SWFPosition_getXY = _mingc.SWFPosition_getXY

def SWFPosition_getXScale(*args):
  return _mingc.SWFPosition_getXScale(*args)
SWFPosition_getXScale = _mingc.SWFPosition_getXScale

def SWFPosition_getYScale(*args):
  return _mingc.SWFPosition_getYScale(*args)
SWFPosition_getYScale = _mingc.SWFPosition_getYScale

def SWFPosition_getXYScale(*args):
  return _mingc.SWFPosition_getXYScale(*args)
SWFPosition_getXYScale = _mingc.SWFPosition_getXYScale

def SWFPosition_getXSkew(*args):
  return _mingc.SWFPosition_getXSkew(*args)
SWFPosition_getXSkew = _mingc.SWFPosition_getXSkew

def SWFPosition_getYSkew(*args):
  return _mingc.SWFPosition_getYSkew(*args)
SWFPosition_getYSkew = _mingc.SWFPosition_getYSkew

def SWFPosition_getXYSkew(*args):
  return _mingc.SWFPosition_getXYSkew(*args)
SWFPosition_getXYSkew = _mingc.SWFPosition_getXYSkew

def SWFDisplayItem_getCharacter(*args):
  return _mingc.SWFDisplayItem_getCharacter(*args)
SWFDisplayItem_getCharacter = _mingc.SWFDisplayItem_getCharacter

def SWFDisplayItem_endMask(*args):
  return _mingc.SWFDisplayItem_endMask(*args)
SWFDisplayItem_endMask = _mingc.SWFDisplayItem_endMask

def SWFDisplayItem_move(*args):
  return _mingc.SWFDisplayItem_move(*args)
SWFDisplayItem_move = _mingc.SWFDisplayItem_move

def SWFDisplayItem_moveTo(*args):
  return _mingc.SWFDisplayItem_moveTo(*args)
SWFDisplayItem_moveTo = _mingc.SWFDisplayItem_moveTo

def SWFDisplayItem_rotate(*args):
  return _mingc.SWFDisplayItem_rotate(*args)
SWFDisplayItem_rotate = _mingc.SWFDisplayItem_rotate

def SWFDisplayItem_rotateTo(*args):
  return _mingc.SWFDisplayItem_rotateTo(*args)
SWFDisplayItem_rotateTo = _mingc.SWFDisplayItem_rotateTo

def SWFDisplayItem_scale(*args):
  return _mingc.SWFDisplayItem_scale(*args)
SWFDisplayItem_scale = _mingc.SWFDisplayItem_scale

def SWFDisplayItem_scaleTo(*args):
  return _mingc.SWFDisplayItem_scaleTo(*args)
SWFDisplayItem_scaleTo = _mingc.SWFDisplayItem_scaleTo

def SWFDisplayItem_skewX(*args):
  return _mingc.SWFDisplayItem_skewX(*args)
SWFDisplayItem_skewX = _mingc.SWFDisplayItem_skewX

def SWFDisplayItem_skewXTo(*args):
  return _mingc.SWFDisplayItem_skewXTo(*args)
SWFDisplayItem_skewXTo = _mingc.SWFDisplayItem_skewXTo

def SWFDisplayItem_skewY(*args):
  return _mingc.SWFDisplayItem_skewY(*args)
SWFDisplayItem_skewY = _mingc.SWFDisplayItem_skewY

def SWFDisplayItem_skewYTo(*args):
  return _mingc.SWFDisplayItem_skewYTo(*args)
SWFDisplayItem_skewYTo = _mingc.SWFDisplayItem_skewYTo

def SWFDisplayItem_getPosition(*args):
  return _mingc.SWFDisplayItem_getPosition(*args)
SWFDisplayItem_getPosition = _mingc.SWFDisplayItem_getPosition

def SWFDisplayItem_getRotation(*args):
  return _mingc.SWFDisplayItem_getRotation(*args)
SWFDisplayItem_getRotation = _mingc.SWFDisplayItem_getRotation

def SWFDisplayItem_getScale(*args):
  return _mingc.SWFDisplayItem_getScale(*args)
SWFDisplayItem_getScale = _mingc.SWFDisplayItem_getScale

def SWFDisplayItem_getSkew(*args):
  return _mingc.SWFDisplayItem_getSkew(*args)
SWFDisplayItem_getSkew = _mingc.SWFDisplayItem_getSkew

def SWFDisplayItem_getMatrix(*args):
  return _mingc.SWFDisplayItem_getMatrix(*args)
SWFDisplayItem_getMatrix = _mingc.SWFDisplayItem_getMatrix

def SWFDisplayItem_setMatrix(*args):
  return _mingc.SWFDisplayItem_setMatrix(*args)
SWFDisplayItem_setMatrix = _mingc.SWFDisplayItem_setMatrix

def SWFDisplayItem_getDepth(*args):
  return _mingc.SWFDisplayItem_getDepth(*args)
SWFDisplayItem_getDepth = _mingc.SWFDisplayItem_getDepth

def SWFDisplayItem_setDepth(*args):
  return _mingc.SWFDisplayItem_setDepth(*args)
SWFDisplayItem_setDepth = _mingc.SWFDisplayItem_setDepth

def SWFDisplayItem_remove(*args):
  return _mingc.SWFDisplayItem_remove(*args)
SWFDisplayItem_remove = _mingc.SWFDisplayItem_remove

def SWFDisplayItem_setName(*args):
  return _mingc.SWFDisplayItem_setName(*args)
SWFDisplayItem_setName = _mingc.SWFDisplayItem_setName

def SWFDisplayItem_setMaskLevel(*args):
  return _mingc.SWFDisplayItem_setMaskLevel(*args)
SWFDisplayItem_setMaskLevel = _mingc.SWFDisplayItem_setMaskLevel

def SWFDisplayItem_setRatio(*args):
  return _mingc.SWFDisplayItem_setRatio(*args)
SWFDisplayItem_setRatio = _mingc.SWFDisplayItem_setRatio

def SWFDisplayItem_setCXform(*args):
  return _mingc.SWFDisplayItem_setCXform(*args)
SWFDisplayItem_setCXform = _mingc.SWFDisplayItem_setCXform

def SWFDisplayItem_setColorAdd(*args):
  return _mingc.SWFDisplayItem_setColorAdd(*args)
SWFDisplayItem_setColorAdd = _mingc.SWFDisplayItem_setColorAdd

def SWFDisplayItem_setColorMult(*args):
  return _mingc.SWFDisplayItem_setColorMult(*args)
SWFDisplayItem_setColorMult = _mingc.SWFDisplayItem_setColorMult
SWFACTION_ONLOAD = _mingc.SWFACTION_ONLOAD
SWFACTION_ENTERFRAME = _mingc.SWFACTION_ENTERFRAME
SWFACTION_UNLOAD = _mingc.SWFACTION_UNLOAD
SWFACTION_MOUSEMOVE = _mingc.SWFACTION_MOUSEMOVE
SWFACTION_MOUSEDOWN = _mingc.SWFACTION_MOUSEDOWN
SWFACTION_MOUSEUP = _mingc.SWFACTION_MOUSEUP
SWFACTION_KEYDOWN = _mingc.SWFACTION_KEYDOWN
SWFACTION_KEYUP = _mingc.SWFACTION_KEYUP
SWFACTION_DATA = _mingc.SWFACTION_DATA

def SWFDisplayItem_addAction(*args):
  return _mingc.SWFDisplayItem_addAction(*args)
SWFDisplayItem_addAction = _mingc.SWFDisplayItem_addAction

def SWFDisplayItem_cacheAsBitmap(*args):
  return _mingc.SWFDisplayItem_cacheAsBitmap(*args)
SWFDisplayItem_cacheAsBitmap = _mingc.SWFDisplayItem_cacheAsBitmap
SWFBLEND_MODE_NULL = _mingc.SWFBLEND_MODE_NULL
SWFBLEND_MODE_NORMAL = _mingc.SWFBLEND_MODE_NORMAL
SWFBLEND_MODE_LAYER = _mingc.SWFBLEND_MODE_LAYER
SWFBLEND_MODE_MULT = _mingc.SWFBLEND_MODE_MULT
SWFBLEND_MODE_SCREEN = _mingc.SWFBLEND_MODE_SCREEN
SWFBLEND_MODE_LIGHTEN = _mingc.SWFBLEND_MODE_LIGHTEN
SWFBLEND_MODE_DARKEN = _mingc.SWFBLEND_MODE_DARKEN
SWFBLEND_MODE_DIFF = _mingc.SWFBLEND_MODE_DIFF
SWFBLEND_MODE_ADD = _mingc.SWFBLEND_MODE_ADD
SWFBLEND_MODE_SUB = _mingc.SWFBLEND_MODE_SUB
SWFBLEND_MODE_INV = _mingc.SWFBLEND_MODE_INV
SWFBLEND_MODE_ALPHA = _mingc.SWFBLEND_MODE_ALPHA
SWFBLEND_MODE_ERASE = _mingc.SWFBLEND_MODE_ERASE
SWFBLEND_MODE_OVERLAY = _mingc.SWFBLEND_MODE_OVERLAY
SWFBLEND_MODE_HARDLIGHT = _mingc.SWFBLEND_MODE_HARDLIGHT

def SWFDisplayItem_setBlendMode(*args):
  return _mingc.SWFDisplayItem_setBlendMode(*args)
SWFDisplayItem_setBlendMode = _mingc.SWFDisplayItem_setBlendMode

def newSWFFill(*args):
  return _mingc.newSWFFill(*args)
newSWFFill = _mingc.newSWFFill

def destroySWFFill(*args):
  return _mingc.destroySWFFill(*args)
destroySWFFill = _mingc.destroySWFFill

def SWFFill_getFillStyle(*args):
  return _mingc.SWFFill_getFillStyle(*args)
SWFFill_getFillStyle = _mingc.SWFFill_getFillStyle

def SWFFill_skewX(*args):
  return _mingc.SWFFill_skewX(*args)
SWFFill_skewX = _mingc.SWFFill_skewX

def SWFFill_skewXTo(*args):
  return _mingc.SWFFill_skewXTo(*args)
SWFFill_skewXTo = _mingc.SWFFill_skewXTo

def SWFFill_skewY(*args):
  return _mingc.SWFFill_skewY(*args)
SWFFill_skewY = _mingc.SWFFill_skewY

def SWFFill_skewYTo(*args):
  return _mingc.SWFFill_skewYTo(*args)
SWFFill_skewYTo = _mingc.SWFFill_skewYTo

def SWFFill_scaleX(*args):
  return _mingc.SWFFill_scaleX(*args)
SWFFill_scaleX = _mingc.SWFFill_scaleX

def SWFFill_scaleXTo(*args):
  return _mingc.SWFFill_scaleXTo(*args)
SWFFill_scaleXTo = _mingc.SWFFill_scaleXTo

def SWFFill_scaleY(*args):
  return _mingc.SWFFill_scaleY(*args)
SWFFill_scaleY = _mingc.SWFFill_scaleY

def SWFFill_scaleYTo(*args):
  return _mingc.SWFFill_scaleYTo(*args)
SWFFill_scaleYTo = _mingc.SWFFill_scaleYTo

def SWFFill_scaleXY(*args):
  return _mingc.SWFFill_scaleXY(*args)
SWFFill_scaleXY = _mingc.SWFFill_scaleXY

def SWFFill_scaleXYTo(*args):
  return _mingc.SWFFill_scaleXYTo(*args)
SWFFill_scaleXYTo = _mingc.SWFFill_scaleXYTo

def SWFFill_rotate(*args):
  return _mingc.SWFFill_rotate(*args)
SWFFill_rotate = _mingc.SWFFill_rotate

def SWFFill_rotateTo(*args):
  return _mingc.SWFFill_rotateTo(*args)
SWFFill_rotateTo = _mingc.SWFFill_rotateTo

def SWFFill_move(*args):
  return _mingc.SWFFill_move(*args)
SWFFill_move = _mingc.SWFFill_move

def SWFFill_moveTo(*args):
  return _mingc.SWFFill_moveTo(*args)
SWFFill_moveTo = _mingc.SWFFill_moveTo

def SWFFill_setMatrix(*args):
  return _mingc.SWFFill_setMatrix(*args)
SWFFill_setMatrix = _mingc.SWFFill_setMatrix

def SWFShape_setLine(*args):
  return _mingc.SWFShape_setLine(*args)
SWFShape_setLine = _mingc.SWFShape_setLine

def SWFShape_setLine2Filled(*args):
  return _mingc.SWFShape_setLine2Filled(*args)
SWFShape_setLine2Filled = _mingc.SWFShape_setLine2Filled

def SWFShape_setLine2(*args):
  return _mingc.SWFShape_setLine2(*args)
SWFShape_setLine2 = _mingc.SWFShape_setLine2

def SWFShape_addSolidFill(*args):
  return _mingc.SWFShape_addSolidFill(*args)
SWFShape_addSolidFill = _mingc.SWFShape_addSolidFill

def SWFShape_addGradientFill(*args):
  return _mingc.SWFShape_addGradientFill(*args)
SWFShape_addGradientFill = _mingc.SWFShape_addGradientFill

def SWFShape_addBitmapFill(*args):
  return _mingc.SWFShape_addBitmapFill(*args)
SWFShape_addBitmapFill = _mingc.SWFShape_addBitmapFill

def SWFShape_setLeftFill(*args):
  return _mingc.SWFShape_setLeftFill(*args)
SWFShape_setLeftFill = _mingc.SWFShape_setLeftFill

def SWFShape_setRightFill(*args):
  return _mingc.SWFShape_setRightFill(*args)
SWFShape_setRightFill = _mingc.SWFShape_setRightFill

def SWFShape_drawArc(*args):
  return _mingc.SWFShape_drawArc(*args)
SWFShape_drawArc = _mingc.SWFShape_drawArc

def SWFShape_drawCircle(*args):
  return _mingc.SWFShape_drawCircle(*args)
SWFShape_drawCircle = _mingc.SWFShape_drawCircle

def SWFShape_drawGlyph(*args):
  return _mingc.SWFShape_drawGlyph(*args)
SWFShape_drawGlyph = _mingc.SWFShape_drawGlyph

def SWFShape_drawSizedGlyph(*args):
  return _mingc.SWFShape_drawSizedGlyph(*args)
SWFShape_drawSizedGlyph = _mingc.SWFShape_drawSizedGlyph

def SWFShape_drawCubic(*args):
  return _mingc.SWFShape_drawCubic(*args)
SWFShape_drawCubic = _mingc.SWFShape_drawCubic

def SWFShape_drawCubicTo(*args):
  return _mingc.SWFShape_drawCubicTo(*args)
SWFShape_drawCubicTo = _mingc.SWFShape_drawCubicTo

def SWFShape_drawCharacterBounds(*args):
  return _mingc.SWFShape_drawCharacterBounds(*args)
SWFShape_drawCharacterBounds = _mingc.SWFShape_drawCharacterBounds

def newSWFMovieClip():
  return _mingc.newSWFMovieClip()
newSWFMovieClip = _mingc.newSWFMovieClip

def destroySWFMovieClip(*args):
  return _mingc.destroySWFMovieClip(*args)
destroySWFMovieClip = _mingc.destroySWFMovieClip

def SWFMovieClip_setNumberOfFrames(*args):
  return _mingc.SWFMovieClip_setNumberOfFrames(*args)
SWFMovieClip_setNumberOfFrames = _mingc.SWFMovieClip_setNumberOfFrames

def SWFMovieClip_nextFrame(*args):
  return _mingc.SWFMovieClip_nextFrame(*args)
SWFMovieClip_nextFrame = _mingc.SWFMovieClip_nextFrame

def SWFMovieClip_labelFrame(*args):
  return _mingc.SWFMovieClip_labelFrame(*args)
SWFMovieClip_labelFrame = _mingc.SWFMovieClip_labelFrame

def SWFMovieClip_add(*args):
  return _mingc.SWFMovieClip_add(*args)
SWFMovieClip_add = _mingc.SWFMovieClip_add

def SWFMovieClip_remove(*args):
  return _mingc.SWFMovieClip_remove(*args)
SWFMovieClip_remove = _mingc.SWFMovieClip_remove

def SWFMovieClip_setSoundStreamAt(*args):
  return _mingc.SWFMovieClip_setSoundStreamAt(*args)
SWFMovieClip_setSoundStreamAt = _mingc.SWFMovieClip_setSoundStreamAt

def SWFMovieClip_setSoundStream(*args):
  return _mingc.SWFMovieClip_setSoundStream(*args)
SWFMovieClip_setSoundStream = _mingc.SWFMovieClip_setSoundStream

def SWFMovieClip_startSound(*args):
  return _mingc.SWFMovieClip_startSound(*args)
SWFMovieClip_startSound = _mingc.SWFMovieClip_startSound

def SWFMovieClip_stopSound(*args):
  return _mingc.SWFMovieClip_stopSound(*args)
SWFMovieClip_stopSound = _mingc.SWFMovieClip_stopSound

def destroySWFPrebuiltClip(*args):
  return _mingc.destroySWFPrebuiltClip(*args)
destroySWFPrebuiltClip = _mingc.destroySWFPrebuiltClip

def newSWFPrebuiltClip_fromFile(*args):
  return _mingc.newSWFPrebuiltClip_fromFile(*args)
newSWFPrebuiltClip_fromFile = _mingc.newSWFPrebuiltClip_fromFile

def newSWFPrebuiltClip_fromInput(*args):
  return _mingc.newSWFPrebuiltClip_fromInput(*args)
newSWFPrebuiltClip_fromInput = _mingc.newSWFPrebuiltClip_fromInput

def newSWFBinaryData(*args):
  return _mingc.newSWFBinaryData(*args)
newSWFBinaryData = _mingc.newSWFBinaryData

def newSWFMovie():
  return _mingc.newSWFMovie()
newSWFMovie = _mingc.newSWFMovie

def newSWFMovieWithVersion(*args):
  return _mingc.newSWFMovieWithVersion(*args)
newSWFMovieWithVersion = _mingc.newSWFMovieWithVersion

def destroySWFMovie(*args):
  return _mingc.destroySWFMovie(*args)
destroySWFMovie = _mingc.destroySWFMovie

def SWFMovie_setRate(*args):
  return _mingc.SWFMovie_setRate(*args)
SWFMovie_setRate = _mingc.SWFMovie_setRate

def SWFMovie_getRate(*args):
  return _mingc.SWFMovie_getRate(*args)
SWFMovie_getRate = _mingc.SWFMovie_getRate

def SWFMovie_setDimension(*args):
  return _mingc.SWFMovie_setDimension(*args)
SWFMovie_setDimension = _mingc.SWFMovie_setDimension

def SWFMovie_setNumberOfFrames(*args):
  return _mingc.SWFMovie_setNumberOfFrames(*args)
SWFMovie_setNumberOfFrames = _mingc.SWFMovie_setNumberOfFrames

def SWFMovie_addExport(*args):
  return _mingc.SWFMovie_addExport(*args)
SWFMovie_addExport = _mingc.SWFMovie_addExport

def SWFMovie_setBackground(*args):
  return _mingc.SWFMovie_setBackground(*args)
SWFMovie_setBackground = _mingc.SWFMovie_setBackground

def SWFMovie_setSoundStream(*args):
  return _mingc.SWFMovie_setSoundStream(*args)
SWFMovie_setSoundStream = _mingc.SWFMovie_setSoundStream

def SWFMovie_setSoundStreamAt(*args):
  return _mingc.SWFMovie_setSoundStreamAt(*args)
SWFMovie_setSoundStreamAt = _mingc.SWFMovie_setSoundStreamAt

def SWFMovie_startSound(*args):
  return _mingc.SWFMovie_startSound(*args)
SWFMovie_startSound = _mingc.SWFMovie_startSound

def SWFMovie_stopSound(*args):
  return _mingc.SWFMovie_stopSound(*args)
SWFMovie_stopSound = _mingc.SWFMovie_stopSound

def SWFMovie_add(*args):
  return _mingc.SWFMovie_add(*args)
SWFMovie_add = _mingc.SWFMovie_add

def SWFMovie_remove(*args):
  return _mingc.SWFMovie_remove(*args)
SWFMovie_remove = _mingc.SWFMovie_remove

def SWFMovie_nextFrame(*args):
  return _mingc.SWFMovie_nextFrame(*args)
SWFMovie_nextFrame = _mingc.SWFMovie_nextFrame

def SWFMovie_labelFrame(*args):
  return _mingc.SWFMovie_labelFrame(*args)
SWFMovie_labelFrame = _mingc.SWFMovie_labelFrame

def SWFMovie_output(*args):
  return _mingc.SWFMovie_output(*args)
SWFMovie_output = _mingc.SWFMovie_output

def SWFMovie_save(*args):
  return _mingc.SWFMovie_save(*args)
SWFMovie_save = _mingc.SWFMovie_save

def SWFMovie_protect(*args):
  return _mingc.SWFMovie_protect(*args)
SWFMovie_protect = _mingc.SWFMovie_protect

def SWFMovie_setNetworkAccess(*args):
  return _mingc.SWFMovie_setNetworkAccess(*args)
SWFMovie_setNetworkAccess = _mingc.SWFMovie_setNetworkAccess

def SWFMovie_addMetadata(*args):
  return _mingc.SWFMovie_addMetadata(*args)
SWFMovie_addMetadata = _mingc.SWFMovie_addMetadata

def SWFMovie_setScriptLimits(*args):
  return _mingc.SWFMovie_setScriptLimits(*args)
SWFMovie_setScriptLimits = _mingc.SWFMovie_setScriptLimits

def SWFMovie_setTabIndex(*args):
  return _mingc.SWFMovie_setTabIndex(*args)
SWFMovie_setTabIndex = _mingc.SWFMovie_setTabIndex

def SWFMovie_importFont(*args):
  return _mingc.SWFMovie_importFont(*args)
SWFMovie_importFont = _mingc.SWFMovie_importFont

def SWFMovie_addFont(*args):
  return _mingc.SWFMovie_addFont(*args)
SWFMovie_addFont = _mingc.SWFMovie_addFont

def SWFMovie_importCharacter(*args):
  return _mingc.SWFMovie_importCharacter(*args)
SWFMovie_importCharacter = _mingc.SWFMovie_importCharacter

def SWFMovie_assignSymbol(*args):
  return _mingc.SWFMovie_assignSymbol(*args)
SWFMovie_assignSymbol = _mingc.SWFMovie_assignSymbol

def SWFMovie_defineScene(*args):
  return _mingc.SWFMovie_defineScene(*args)
SWFMovie_defineScene = _mingc.SWFMovie_defineScene

def SWFMovie_namedAnchor(*args):
  return _mingc.SWFMovie_namedAnchor(*args)
SWFMovie_namedAnchor = _mingc.SWFMovie_namedAnchor

def SWFMovie_writeExports(*args):
  return _mingc.SWFMovie_writeExports(*args)
SWFMovie_writeExports = _mingc.SWFMovie_writeExports
SWFFILTER_MODE_INNER = _mingc.SWFFILTER_MODE_INNER
SWFFILTER_MODE_KO = _mingc.SWFFILTER_MODE_KO
SWFFILTER_MODE_COMPOSITE = _mingc.SWFFILTER_MODE_COMPOSITE
SWFFILTER_MODE_ONTOP = _mingc.SWFFILTER_MODE_ONTOP
SWFFILTER_FLAG_CLAMP = _mingc.SWFFILTER_FLAG_CLAMP
SWFFILTER_FLAG_PRESERVE_ALPHA = _mingc.SWFFILTER_FLAG_PRESERVE_ALPHA
SWFFILTER_TYPE_DROPSHADOW = _mingc.SWFFILTER_TYPE_DROPSHADOW
SWFFILTER_TYPE_BLUR = _mingc.SWFFILTER_TYPE_BLUR
SWFFILTER_TYPE_GLOW = _mingc.SWFFILTER_TYPE_GLOW
SWFFILTER_TYPE_BEVEL = _mingc.SWFFILTER_TYPE_BEVEL
SWFFILTER_TYPE_GRADIENTGLOW = _mingc.SWFFILTER_TYPE_GRADIENTGLOW
SWFFILTER_TYPE_CONVOLUTION = _mingc.SWFFILTER_TYPE_CONVOLUTION
SWFFILTER_TYPE_COLORMATRIX = _mingc.SWFFILTER_TYPE_COLORMATRIX
SWFFILTER_TYPE_GRADIENTBEVEL = _mingc.SWFFILTER_TYPE_GRADIENTBEVEL
class SWFColor(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SWFColor, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SWFColor, name)
    __repr__ = _swig_repr
    __swig_setmethods__["red"] = _mingc.SWFColor_red_set
    __swig_getmethods__["red"] = _mingc.SWFColor_red_get
    if _newclass:red = _swig_property(_mingc.SWFColor_red_get, _mingc.SWFColor_red_set)
    __swig_setmethods__["green"] = _mingc.SWFColor_green_set
    __swig_getmethods__["green"] = _mingc.SWFColor_green_get
    if _newclass:green = _swig_property(_mingc.SWFColor_green_get, _mingc.SWFColor_green_set)
    __swig_setmethods__["blue"] = _mingc.SWFColor_blue_set
    __swig_getmethods__["blue"] = _mingc.SWFColor_blue_get
    if _newclass:blue = _swig_property(_mingc.SWFColor_blue_get, _mingc.SWFColor_blue_set)
    __swig_setmethods__["alpha"] = _mingc.SWFColor_alpha_set
    __swig_getmethods__["alpha"] = _mingc.SWFColor_alpha_get
    if _newclass:alpha = _swig_property(_mingc.SWFColor_alpha_get, _mingc.SWFColor_alpha_set)
    def __init__(self): 
        this = _mingc.new_SWFColor()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _mingc.delete_SWFColor
    __del__ = lambda self : None;
SWFColor_swigregister = _mingc.SWFColor_swigregister
SWFColor_swigregister(SWFColor)


def newSWFShadow(*args):
  return _mingc.newSWFShadow(*args)
newSWFShadow = _mingc.newSWFShadow

def destroySWFShadow(*args):
  return _mingc.destroySWFShadow(*args)
destroySWFShadow = _mingc.destroySWFShadow

def newSWFBlur(*args):
  return _mingc.newSWFBlur(*args)
newSWFBlur = _mingc.newSWFBlur

def destroySWFBlur(*args):
  return _mingc.destroySWFBlur(*args)
destroySWFBlur = _mingc.destroySWFBlur

def newSWFFilterMatrix(*args):
  return _mingc.newSWFFilterMatrix(*args)
newSWFFilterMatrix = _mingc.newSWFFilterMatrix

def destroySWFFilterMatrix(*args):
  return _mingc.destroySWFFilterMatrix(*args)
destroySWFFilterMatrix = _mingc.destroySWFFilterMatrix

def destroySWFFilter(*args):
  return _mingc.destroySWFFilter(*args)
destroySWFFilter = _mingc.destroySWFFilter

def newColorMatrixFilter(*args):
  return _mingc.newColorMatrixFilter(*args)
newColorMatrixFilter = _mingc.newColorMatrixFilter

def newConvolutionFilter(*args):
  return _mingc.newConvolutionFilter(*args)
newConvolutionFilter = _mingc.newConvolutionFilter

def newGradientBevelFilter(*args):
  return _mingc.newGradientBevelFilter(*args)
newGradientBevelFilter = _mingc.newGradientBevelFilter

def newGradientGlowFilter(*args):
  return _mingc.newGradientGlowFilter(*args)
newGradientGlowFilter = _mingc.newGradientGlowFilter

def newBevelFilter(*args):
  return _mingc.newBevelFilter(*args)
newBevelFilter = _mingc.newBevelFilter

def newGlowFilter(*args):
  return _mingc.newGlowFilter(*args)
newGlowFilter = _mingc.newGlowFilter

def newBlurFilter(*args):
  return _mingc.newBlurFilter(*args)
newBlurFilter = _mingc.newBlurFilter

def newDropShadowFilter(*args):
  return _mingc.newDropShadowFilter(*args)
newDropShadowFilter = _mingc.newDropShadowFilter

def SWFDisplayItem_addFilter(*args):
  return _mingc.SWFDisplayItem_addFilter(*args)
SWFDisplayItem_addFilter = _mingc.SWFDisplayItem_addFilter


