#!/usr/bin/perl -w
# Generated by swftoperl converter included with ming. Have fun. 

# Change this to your needs. If you installed perl-ming global you don't need this.
#use lib("/home/peter/mystuff/lib/site_perl");

# We import all because our converter is not so clever to select only needed. ;-)
use SWF qw(:ALL);
# Just copy from a sample, needed to use Constants like SWFFILL_RADIAL_GRADIENT
use SWF::Constants qw(:Text :Button :DisplayItem :Fill);

$m = SWF::Movie::newSWFMovieWithVersion(8);

SWF::setScale(1.0);
#Unknown block type 69

# SWF_DEFINESHAPE3 

# Shape 1 (TYPE=3, RECT=-10,2010 -10,2010)
$character1 = new SWF::Shape();
#1 fillstyle(s)
$character1_f0_red   = 0xff;
$character1_f0_green = 0x80;
$character1_f0_blue  = 0x00;
$character1_f0_alpha = 0xff;
$character1_f0 = $character1->addSolidFill($character1_f0_red, $character1_f0_green, $character1_f0_blue, $character1_f0_alpha ); #SWFFILL_SOLID
#1 linestyles(s)
$character1_l0_width = 20;
$character1_l0_red   = 0x00;
$character1_l0_green = 0x00;
$character1_l0_blue  = 0x00;
$character1_l0_alpha = 0xff;
# StateLineStyle: 1 
$character1->setLine($character1_l0_width, $character1_l0_red, $character1_l0_green, $character1_l0_blue, $character1_l0_alpha);
$character1->setRightFill($character1_f0);
$character1->drawLine(2000, 0);
$character1->drawLine(0, 2000);
$character1->drawLine(-2000, 0);
$character1->drawLine(0, -2000);

# SWF_PLACEOBJECT2 
$i1 = $m->add($character1);
$i1->setDepth(1);
# PlaceFlagHasMatrix 

# SWF_SHOWFRAME 
$m->nextFrame(); # end of frame 1 

# SWF_END 

$m->save("test01.swf");
