#!/usr/bin/perl -w
# Generated by swftoperl converter included with ming. Have fun. 

# Change this to your needs. If you installed perl-ming global you don't need this.
#use lib("/home/peter/mystuff/lib/site_perl");

# We import all because our converter is not so clever to select only needed. ;-)
use SWF qw(:ALL);
# Just copy from a sample, needed to use Constants like SWFFILL_RADIAL_GRADIENT
use SWF::Constants qw(:Text :Button :DisplayItem :Fill);

$m = SWF::Movie::newSWFMovieWithVersion(9);

SWF::setScale(1.0);
$m->setFrames(10);
#Unknown block type 69

# SWF_SHOWFRAME 
$m->nextFrame(); # end of frame 1 

# SWF_SHOWFRAME 
$m->nextFrame(); # end of frame 2 

# SWF_SHOWFRAME 
$m->nextFrame(); # end of frame 3 

# SWF_SHOWFRAME 
$m->nextFrame(); # end of frame 4 

# SWF_SHOWFRAME 
$m->nextFrame(); # end of frame 5 

# SWF_SHOWFRAME 
$m->nextFrame(); # end of frame 6 

# SWF_SHOWFRAME 
$m->nextFrame(); # end of frame 7 

# SWF_SHOWFRAME 
$m->nextFrame(); # end of frame 8 

# SWF_SHOWFRAME 
$m->nextFrame(); # end of frame 9 

# SWF_SHOWFRAME 
$m->nextFrame(); # end of frame 10 

# SWF_DEFINESCENEANDFRAMEDATA 
$m->defineScene(0, "test0");
$m->defineScene(5, "test1");

# SWF_END 

$m->save("test01.swf");
