# This file was automatically generated by SWIG
package mingc;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package mingc;
bootstrap mingc;
var_mingc_init();
package mingc;
@EXPORT = qw( );
1;
