.TH dbl2png 1 "25 Nov 2009" "" "Ming utils"
.\" $Id$
.SH NAME
dbl2png - convert a dbl file to an png file
.SH SYNOPSIS
.B dbl2png [--verbose] <file.dbl>
.SH DESCRIPTION
.B dbl2png
is a command line tool for converting a dbl file into a png file. Output is written to file.png.
H OPTIONS
.TP
\fB\--verbose\fR
displays additional information during processing.
.TP
\fB<file.dbl>\fR
Name of dbl format file to use as input.
.SH AUTHOR
Written by Albrecht Kleine <kleine@ak.sax.de>
.SH COPYRIGHT
Code is released under the GNU GPL license.
