.TH gif2mask 1 "25 Nov 2009" "" "Ming utils"
.\" $Id$
.SH NAME
gif2mask - convert a gif file to an aaaalpha mask
.SH SYNOPSIS
.B gif2mask <file.gif>
.SH DESCRIPTION
.B gif2mask
is a command line tool for converting a gif file into an alpha mask file. Output is written to file.msk.
H OPTIONS
.TP
\fB<file.gif>\fR
Name of gif format file to use as input.
.SH AUTHOR
Written by ?????
.SH COPYRIGHT
Code is released under the GNU GPL license.
