.TH gif2dbl 1 "25 Nov 2009" "" "Ming utils"
.\" $Id$
.SH NAME
gif2dbl - convert a gif file to an dbl file using a RGB palette
.SH SYNOPSIS
.B gif2dbl <file.gif>
.SH DESCRIPTION
.B gif2dbl
is a command line tool for converting a gif file into a dbl file. Output is written to file.dbl.
H OPTIONS
.TP
\fB<file.gif>\fR
Name of gif format file to use as input.
.SH AUTHOR
Written by Raffaele Sena (raff@aromatic.org)
.SH COPYRIGHT
Code is released under the GNU GPL license.
