.TH listfdb 1 "25 Nov 2009" "" "Ming utils"
.\" $Id$
.SH NAME
listfdb - display the contents of a fdb format file
.SH SYNOPSIS
.B listfdb <file.fdb>
.SH DESCRIPTION
.B listfdb
is a command line tool for dumping the contents of a fdb format file.
A fdb format file is a swf format file that only contains a DefineFont2 block.
H OPTIONS
.TP
\fB<file.fdb>\fR
Name of fdb format file to use as input.
.SH AUTHOR
Written by ????
.SH COPYRIGHT
Code is released under the GNU GPL license.
