.TH listjpeg 1 "25 Nov 2009" "" "Ming utils"
.\" $Id$
.SH NAME
listjpeg - display the contents of a jpeg format file
.SH SYNOPSIS
.B listjpeg <file.jpg>
.SH DESCRIPTION
.B listjpeg
is a command line tool for dumping the contents of a jpeg format file.
H OPTIONS
.TP
\fB<file.jpg>\fR
Name of jpeg format file to use as input.
.SH AUTHOR
Written by ????
.SH COPYRIGHT
Code is released under the GNU GPL license.
