.TH listmp3 1 "25 Nov 2009" "" "Ming utils"
.\" $Id$
.SH NAME
listmp3 - display the contents of a mp3 format file
.SH SYNOPSIS
.B listmp3 <file.mp3>
.SH DESCRIPTION
.B listmp3
is a command line tool for dumping the contents of a mp3 format file.
H OPTIONS
.TP
\fB<file.mp3>\fR
Name of mp3 format file to use as input.
.SH AUTHOR
Written by ????
.SH COPYRIGHT
Code is released under the GNU GPL license.
