.TH makefdb 1 "25 Nov 2009" "" "Ming utils"
.\" $Id$
.SH NAME
makefdb - extract fdb files from a swf file
.SH SYNOPSIS
.B makefdb <file.fdb>
.SH DESCRIPTION
.B makefdb
is a command line tool for extracting font blocks from a swf file.
For every fontblock found a .fdb file is wirtten with the associated font name.
H OPTIONS
.TP
\fB\-v\fR
Enable verbose output while processing the file.
.TP
\fB<file.swf>\fR
Name of swf format file to use as input.
.SH AUTHOR
Written by ????
.SH COPYRIGHT
Code is released under the GNU GPL license.
