.TH png2dbl 1 "25 Nov 2009" "" "Ming utils"
.\" $Id$
.SH NAME
png2dbl - convert a png file to an dbl file
.SH SYNOPSIS
.B png2dbl [--verbose]] <file.png>
.SH DESCRIPTION
.B png2dbl
is a command line tool for converting a png file into a dbl file. Output is written to file.dbl.
H OPTIONS
.TP
\fB\--verbose\fR
displays additional information during processing.
.TP
\fB<file.png>\fR
Name of png format file to use as input.
.SH AUTHOR
Written by ????
.SH COPYRIGHT
Code is released under the GNU GPL license.
