.TH raw2adpcm 1 "25 Nov 2009" "" "Ming utils"
.\" $Id$
.SH NAME
raw2adpcm - raw2adpcm converts a raw sound data to adpcm compressed
.SH SYNOPSIS
.B raw2adpcm in out [16bit] [stereo]
.SH DESCRIPTION
.B raw2adpcm
is a command line tool for converting a raw sound data to adpcm compressed data.
H OPTIONS
.TP
\fBin\fR
Name of file to use as input.
.TP
\fBout\fR
Name of file to use for the output.
.TP
\fB[16bit]\fR
bits per sample (0=8bit, 1=16bit,default=1=16bit).
.TP
\fB[stereo]\fR
number of channels (0=mono, 1=stereo,default=1=stereo).
.SH AUTHOR
Written by ????
.SH COPYRIGHT
Code is released under the GNU GPL license.
